ReactiveX/RxJava

src/main/java/rx/internal/util/unsafe/SpscArrayQueue.java, src/main/java/rx/observers/TestSubscriber.java, src/test/java/rx/internal/operators/OperatorRetryTest.java
Maybe the error function was not emitting events properly.
=> Operator retry test fix attempt

src/main/java/rx/internal/operators/TakeLastQueueProducer.java, src/test/java/rx/internal/operators/OperatorTakeLastTest.java
Went looking for a bug that wasn't a bug but found this anyway.  ```OperatorTakeLast``` doesn't check ```subscriber.isUnsubscribed()``` while emitting its queued events so I added a failing unit test and the fix.
=> OperatorTakeLast add check for isUnsubscribed to fast path

src/main/java/rx/subscriptions/CompositeSubscription.java, src/test/java/rx/subscriptions/CompositeSubscriptionTest.java
Otherwise, it'll just fail late when unsubscribing, which is much harder to trace.
I discovered this while writing  a unit test, when I didn't properly mock out a method to return a valid Observable. Seems like it would be more likely to happen in test code than production, but still could be a stumbling block that's hard to track down if there's a bug in app logic adding a null subscription.
=> Fail early if a null subscription is added to a CompositeSubscription.

src/test/java/rx/BackpressureTests.java
- Increased the limits of ```testMergeAsyncThenObserveOn```
- Fixed ```testOnBackpressureDrop``` because in case there was no drop at all, the last value would be NUM - 1.
- Changed ```SLOW_PASS_THRU``` to perform non-trivial work that can't be optimized away by JIT.
=> Backpressure tests fix0121

src/test/java/rx/internal/operators/OnSubscribeRefCountTest.java
Because of the 1 ms interval, it is possible a single source value might get emitted but not reach the output.
=> RefCountAsync: adjusted time values as 1 ms is unreliable

src/main/java/rx/internal/operators/BlockingOperatorLatest.java, src/main/java/rx/internal/operators/BlockingOperatorNext.java, src/main/java/rx/internal/operators/BlockingOperatorToIterator.java, src/main/java/rx/observables/BlockingObservable.java, src/test/java/rx/observables/BlockingObservableTest.java
Originated from discussion #1804.
I was considering to make it opt-in, but it would drastically increase number of methods in public API.
What do you think?
=> Unsubscribe when thread is interrupted

src/main/java/rx/schedulers/TrampolineScheduler.java, src/test/java/rx/schedulers/TrampolineSchedulerTest.java
Also adds a unit test for regression.
It appears there is a potential race condition if something adds to/removes from the PQ while it's *inside* the 'poll' operation, which is where the exceptions in #1702 seem to have actually come from. Therefore, the initial null check didn't really address the original problem. The test here seems to reliably recreate those conditions.
I considered using a PriorityBlockingQueue instead of synchronized, but since the isEmpty and poll calls should not allow something to interleave between them and access the queue, a synchronized block seemed wiser here.
=> Fixes NPEs reported in ReactiveX#1702 by synchronizing queue.

src/main/java/rx/internal/operators/OperatorMerge.java, src/test/java/rx/internal/operators/OperatorMergeTest.java
I think I hunted down the bug that was causing missed value emission if scalar source such as ```just()``` was involved. This either manifested as completion without a value or non-completion because the missing scalar value would sit in the queue and prevented onCompleted from draining. (I've also fixed some visibility issues which might had an effect in this.)
In addition, I've discovered a good practice for spuriously failing tests: I create a new ```@Test```method with a loop in it, calling the original test method. This way, the original is not disturbed and the likelihood of failure is increased by the looping test.
Since the whole ```merge```operator is quite complicated, I can't be 100% certain this works despite local tests passing.
See also #2480, #2466 and #1941.
=> Merge: fixed hangs & missed scalar emissions

src/main/java/rx/exceptions/OnErrorThrowable.java, src/main/java/rx/functions/Actions.java, src/main/java/rx/internal/operators/BlockingOperatorNext.java, src/main/java/rx/internal/operators/OnSubscribeCache.java, src/main/java/rx/internal/operators/OperatorGroupBy.java, src/main/java/rx/internal/operators/OperatorObserveOn.java, src/main/java/rx/internal/operators/OperatorPublish.java, src/main/java/rx/internal/operators/OperatorScan.java, src/main/java/rx/observables/BlockingObservable.java, src/main/java/rx/schedulers/CachedThreadScheduler.java, src/main/java/rx/schedulers/TrampolineScheduler.java, src/main/java/rx/subjects/TestSubject.java, src/main/java/rx/subscriptions/Subscriptions.java
more cleanup:
* removed unnecessary imports
* added missing generic types
* added SuppressWarning annotations
=> Warnings cleanup

src/main/java/rx/internal/schedulers/NewThreadWorker.java, src/main/java/rx/schedulers/CachedThreadScheduler.java, src/main/java/rx/schedulers/GenericScheduledExecutorService.java, src/test/java/rx/schedulers/CachedThreadSchedulerTest.java
cancelled task-retention.
First debated in #1922, see also #1919.
We may want to discuss the naming of system parameters. I chose these so RxJava 2.0 specific properties may be trivially separated:
``` io.reactivex.rxjava.scheduler.jdk6.purge-frequency-millis ```
Specifies the purge frequency in milliseconds. Default is 1000.
``` io.reactivex.rxjava.scheduler.jdk6.purge-force ```
Forces the use of the purge (if set to true) even if the setRemoveOnCancelPolicy is supported. The benefit is that removing cancelled tasks now runs on a different thread so the main pool thread doesn't waste time on them. The drawback is the retention window can be still to large.
Do we have a wiki page where such parameters are listed?
=> ScheduledExecutorService: call purge periodically on JDK 6 to avoid

src/main/java/rx/internal/operators/OperatorMerge.java, src/test/java/rx/internal/operators/OperatorMergeTest.java
Calling 
```java
request(2);
request(Long.MAX_VALUE-1);
```
hangs ```OperatorMerge``` because the internal requested count overflows and becomes negative. 
This PR adds fix and unit test.
I imagine this will be in other operators as well. I'll have a hunt around.
=> OperatorMerge handle request overflow

src/main/java/rx/Subscriber.java, src/test/java/rx/SubscriberTest.java
As per discussion in #1956 and #2545, making a call to ```Subscriber.request(n)``` with negative n should throw an ```IllegalArgumentException```.
Includes unit test.
=> Subscriber.request should throw exception if negative request made

src/main/java/rx/Subscriber.java, src/test/java/rx/SubscriberTest.java
=> Subscriber.onStart requests should be additive (and check for overflow)

src/main/java/rx/internal/operators/NotificationLite.java, src/main/java/rx/subjects/AsyncSubject.java, src/main/java/rx/subjects/BehaviorSubject.java, src/main/java/rx/subjects/PublishSubject.java, src/main/java/rx/subjects/ReplaySubject.java, src/test/java/rx/internal/operators/NotificationLiteTest.java, src/test/java/rx/internal/operators/OperatorMergeTest.java, src/test/java/rx/subjects/AsyncSubjectTest.java, src/test/java/rx/subjects/BehaviorSubjectTest.java, src/test/java/rx/subjects/PublishSubjectTest.java, src/test/java/rx/subjects/ReplaySubjectBoundedConcurrencyTest.java, src/test/java/rx/subjects/ReplaySubjectConcurrencyTest.java, src/test/java/rx/subjects/ReplaySubjectTest.java
fix.
This PR aims to support the requests in #2331 and #1897 by adding methods to the (final) subject classes that let developers access in-flight state in a snapshot fashion. 
This may be considered safe API change because all subject classes were final already so adding extra methods won't break anyone's code (and we will be careful with our Observable in the future).
- ```NotificationLite``` is now extended with two missing value checks: isNull and isNext.
- Each subject has ```hasCompleted```, ```hasThrowable``` and ```getThrowable``` methods, however, I can't add them to ```Subject``` because that would be an incompatible API change.
- Where applicable, ```getValue``` and ```getThrowable``` return ```null``` instead of throwing exceptions so users are encouraged to call hasXXX …
=> Subject state information methods & bounded ReplaySubject termination

src/main/java/rx/internal/operators/OperatorMerge.java, src/main/java/rx/internal/util/RxRingBuffer.java, src/main/java/rx/internal/util/unsafe/SpscArrayQueue.java
Changed RxRingBuffer to use synchronized blocks for correctness. We are relying here upon biased locking and lock-elision. It gets pretty close to the baseline
Benchmark:
```
Benchmark              (size)        1.x   |    PR#2333  |    this   
1SyncStreamOfN              1  3779678,748 | 3767936,028 | 3775157,195
1SyncStreamOfN           1000    21250,675 |   18530,542 |   20759,900
1SyncStreamOfN        1000000       20,406 |      17,712 |      19,768
NAsyncStreamsOfN            1   115390,116 |  115629,480 |  113859,532
NAsyncStreamsOfN         1000        2,579 |       2,546 |       2,435
NSyncStreamsOf1             1  3543551,254 | 3602242,709 | 3539162,675
NSyncStreamsOf1           100   299166,910 |  301703,721 |  302642,458
NSyncStreamsOf1          1000    28404,751 |   28420,833 …
```
=> RxRingBuffer with synchronization

src/main/java/rx/internal/operators/OperatorMergeMaxConcurrent.java, src/test/java/rx/internal/operators/OperatorMergeMaxConcurrentTest.java
=> Merge with max concurrency now supports backpressure.

src/test/java/rx/BackpressureTests.java, src/test/java/rx/test/TestObstructionDetection.java, src/test/java/rx/test/TestObstructionDetectionTest.java
To make sure tests don't hang the computation scheduler.
=> Obstruction detection in tests.

src/test/java/rx/internal/operators/OperatorRetryTest.java, src/test/java/rx/subjects/ReplaySubjectBoundedConcurrencyTest.java, src/test/java/rx/subjects/ReplaySubjectConcurrencyTest.java
On my Windows machine, I've virtualized an Ubuntu machine and adjusted some tests according to the time it takes on this "slow machine".
=> Give more time to certain concurrency tests.

src/main/java/rx/Producer.java, src/main/java/rx/Subscriber.java, src/main/java/rx/internal/operators/BackpressureUtils.java, src/main/java/rx/internal/operators/OnSubscribeFromIterable.java, src/main/java/rx/internal/operators/OperatorMerge.java, src/test/java/rx/internal/operators/OnSubscribeFromIterableTest.java
A subscriber like so provokes a hang from ```OnSubscribeFromIterable``` due to overflow to negative of requested field:
```java
@Override
public void onStart() {
request(2);
}
@Override
public void onNext(Integer t) {
request(Long.MAX_VALUE-1);
}
```
I've moved the ```getAndAddRequest``` method that does the overflow check to a new ```rx.internal.operators.Util``` class that is also now used by the request overflow check in ```OperatorMerge```.
Of course there are plenty more of these to be done. I propose to do them bit by bit.
=> OnSubscribeFromIterable - add request overflow check 

src/main/java/rx/subjects/ReplaySubject.java, src/test/java/rx/internal/operators/OperatorReplayTest.java
When a replay subject with size and time eviction policy is used then any observer that subscribes after some events are already pushed will not get those older events. 
This is because if an observable is not yet terminated then on subscription by any new observer the check for event validity fails on the Size Eviction policy hence that event is dropped and not pushed to the new subscriber.
Relevant call stack:
{{{
TimeOnAdd.call
BoundedState.replayObserverFromIndexTest
BoundedState.replayObserverFromIndexTest
PairEvictionPolicy.test
}}}
Test Case: 
- add test case for this use case, Fails if without changes.
=> SizeEviction test needs to return false 

src/main/java/rx/internal/util/unsafe/ConcurrentCircularArrayQueue.java, src/main/java/rx/internal/util/unsafe/ConcurrentSequencedCircularArrayQueue.java, src/main/java/rx/internal/util/unsafe/MessagePassingQueue.java, src/main/java/rx/internal/util/unsafe/MpmcArrayQueue.java, src/main/java/rx/internal/util/unsafe/SpmcArrayQueue.java, src/main/java/rx/internal/util/unsafe/SpscArrayQueue.java, src/test/java/rx/internal/util/JCToolsQueueTests.java
=> Updating queue code from JCTools

src/main/java/rx/internal/operators/OperatorSubscribeOn.java, src/test/java/rx/internal/operators/OperatorReplayTest.java
@mattrjacobs noticed that the unsubscribe from timeouts of Hystrix commands was not being propagated across the subscribeOn.
https://github.com/Netflix/Hystrix/issues/354
=> subscribeOn drops the subscriptions returned from the scheduler.

src/main/java/rx/internal/operators/OnSubscribeCombineLatest.java, src/test/java/rx/internal/operators/OnSubscribeCombineLatestTest.java
sometimes.
Discovered in #2560.
=> CombineLatest: fixed concurrent requestUpTo yielding -1 requests

src/main/java/rx/internal/operators/OperatorPublish.java, src/test/java/rx/internal/operators/OperatorPublishTest.java
Reported in a [rxjava group](https://groups.google.com/forum/#!topic/rxjava/iOA_wl-fReI) post.
The shared emissioncounter subtracted from all subscribers accounting made late coming subscribers appear to have received the same amount of events.
=> Publish: fixed incorrect subscriber requested accounting

src/main/java/rx/internal/util/SubscriptionList.java, src/perf/java/rx/subscriptions/CompositeSubscriptionConcurrentPerf.java, src/perf/java/rx/subscriptions/CompositeSubscriptionPerf.java, src/perf/java/rx/subscriptions/MultipleAssignmentSubscriptionPerf.java, src/perf/java/rx/subscriptions/SerialSubscriptionPerf.java, src/perf/java/rx/subscriptions/SubscriptionListConcurrentPerf.java, src/perf/java/rx/subscriptions/SubscriptionListPerf.java
Subscription perf tests with JMH.
```
gradlew benchmarks "-Pjmh=-f 1 -tu s -bm thrpt -wi 10 -i 10 -r 1 rx.subscriptions.*Perf.*"
```
[Perf run](https://gist.github.com/akarnokd/9b493209fc27c858b85a) took 90 minutes on my i7 4770k, JDK 1.8u31, Windows 7 x64.
=> Added perf tests for various container-like subscriptions

src/main/java/rx/Observable.java, src/main/java/rx/internal/operators/OperatorSwitchIfEmpty.java, src/test/java/rx/internal/operators/OperatorSwitchIfEmptyTest.java
=> Operator: switchIfEmpty

src/main/java/rx/Observable.java, src/main/java/rx/internal/operators/OperatorSwitchIfEmpty.java, src/test/java/rx/internal/operators/OperatorSwitchIfEmptyTest.java
Like defaultIfEmpty but subscribes to and emits the items in an Observable if the source is empty.
Fixes #1878
=> Added Operator switchIfEmpty

src/main/java/rx/internal/operators/OperatorOnBackpressureBlock.java, src/main/java/rx/internal/operators/OperatorOnBackpressureBuffer.java, src/main/java/rx/internal/util/BackpressureDrainManager.java, src/test/java/rx/internal/operators/OnBackpressureBlockTest.java, src/test/java/rx/internal/operators/OperatorOnBackpressureBufferTest.java
This is quite a complex operator with lots of cases.
Properties:
1) If there aren't any elements queued up and nothing is requested but terminal event received, emit terminal event and quit.
2) If there are elements in the queue and a terminal flag, and at least the same amount is requested, deliver the events and the terminal event.
3) If more was requested and more became available just after the loop and before the synchronized block, keep looping.
3.a) If more was requested but nothing is available or nothing was requested and something is available: quit and let either the onNext or request do the subsequent drain.
3.b) If elements and termination was produced but not requested: quit and let the request do the drain
3.c) If termination was requested and no elements produced: loop , …
=> OnBackpressureXXX: support for common drain manager & fix for former concurrency bugs

src/main/java/rx/internal/schedulers/NewThreadWorker.java
Changed the parameter naming as per [discussed](https://github.com/ReactiveX/RxJava/pull/2465#discussion_r24035981).
=> Changed the naming of the NewThreadWorker's system parameters

src/main/java/rx/internal/operators/OperatorZip.java, src/test/java/rx/internal/operators/OperatorZipTest.java
Should fix issue reported in #2588.
Ps. What are the odds two bug reports issued so close to each other have the same cause and same fix? @davidmoten the ```BackpressureUtils``` was a fantastic idea.
=> Zip: fixed unbounded downstream requesting above Long.MAX_VALUE

src/main/java/rx/internal/operators/OnSubscribeRedo.java, src/test/java/rx/internal/operators/OperatorRepeatTest.java
=> Repeat/retry: fixed unbounded downstream requesting above Long.MAX_VALUE

src/main/java/rx/internal/operators/OnSubscribeRefCount.java, src/test/java/rx/internal/operators/OnSubscribeRefCountTest.java
This should fix the problem in #2564. @davidmoten I hope you can review the changes and implications.
The particular issue was caused by the refCount unable to unsubscribe from upstream in case the current client count was greater than 1. If the upstream sent an error and each client had a retry() in its chain, the retry would immediately resubscribe, thus the refCount would see only a 2 -> 1 -> 2 change in sequence as errors are dispatched sequentially. In the change, each client is wrapped and a termination event triggers the refcount to become 0 atomically and unsubscribes the upstream. When each client then call disconnect, that becomes a no-op.
=> RefCount: disconnect all if upstream terminates

src/main/java/rx/internal/operators/OperatorZip.java, src/test/java/rx/internal/operators/OperatorZipTest.java
Could also fix #2588 but can't be sure because the test created from the example app works for me.
=> Zip: emit onCompleted without waiting for request + avoid re-reading fields

src/main/java/rx/observers/TestSubscriber.java
Reverts change made at https://github.com/ReactiveX/RxJava/pull/2332/files#diff-fbed6a16f49022fd2b10f45fd6dd015bR230
See discussion at https://github.com/ReactiveX/RxJava/issues/2549#issuecomment-72783738
The Javadoc for this method clearly states that it will wait until completion or timeout. It does not say it will throw an exception on timeout, so we can not start throwing as that is a behavioral change.
=> Revert Behavior Change in TestSubscriber.awaitTerminalEvent

src/main/java/rx/internal/operators/OnSubscribeRefCount.java
As mentioned in #2567, improve the comments
=> OnSubscribeRefCount - improve comments

src/main/java/rx/Observable.java, src/test/java/rx/ObservableTests.java
Empty was always stateless so creating a new instance all the time (especially through a ```from(Iterable)```) is wasteful. Besides, ```onCompleted``` events don't have to be backpressured.
Should enable identity based optimizations discussed in #1653.
=> Changed Observable.empty() into a stateless constant observable.

src/main/java/rx/Observable.java, src/test/java/rx/ObservableTests.java
=> Cast back Observer to Subscriber if passed to subscribe(Observer)

src/main/java/rx/Scheduler.java
There is a potential memory leak in `schedulePeriodically` that may keep a reference to `action` after `unsubscribe`. 
Because `mas.set` is called after `schedule`,  it may replace a new Subscription (created in `recursiveAction`) with the old one. Therefore, `unsubscribe` won't be able to unsubscribe the new Subscription and will keep the reference to `action` until the period time elapses.
This PR fixed it by calling `mas.set` before `schedule`.
=> Fix a potential memory leak in schedulePeriodically

src/main/java/rx/internal/util/unsafe/UnsafeAccess.java
Missing Unsafe class yields NoClassDefFoundError so checking for Exception is not really appropriate. Let's catch all throwables.
=> Missing Unsafe class yields NoClassDefFoundError

src/main/java/rx/schedulers/EventLoopsScheduler.java
This change allows limiting the number of computation threads to 1 .. availableProcessors.
=> Allow configuring the maximum number of computation scheduler threads

src/main/java/rx/exceptions/Exceptions.java, src/main/java/rx/internal/operators/OperatorPublish.java, src/main/java/rx/internal/util/SubscriptionList.java, src/main/java/rx/internal/util/SubscriptionRandomList.java, src/main/java/rx/subjects/AsyncSubject.java, src/main/java/rx/subjects/BehaviorSubject.java, src/main/java/rx/subjects/PublishSubject.java, src/main/java/rx/subjects/ReplaySubject.java, src/main/java/rx/subscriptions/CompositeSubscription.java
Tried to be as flexible with the error text as possible.
=> Added common Exceptions.throwIfAny to throw a collection of exceptions

src/main/java/rx/Subscriber.java, src/main/java/rx/internal/operators/OperatorTakeWhile.java, src/test/java/rx/internal/operators/OperatorTakeWhileTest.java
Fixes #2647 issue with TakeWhile.
=> TakeWhile: don't unsubscribe downstream.

src/main/java/rx/Observable.java, src/test/java/rx/internal/operators/OperatorFlatMapTest.java
For issue #2626.
There is no point in adding maxConcurrent to flatMapIterable because each iterable is subscribed to sequentially and run to completion.
=> FlatMap overloads with maximum concurrency parameter

src/main/java/rx/internal/operators/OperatorMerge.java, src/main/java/rx/internal/operators/OperatorSwitch.java, src/test/java/rx/internal/operators/OperatorSwitchTest.java
Fix for issue #2654.
By calling the ```super(child)``` in SwitchSubscriber's constructor, the upstream's merge producer overwrote the producer placed by the SwitchOnNext operator thus any downstream request went into the upstream an not into the currently active observable.
=> SwitchOnNext: fix upstream producer replacing the ops own producer

src/main/java/rx/Observable.java, src/main/java/rx/internal/operators/OnSubscribeUsing.java, src/test/java/rx/internal/operators/OnSubscribeUsingTest.java
See #2604 where it was discovered that ```Observable.using``` used ```subscribe``` instead of ```unsafeSubscribe``` which provoked a race condition leading to an IllegalArgumentException from the merge operator.
This PR uses ```unsafeSubscribe``` and adds an overload for ```using``` to optionally dispose of resources eagerly (just before completion or error). The use case for this is a *synchronous* observable where a downstream operation wants to reuse a resource (but because the observable is synchronous the resource cannot get disposed till the downstream completes).
Unit tests included.
=> Observable.using should use unsafeSubscribe and enable eager disposal

src/main/java/rx/internal/util/SubscriptionList.java, src/main/java/rx/subscriptions/CompositeSubscription.java
Extracted isUnsubscribed optimization from #2603.
```
Benchmark                                   (size)   Mode   Samples          1.x        2603    
r.s.ComputationSchedulerPerf.observeOn           1  thrpt         5   104110.926  104707.286
r.s.ComputationSchedulerPerf.observeOn          10  thrpt         5   100723.402  105825.148
r.s.ComputationSchedulerPerf.observeOn         100  thrpt         5    24609.763   65571.461
r.s.ComputationSchedulerPerf.observeOn        1000  thrpt         5     3212.434   13020.027
r.s.ComputationSchedulerPerf.observeOn       10000  thrpt         5      955.002    1555.493  
r.s.ComputationSchedulerPerf.observeOn      100000  thrpt         5       96.628     160.218  
r.s.ComputationSchedulerPerf.observeOn     1000000  thrpt         5        9.508 …
```
=> Optimized isUnsubscribed check

src/main/java/rx/Observable.java, src/main/java/rx/internal/operators/OperatorWithLatestFrom.java, src/main/java/rx/observers/SerializedSubscriber.java, src/test/java/rx/internal/operators/OperatorWithLatestFromTest.java
Named after RxJS, for issue #405
=> Operator: WithLatestFrom

src/main/java/rx/internal/operators/OnSubscribeCombineLatest.java, src/test/java/rx/internal/operators/OnSubscribeCombineLatestTest.java
Use ```BackpressureUtils.getAndAddRequest(requested, n)``` instead of  ```requested.getAndAdd(n)``` so that an overflow check takes place.
=> OperatorCombineLatest request overflow check

src/main/java/rx/internal/operators/OperatorOnBackpressureDrop.java, src/test/java/rx/internal/operators/OperatorOnBackpressureDropTest.java
Use ```BackpressureUtils.getAndAddRequest(requested, n)``` instead of ```requested.getAndAdd(n)``` so that an overflow check takes place. Includes a unit test that failed on original code (but passes with this PR).
=> OperatorOnBackpressureDrop request overflow check

src/main/java/rx/internal/operators/OnSubscribeRange.java, src/test/java/rx/internal/operators/OnSubscribeRangeTest.java
One more:
Use ```BackpressureUtils.getAndAddRequest(requested, n)``` instead of ```requested.getAndAdd(n)``` so that an overflow check takes place. Includes a unit test that failed on original code (but passes with this PR).
=> OnSubscribeRange request overflow check

src/main/java/rx/Observable.java, src/main/java/rx/internal/schedulers/EventLoopsScheduler.java, src/main/java/rx/internal/util/ScalarSynchronousObservable.java, src/main/java/rx/schedulers/Schedulers.java
Redone #2603.
Run on i7 920, 2.6GHz, Windows 7 x64, JDK 1.8u31
```
Benchmark      (size)       this   Score error       1.x   Score error
observeOn           1  160377,408     3091,205  140913,081     7097,415
observeOn          10  132990,049     1477,661  125288,149    14304,259
observeOn         100   43701,203     2342,570   43840,921      944,682
observeOn        1000   11603,952     2377,205   11400,340     1400,628
observeOn        2000    6769,716      220,476    6853,283       71,276
observeOn        3000    4753,876      326,497    4741,108      120,612
observeOn        4000    3616,782      212,285    3632,433      433,754
observeOn       10000    1544,141       28,796    1548,504       61,419
observeOn      100000     149,573       14,974     150,924        8,331
observeOn …
```
=> Optimized scalar observeOn/subscribeOn

src/main/java/rx/internal/operators/OperatorMulticast.java, src/test/java/rx/internal/operators/OperatorMulticastTest.java
See discussion in  #2774 
Changes include 
* fix for #2774 just for ```OperatorMulticast``` (will do ```OperatorPublish``` in another PR once have sorted this one out)
* made fields private that had default visibility
* renamed ```OnSubscribeMulticastTest``` to ```OperatorMulticastTest```
* addressed a possible race condition that could provoke an IAE when ```Observable.subscribe(sub)``` is called with sub=null (unsubscription occurs between L144 and L145 on old code).
=> OperatorMulticast.connect(connection) should not return null

src/main/java/rx/internal/operators/OperatorPublish.java, src/test/java/rx/internal/operators/OperatorPublishTest.java
=> Fix the bug that 'publish' will cache items when no subscriber

src/main/java/rx/internal/operators/OperatorObserveOn.java, src/main/java/rx/internal/schedulers/EventLoopsScheduler.java, src/main/java/rx/internal/schedulers/NewThreadWorker.java, src/main/java/rx/internal/schedulers/ScheduledAction.java, src/main/java/rx/internal/util/SubscriptionList.java, src/test/java/rx/internal/operators/OperatorConcatTest.java, src/test/java/rx/internal/operators/OperatorReplayTest.java
Squashed commits of #2773.
---------------
Further optimizations to ```observeOn```.
- Using SpscArrayQueue directly in observeOn instead of ```RingBuffer``` to avoid the synchronization block
- Split tracking structure to serial (SubscriptionList) and timed (CompositeSubscription) in ```EventLoopsScheduler``` which improves the sequential scheduling performance because a completing task's subscription will be most likely the first item in the underlying LinkedList.
Benchmark: (i7 920, Window 7 x64, Java 1.8u31, 5x1s warmup, 5x5s iteration)
```
Benchmark      (size)         1.x    1.x error      this PR   this error
observeOn           1  162326,012     2458,085   166536,559     3154,174
observeOn          10  132471,205     1857,434   142517,407     3734,424 ++
observeOn         100 …
```
=> ObserveOn throughput enhancements

src/main/java/rx/internal/operators/OperatorTakeUntil.java, src/test/java/rx/internal/operators/OperatorTakeUntilTest.java
of a terminal condition.
This issue came up in [a group discussion](https://groups.google.com/forum/#!topic/rxjava/sF2hy5sV5ck) (but is unrelated to the actual problem there). The problem was that takeUntil was unsafeSubscribed to, there was no one to terminate either the main or the other observable on a terminal condition, leaving the connection to upstream active indefinitely.
=> Fixed takeUntil not unsubscribing from either of the observables in case

src/test/java/rx/BackpressureTests.java
It is possible the synchronized block inside RxRingBuffer blocks out the firehose thread long enough that there will be enough requests cumulating up and no values have to be dropped. The change increases the taken value count and should decrease the likelihood of such no-drop situation.
=> Fix for non-deterministic: testOnBackpressureDropWithAction

src/main/java/rx/Observable.java, src/main/java/rx/Observer.java, src/main/java/rx/Producer.java, src/main/java/rx/Subscription.java, src/main/java/rx/functions/Action0.java, src/main/java/rx/functions/Action1.java, src/main/java/rx/functions/Action2.java, src/main/java/rx/functions/Action3.java, src/main/java/rx/functions/Func0.java, src/main/java/rx/functions/Func1.java, src/main/java/rx/functions/Func2.java, src/main/java/rx/functions/Func3.java, src/main/java/rx/functions/Func4.java, src/main/java/rx/functions/Func5.java, src/main/java/rx/functions/Func6.java, src/main/java/rx/functions/Func7.java, src/main/java/rx/functions/Func8.java, src/main/java/rx/functions/Func9.java, src/main/java/rx/functions/FuncN.java, src/main/java/rx/internal/operators/OperatorTimeoutBase.java, src/test/java/rx/internal/operators/OnSubscribeUsingTest.java
Just little Java syntax fix for interfaces
I checked all interfaces in RxJava.
@benjchristensen I can add and configure `Checkstyle` gradle plugin for RxJava if you don't mind, mm?
=> Corrected all Java interfaces declarations

src/main/java/rx/exceptions/OnErrorThrowable.java, src/main/java/rx/plugins/RxJavaErrorHandler.java, src/test/java/rx/plugins/RxJavaPluginsTest.java
as discussed in #2468, allow implementations of RxJavaErrorHandler to define a rendering behavior for safe and known types to be rendered in the stacktrace of OnNextValue.
=> Implement hook to render specific types in OnNextValue

src/test/java/rx/BackpressureTests.java
Not for merge. Diagnosing travis build failure.
=> testOnBackpressureDropWithAction restored original test count

src/main/java/rx/Observable.java
Removed wrong link inside of JavaDoc for Observable.repeat() method
=> Fixed javadoc for Observable.repeat() method

src/main/java/rx/internal/operators/OperatorDebounceWithTime.java, src/test/java/rx/internal/operators/OperatorDebounceTest.java
Fixed #2850.
The issue is because OperatorDebounceWithTime will swallow values but not request more items. Just add `request(Long.MAX_VALUE)` since it doesn't support backpressure.
=> Add 'request(Long.MAX_VALUE)' in 'onStart' to fix the backpressure issue of debounce

src/main/java/rx/internal/operators/OnSubscribeRedo.java, src/main/java/rx/internal/operators/OperatorRetryWithPredicate.java, src/test/java/rx/internal/operators/OperatorRetryWithPredicateTest.java
Fixes both issue #2826 and [this StackOverflow](http://stackoverflow.com/questions/29324886/retrywhen-operator-never-retries) problem.
=> Change retryWhen to eagerly ignore an error'd source's subsequent events

src/main/java/rx/internal/operators/OperatorDoOnRequest.java, src/test/java/rx/internal/operators/OperatorDoOnRequestTest.java
When ```Observable.doOnRequest``` is used it does not pass unsubscription upstream. This PR fixes that and also adds a unit test of the base functionality for ```doOnRequest``` (no unit tests were present for this operator at all).
=> OperatorDoOnRequest should unsubscribe from upstream

src/main/java/rx/internal/operators/BackpressureUtils.java, src/main/java/rx/observables/AbstractOnSubscribe.java, src/test/java/rx/observables/AbstractOnSubscribeTest.java
=> Fixes wrong request accounting in AbstractOnSubscribe

src/main/java/rx/internal/operators/OperatorSingle.java, src/test/java/rx/internal/operators/OperatorSingleTest.java
I noticed that ```observable.single().subscribe()``` requested ```Long.MAX_VALUE``` from ```observable``` which is more than it needs to come up with one item or an error. This PR sets a ```Producer``` for ```OperatorSingle``` so that it requests no more or less than it needs.
=> OperatorSingle should request exactly what it needs

src/test/java/rx/internal/operators/OperatorZipTest.java
The test ```OperatorZipTest.testZipRace``` fails every time on my pretty fast desktop due to not achieving the desired number of iterations within the timeout. It also fails every time on my slow laptop. This PR adds a time limit for the iterations of one second less than the test timeout so that the test will fail if a zip hangs but not if the machine is slow.
=> Ensure OperatorZipTest.testZipRace does not fail on slower machines

src/main/java/rx/internal/util/IndexedRingBuffer.java, src/main/java/rx/internal/util/SubscriptionIndexedRingBuffer.java, src/perf/java/rx/internal/IndexedRingBufferPerf.java, src/test/java/rx/internal/util/IndexedRingBufferTest.java
Added type to IndexedRingBuffer.POOL (to get rid of raw types warning) and changed signature of ```IndexedRingBuffer.getInstance``` so that it infers type. Means that 13 ```unchecked``` warnings in the code base can be removed.
=> IndexedRingBuffer.getInstance can infer type

src/test/java/rx/CovarianceTest.java, src/test/java/rx/ObservableTests.java, src/test/java/rx/internal/operators/OnSubscribeToObservableFutureTest.java, src/test/java/rx/internal/operators/OperatorConcatTest.java, src/test/java/rx/internal/operators/OperatorDoOnEachTest.java, src/test/java/rx/internal/operators/OperatorMulticastTest.java, src/test/java/rx/internal/operators/OperatorOnErrorResumeNextViaObservableTest.java, src/test/java/rx/internal/operators/OperatorPublishTest.java, src/test/java/rx/internal/operators/OperatorReplayTest.java, src/test/java/rx/internal/operators/OperatorSampleTest.java, src/test/java/rx/internal/operators/OperatorScanTest.java, src/test/java/rx/internal/operators/OperatorSkipWhileTest.java, src/test/java/rx/internal/util/IndexedRingBufferTest.java
Made changes to test source to avoid or suppress these warnings:
* raw types 
* unused imports
* unused variables
=> Cleanup warnings in test source

src/main/java/rx/internal/util/SubscriptionIndexedRingBuffer.java, src/main/java/rx/internal/util/SubscriptionRandomList.java, src/main/java/rx/plugins/RxJavaErrorHandler.java
* removed unused constructors that were the subject of varargs warnings
* removed unused import
I think that cleans up all java source warnings (not including javadoc issues).
=> More warnings cleanup

src/main/java/rx/functions/Action1.java, src/main/java/rx/functions/Func1.java
Use simpler naming in ```Action1```, ```Func1``` because is used as a default for IDEs when generating implementing methods. For instance,  in Eclipse when auto-generating the implementing methods for an ```Action1``` I get by default:
```java
new Action1<Integer>() {
@Override
public void call(Integer t1) {
//TODO auto-generated
}
}
```
I can't count the number of times I've removed the trailing 1 from the parameter before continuing and I'd appreciate not having to do it! (unfortunately I can't use Java 8 lambdas in all my code).
I'd also be open to a name other than ```t``` like ```value``` but would be happy just to see the 1 go.
=> Use simpler naming in Action1, Func1 to assist IDEs

src/main/java/rx/internal/operators/OperatorConcat.java
=> Fix: NPE in requestFromChild method.

src/main/java/rx/internal/operators/OperatorScan.java
=> OperatorScan - don't call onNext after onError is called

src/main/java/rx/internal/operators/OnSubscribeRange.java
In `RangeProducer` if the first two requests come concurrently and are both for `Long.MAX_VALUE` then there is a possible race condition where the fast path is started twice thus emitting some or all elements twice.
This PR fixes the race by only allowing the fast path if the current request count is 0 (using ```compareAndSet```).
=> Fix Observable.range race condition

src/main/java/rx/internal/operators/OnSubscribeFromIterable.java
In `IterableProducer` if the first two requests come concurrently and are both for `Long.MAX_VALUE` then there is a possible race condition where the fast path is started twice thus emitting some or all elements twice.
This PR fixes the race by only allowing the fast path if the current request count is 0 (using ```compareAndSet```).
=> Fix Observable.from(Iterable) race condition

src/test/java/rx/internal/operators/OnSubscribeRangeTest.java
As per discussion in #2884, it turns out that `range` does emit `onComplete` even when zero is requested because `Observable.range` does not use `OperatorRange` when the count is zero but rather returns an `Observable.empty()`. This PR adds a unit test confirming this fact.
=> Observable.range - add unit test for eager completion on empty

src/main/java/rx/internal/operators/OnSubscribeFromIterable.java, src/test/java/rx/internal/operators/OnSubscribeFromIterableTest.java
As per discussion in #2884, `Observable.from(iterable)` is preferred to emit `onCompleted` when `iterable` is empty even when nothing has been requested.
This PR adds a check on `iterator.hasNext` before the `Producer` is assigned and emits `onCompleted` immediately if `hasNext` returns false.
Includes unit test that failed on existing code base.
=> Observable.from(empty) to emit onComplete even when 0 requested

src/main/java/rx/internal/operators/OperatorConcat.java, src/test/java/rx/internal/operators/OperatorConcatTest.java
=> Concat: fixed reentrancy problem in completeInner

src/main/java/rx/Observable.java
Every call to Observable.count() and countLong() instantiated a new Func2 which I have now made a singleton in the interests of minimizing GC pressure. 
Can anyone in the know confirm for me that there is GC benefit from this one because I assume a sophisticated enough compiler could replace the new Func2 call with a singleton during its optimizations.
If this one is worthwhile then there are heaps more of these in ```Observable.java``` and possibly elsewhere.
=> Use singleton reduction functions in count and countLong

src/test/java/rx/exceptions/ExceptionsTest.java
On my i5 laptop `ExceptionsTest.testStackOverflowIsThrow` hangs. This PR changes the test so that it confirms that significant stack depth occurs and in another test ensures that the fatal `StackOverflowError` is thrown by `subscribe` when it occurs in `onNext`.
I also removed some unused code from the original test and some extra subscriptions that didn't seem to serve a particular function.
=> Prevent ExceptionsTest from hanging when testing stack overflow

src/main/java/rx/internal/operators/OperatorWindowWithObservable.java, src/test/java/rx/internal/operators/OperatorWindowWithObservableTest.java
Source was emitting t multiple times while holding queue.
Fixes #2896
=> Fix for overlapping windows. 

src/main/java/rx/internal/operators/TakeLastQueueProducer.java, src/test/java/rx/internal/operators/OperatorTakeLastTest.java
Added request overflow check to `TakeLastQueueProducer` and associated unit test (that failed on existing code base).
=> TakeLast - add request overflow check

src/main/java/rx/Observable.java, src/main/java/rx/internal/operators/OperatorDistinct.java, src/main/java/rx/internal/operators/OperatorDistinctUntilChanged.java, src/main/java/rx/internal/operators/OperatorOnBackpressureBuffer.java, src/main/java/rx/internal/operators/OperatorSingle.java
To reduce GC pressure use singleton `Operator`s for `Observable.single`, `distinct`, `distinctUntilChanged`,  `onBackpressureBuffer`,  `isEmpty`.
=> Use singleton Operators where we can

src/test/java/rx/internal/util/RxRingBufferWithoutUnsafeTest.java
Reported in #2908. The bug is on line [113](https://github.com/ReactiveX/RxJava/blob/5ac4448873c09cd806ae73a37727a299cbaee2ba/src/test/java/rx/internal/util/RxRingBufferWithoutUnsafeTest.java#L113). If the drainer is delayed after a poll returning null and the emitter producing & terminating before the getCount(), the queue is non empty but the drainer quits and hence the value difference. It comes up almost always if you put a sleep before L113.
=> Fix the drainer to check if the queue is empty before quitting.

src/perf/java/rx/operators/OperatorPublishPerf.java
Benchmarks the behavior of ```publish()``` in face of number of child subscribers, batching effect in request(), length of the source and whether or not each child observes values on a separate thread.
[Benchmark results](https://gist.github.com/akarnokd/cccc31312125d8636d3d)
Remarks:
- With no subscribers, the operator seems to fill its queue and then do nothing unless someone subscribes. There is no test to check for this behavior so it might be a bug or a feature.
- In async mode, the benchmark threw ```MissingBackpressureException``` a lot of times which can happen with a single subscriber as well, so it might be some concurrency bug in the operator.
=> OperatorPublish benchmark

src/main/java/rx/Observable.java, src/main/java/rx/internal/operators/OperatorTakeLastOne.java, src/perf/java/rx/operators/OperatorTakeLastOnePerf.java, src/test/java/rx/internal/operators/OperatorTakeLastOneTest.java
This is an optimization for `takeLast` when called with parameter 1. Using `OperatorTakeLast` carries unnecessary overhead for the `takeLast(1)` case and a decent throughput improvement (x2) for streams of 100 elements or more is seen in the benchmarks below.
`takeLast(1)` is used by the following operators which will also demonstrate a throughput improvement:
* `last`, `lastOrDefault`
* `reduce`
* `collect`
* `count`, `countLong`
Benchmarks comparing using the new `OperatorTakeLastOne` and `OperatorTakeLast`:
```
Benchmark                                                        Mode   Samples        Score  Score error    Units
r.o.OperatorTakeLastOnePerf.takeLastOneUsingTakeLastOne_Few     thrpt         5  2235516.141   129091.019    ops/s …
```
=> Optimization - use OperatorTakeLastOne for takeLast(1)

src/main/java/rx/Observable.java, src/main/java/rx/internal/operators/OperatorIgnoreElements.java, src/test/java/rx/internal/operators/OperatorIgnoreElementsTest.java, src/test/java/rx/internal/operators/OperatorTakeLastOneTest.java
As suggested by @akarnokd, instead of `filter(alwaysFalse)` use a custom operator and a singleton instance of it.
Also snuck in the removal of an unused import from `OperatorTakeLastOneTest.java`.
=> Observable.ignoreElements - optimize 

src/main/java/rx/subjects/AsyncSubject.java, src/main/java/rx/subjects/BehaviorSubject.java, src/main/java/rx/subjects/PublishSubject.java, src/main/java/rx/subjects/ReplaySubject.java, src/main/java/rx/subjects/SerializedSubject.java, src/main/java/rx/subjects/Subject.java, src/test/java/rx/subjects/SerializedSubjectTest.java
This PR modifies the ```Subject``` class to host the union of the state-peeking methods of the various ```Subject``` implementations and fixes the inconsistent behavior of ```ReplaySubject.getValues(T[])```.
The changes enable the ```SerializedSubject``` to relay such state-peeking method calls into the wrapped subject and allows future ```Subject``` wrappers to do the same (#2458).
=> Proposal: standardized Subject state-peeking methods.

src/main/java/rx/Observable.java, src/main/java/rx/internal/operators/OperatorToObservableList.java, src/main/java/rx/internal/operators/OperatorToObservableSortedList.java, src/main/java/rx/internal/operators/SingleDelayedProducer.java, src/test/java/rx/internal/operators/OperatorToObservableListTest.java, src/test/java/rx/internal/operators/OperatorToObservableSortedListTest.java
Added support for backpressure in ```toList``` and ```toSortedList```: they emit their buffered content only when downstream actually requested it.
Few other notes:
- Added overload to ```toSortedList``` taking a ```initialCapacity``` argument which should help reduce the number of times the buffer needs to be resized.
- The Func2 parameter of ```toSortedList``` is now wrapped once per operator instead of once per subscriber.
- Using non-final list buffers which are set to null on completion to not hold onto the buffer.
- ```toSortedList```now returns a modifiable ```ArrayList```: since it is a handoff procedure, there is no value in forcing a non-modification constraint on the emitted list (similar to ```toList``` even before this PR).
=> Operators toList and toSortedList now support backpressure

src/main/java/rx/internal/operators/OperatorObserveOn.java, src/test/java/rx/internal/operators/OperatorObserveOnTest.java
Use `BackpressureUtils.getAndAddRequest` in the `Producer` in `OperatorObserveOn`.
Includes unit test that failed on codebase before this change.
=> OperatorObserveOn - handle request overflow correctly

src/main/java/rx/internal/operators/OperatorPublish.java, src/perf/java/rx/operators/OperatorPublishPerf.java, src/test/java/rx/internal/operators/OperatorPublishTest.java
Complete rewrite of ```publish()``` and fixed bugs of #2810 and #2803.
=> Operator Publish full rewrite

src/main/java/rx/Observable.java, src/main/java/rx/internal/operators/OperatorWindowWithSize.java, src/test/java/rx/internal/operators/OperatorWindowWithSizeTest.java
Changes to the ```window(size)``` operator to respect the backpressure on its *outer* Observable: asking for 1 window will request ```size``` values from upstream. 
Backpressure is ignored on the inner Observable for now, partially because the ```BufferUntilSubscriber``` doesn't support it, partially because coordinating the inner requests with the outer requests needs more thoughts. The problem is that the outer has to request at least 1 element from upstream in order to open the window, but the inner subscriber may not want that single element just yet or would request more than the remaining window size and it would trigger new windows whose value it can't receive but would overflow the next window's observers.
```window(size, skip)``` is not changed as I need to think about it more.
=> Backpressure for window(size)

src/main/java/rx/internal/schedulers/EventLoopsScheduler.java, src/main/java/rx/internal/util/SubscriptionList.java
SubscriptionList.add() and thread unparking.
This PR partially reverts some changes from earlier scheduler optimizations and fixes a case where if multiple concurrent schedule() calls happen, the order in the SubscriptionList might be different from the actual execution order which degrades performance on task termination due to remove() being O(n).
This might be the source of degradation in #2857 as well.
I'll post the ```ComputationSchedulerPerf``` results later.
=> Fix the performance degradation due to different schedule execution and

src/main/java/rx/subjects/TestSubject.java, src/test/java/rx/subjects/TestSubjectTest.java
Problem is in TestSubject.onNext()
when is called on current time that is not 0 it will be delayed by current time.
calling TestSubject.onNext() should execute immediately.
* TestSubjectTest.testObserverPropagateValueAfterTriggeringActions - represent already working behavior
* TestSubjectTest.testObserverPropagateValueInFutureTimeAfterTriggeringActions - represent a bug that is fixed by this commit
=> Fix TestSubject bug

src/main/java/rx/internal/operators/OnSubscribeCombineLatest.java
RxRingBuffer size is not a constant and on Android is
less then 128 (16). So it causing silent issues when
there were given 16 < Observers < 128.
=> Fixed Observable.combineLatest overflow bug on Android

src/main/java/rx/internal/operators/OperatorPublish.java
Yet another fix to the race condition in publish().
=> publish: Fix another race between terminalEvent and the queue being empty.

src/main/java/rx/internal/operators/OperatorDebounceWithTime.java
Due to !hasValue check (line 120), localHasValue field is always true
=> Remove unnecessary localHasValue check

build.gradle
This is one thing I've missed for a while so I figured out how to get gradle to provide them. This PR enables production of Jacoco coverage reports and Findbugs reports as html in the build directory. It doesn't happen by default, the plugins are run like this (instructions in comments in `build.gradle`):
To run Findbugs:
```./gradlew check```
To run Jacoco test coverage:
```./gradlew test jacocoTestReport```
To run Jacoco on a single test:
```./gradlew -Dtest.single=OperatorRetry test jacocoTestReport```
Then open up the reports in `build/reports`.
=> Add code quality plugins to build.gradle (jacoco, findbugs)

src/main/java/rx/internal/operators/OperatorObserveOn.java, src/perf/java/rx/operators/OperatorObserveOnPerf.java
This is a fix for a race condition in `OperatorObserveOn` where if thread A gets to L164 and thread B starts the pollQueue loop then it will act as if the stream had completed normally instead of with an error. 
The effect is that a stream could appear to complete normally when in fact an error had occurred.
Using two boolean volatiles `completed` and `failed` that as a pair were not atomically updated/read exposed us to this race condition. 
The fix is to use a single volatile integer `status` to represent the  states ACTIVE, COMPLETED, ERRORED to replace `completed` and `failed`.
=> OperatorObserveOn onComplete can be emitted despite onError being called

src/main/java/rx/schedulers/ExecutorScheduler.java, src/test/java/rx/schedulers/ExecutorSchedulerTest.java
Fixes a race condition with the timed schedule (first potentially overwriting the result of the untimed schedule in mas) and a scheduled task retention problem due to not tracking those.
=> Fixed schedule race and task retention with ExecutorScheduler.

build.gradle
When a release is created the tagged version should build deterministically at any time. The wildcard dependency on ```gradle-rxjava-project-plugin``` in ```build.gradle``` means this will not be the case. This PR sets the version at 2.2.3 (the latest on Maven Central).
=> Use explicit versioning for gradle-rxjava-project-plugin

src/main/java/rx/Observable.java, src/main/java/rx/internal/operators/OperatorOnBackpressureLatest.java, src/test/java/rx/internal/operators/OperatorOnBackpressureLatestTest.java
This is essentially the pair of the ```OnBackpressureDrop```. While ```OnBackpressureDrop``` emits the first value requested and then drops the rest, ```OnBackpressureLatest``` drops values but the latest and emits that when requested. One can also think of this operator as a sample with backpressure.
One mentionable property is that since it holds onto the very last value, downstream has to request at least one to receive ```onCompleted()```.
=> OnBackpressureLatest: Non-blocking version of the toBlocking().latest() operator.

build.gradle
Apologies for the PR that added these to build.gradle. My claim that they were not run by default was wrong (`./gradlew build` runs them). Let's remove till I figure out how to do this properly.
=> Remove findbugs+jacoco from build.gradle

src/main/java/rx/internal/operators/OperatorGroupBy.java, src/test/java/rx/internal/operators/OperatorGroupByTest.java
Added request overflow check to `OperatorGroupBy` (using `BackpressureUtils`) and prevented `requested` counters from being decremented if they were at `Long.MAX_VALUE`.
Includes unit test that failed on current codebase.
=> OperatorGroupBy - check for request overflow and don't decrement when at Long.MAX_VALUE

src/main/java/rx/internal/operators/OperatorConcat.java, src/test/java/rx/internal/operators/OperatorConcatTest.java
Used `BackpressureUtils` to prevent request overflow and added an `n > 0` check for requests to ensure that `subscribeNext` is not called concurrently (race condition).
No unit tests written. Let me know if you think worth the effort.
=> OperatorConcat - prevent request overflow and fix race condition

src/main/java/rx/internal/operators/OperatorObserveOn.java, src/test/java/rx/internal/operators/OperatorObserveOnTest.java
In existing code if unsubscription happens immediately after a `child.onNext` call from `pollQueue` then the number of emissions made in the loop will be requested of upstream despite `child` being unsubscribed.
This PR adds a local variable `isUnsubscribed` and when set to true no further requests will be made.
This PR includes a unit test that failed on the existing codebase.
=> OperatorObserveOn should not request more after child is unsubscribed

src/main/java/rx/observers/TestSubscriber.java
Additional asserts for TestSubscriber and the option to specify the initial request via a constructor.
=> More assertions for TestSubscriber

src/main/java/rx/internal/operators/OnSubscribeAmb.java, src/test/java/rx/internal/operators/OnSubscribeAmbTest.java
The Amb operator has a backpressure bug:
* if `m` requests were made before the first emission then `m` subscriptions were started on each source observable. We only want once subscription on each.
This PR adds fix code to  `OnSubscribeAmb` and two unit tests.
=> fix Amb backpressure bug

src/main/java/rx/internal/operators/OperatorConcat.java, src/main/java/rx/internal/producers/ProducerArbiter.java, src/test/java/rx/internal/operators/OperatorConcatTest.java
If a request arrives while `ConcatInnerSubscriber` is being constructed ([L199-201](https://github.com/ReactiveX/RxJava/blob/bad4d40a7b59cb443c3cb19d00ab80000e017a5f/src/main/java/rx/internal/operators/OperatorConcat.java#L199-L201)) then that additional request does not induce a request from the subscriber and could stall the stream. The fix is not to pass `requested` value in the constructor but to call `ConcatInnerSubscriber.requestMore` with `requested` only once `currentSubscriber` is set.
=> fix OperatorConcat race condition where request lost

src/test/java/rx/internal/operators/OperatorSerializeTest.java
to address #2870, have made it much more improbable that the error emission is the last thread to complete by only failing the test if the error emission is the last for `n` repeats. I chose `n` = 3 to keep the runtime low (average <2s).
=> improve OperatorSerializeTest.testMultiThreadedWithNPEinMiddle 

src/main/java/rx/internal/operators/OperatorAll.java, src/test/java/rx/internal/operators/OperatorAllTest.java
Implemented backpressure using `SingleDelayedProducer` (thanks @akarnokd) and while I was there ensured that the last value is in the exception cause when the predicate throws an exception.
=> OperatorAll  - implement backpressure and include last value in exception cause

src/main/java/rx/internal/operators/OperatorSkip.java, src/test/java/rx/internal/operators/OperatorSkipTest.java
`OperatorSkip` suffered from this race condition:
Suppose we wanted to skip 5 elements, then
* two concurrent requests of say 1 between onStart request of 0 and first emission would request 1+ (5-0) and 1 + (5-0) elements = 12 elements. To deliver the two requested we only need 7 from upstream so we have overrequested.
It also lacked protection from request overflow.
Two unit tests have been added that failed on previous code and now pass.
=> fix skip() race condition and request overflow

src/main/java/rx/internal/operators/OperatorAny.java, src/test/java/rx/internal/operators/OperatorAnyTest.java
Implemented backpressure using `SingleDelayedProducer`  and while I was there ensured that the last value is in the exception cause when the predicate throws an exception.
=> Operator exists() - implement backpressure and include last value in exception cause

src/main/java/rx/internal/operators/OperatorTake.java, src/test/java/rx/internal/operators/OperatorTakeTest.java
The `request` method used logic that could overrequest upstream if multiple small requests were made before the next item arrived.
Added a unit test that failed on previous code.
=> prevent take() from requesting more than needed

src/main/java/rx/internal/operators/OperatorTakeUntilPredicate.java, src/test/java/rx/internal/operators/OperatorTakeUntilPredicateTest.java
As per title, unit test included.
=> takeUntil(predicate) - include last value in error cause

src/main/java/rx/exceptions/OnErrorThrowable.java, src/test/java/rx/exceptions/OnNextValueTest.java
When an error occurs some `Operator`s (like `map`) include the value in the exception cause to help debugging. The intent is that for the 9 primitive types (int/Integer, double/Double, byte/Byte, char/Character etc) we render the value using `value.toString` but the test for being a primitive does not work because `.isPrimitive` always returns false (primitives have always been autoboxed by the time they get here).
The fix is to create a lazy loaded singleton set of the primitive classes (Integer.class, Double.class, etc) and check for membership in that set.
Unit tests included for each primitive type.
=> Fix value rendering in error last cause for primitive types

src/main/java/rx/internal/operators/OperatorTakeWhile.java, src/test/java/rx/internal/operators/OperatorTakeWhileTest.java
As per title, unit test included.
=> takeWhile(predicate) - include last value in error cause

src/main/java/rx/internal/operators/OperatorSwitchIfEmpty.java, src/test/java/rx/internal/operators/OperatorSwitchIfEmptyTest.java
`OperatorSwitchIfEmpty` suffered from these conditions:
* Backpressure was not enabled for the source observable (as opposed to the altenate) because `setProducer` called `super.setProducer` instead of `child.setProducer`
* Requests could be lost
Bot the of the above problems are solved by using `ProducerArbiter` from @akarnokd.
Included two unit tests that failed on previous code.
=> switchIfEmpty - fix backpressure bug and lost requests

src/main/java/rx/observers/TestSubscriber.java, src/main/java/rx/subjects/ReplaySubject.java
`AssertionError(message, cause)` is a Java 7 API. This PR uses RuntimeException to replace it, just like `assertNoErrors`.
=> Replace the Java 7 AssertionError(message, cause) with RuntimeException

src/main/java/rx/internal/operators/OperatorDelayWithSelector.java, src/main/java/rx/internal/operators/OperatorMulticast.java
minor simplification in `OperatorDelayWithSelector` and `OperatorMulticast`
=> use Subscribers.from()

src/main/java/rx/internal/operators/OnSubscribeFromIterable.java, src/test/java/rx/internal/operators/OnSubscribeFromIterableTest.java
This PR is a fix for #3006.
Ensured `it.hasNext()` not called more often than required especially when unsubscription happens before completion.
Added two unit tests (one for fast path and the other for backpressure) that failed on previous codebase.
=> Observable.from(iterable) - ensure it.hasNext() is not called unnecessarily #3006

src/main/java/rx/Subscriber.java
The `Subscriber` class is something I encounter frequently when debug stepping through code and is hard to read. This PR improves the names of variables and makes the `request` method more readable in particular by moving some code off into another method. 
I've also put in a `return` straight after the `addToRequested(n)` call so that we don't need to make an unnecessary test of `producerToRequestFrom != null`. Very minor saving I'm sure but why not.
Javadoc is still missing and I thought to leave that for another PR (because it will require a bit more thought).
=> Improve Subscriber readability

src/main/java/rx/internal/operators/OnSubscribeDefer.java, src/main/java/rx/internal/operators/OnSubscribeDelaySubscription.java, src/main/java/rx/internal/operators/OnSubscribeDelaySubscriptionWithSelector.java, src/main/java/rx/internal/operators/OnSubscribeUsing.java, src/main/java/rx/internal/operators/OperatorDoOnSubscribe.java, src/main/java/rx/internal/operators/OperatorDoOnUnsubscribe.java, src/main/java/rx/internal/operators/OperatorGroupBy.java, src/main/java/rx/internal/operators/OperatorMulticast.java, src/main/java/rx/internal/operators/OperatorOnErrorResumeNextViaFunction.java, src/main/java/rx/observers/TestSubscriber.java, src/test/java/rx/internal/operators/OperatorPublishTest.java
Started investigating multiple calls to onStart based on #2979 and found a bunch, but since onStart can be overridden, I might have missed cases. In addition, I've found a single place where a producer is set twice on a subscriber but again, many other places may exist.
=> Fixed multiple calls to onStart.

src/main/java/rx/observers/TestSubscriber.java, src/test/java/rx/observers/TestSubscriberTest.java
The method `TestSubscriber.awaitTerminalEventAndUnsubscribeOnTimeout` did not unsubscribe on timeout. This PR fixes it.
=> TestSubscriber - fix awaitTerminalEventAndUnsubscribeOnTimeout

src/main/java/rx/Observable.java, src/main/java/rx/internal/operators/OperatorWindowWithSize.java, src/main/java/rx/internal/operators/OperatorWindowWithTime.java, src/test/java/rx/internal/operators/OperatorWindowWithSizeTest.java, src/test/java/rx/internal/operators/OperatorWindowWithTimeTest.java
backpressure support to window(size, skip).
See #1880.
=> Fixed window(time) to work properly with unsubscription, added

src/main/java/rx/Observable.java
=> Deprecated onBackpressureBlock

src/main/java/rx/Observable.java, src/perf/java/rx/operators/OperatorSerializePerf.java, src/test/java/rx/internal/operators/OnSubscribeCacheTest.java, src/test/java/rx/internal/operators/OnSubscribeCombineLatestTest.java, src/test/java/rx/internal/operators/OnSubscribeRefCountTest.java, src/test/java/rx/internal/operators/OnSubscribeTimerTest.java, src/test/java/rx/internal/operators/OperatorBufferTest.java, src/test/java/rx/internal/operators/OperatorObserveOnTest.java, src/test/java/rx/internal/operators/OperatorPublishTest.java, src/test/java/rx/internal/producers/ProducersTest.java
The existing six methods below didn't make sense and caused some confusion.
```
timer(delay, timeUnit[, scheduler]);  --> emits 0 after delay and completes
timer(delay, period, timeUnit[, scheduler]); --> emits 0 after delay and then i++ after every period forever
interval(period, timeUnit[, schduler); --> emits i++ after every period forever
```
I felt that the middle method acted more like the third method `interval` than first method `timer`.  This PR is to make this change.
```
timer(delay, timeUnit[, scheduler]);  --> emits 0 after delay and completes
+@Deprecated
timer(delay, period, timeUnit[, scheduler]); --> emits 0 after delay and then i++ after every period forever
+interval(delay, period, timeUnit[, scheduler]); --> emits 0 after delay and then i++ after every period forever …
```
=> Deprecate and rename two timer overloads to interval

src/main/java/rx/observers/TestSubscriber.java, src/test/java/rx/internal/operators/OnSubscribeRangeTest.java
Since we use this so much I've added factory methods so we can infer types. 
Instead of 
```java
TestSubscriber<Integer> ts = new TestSubscriber<Integer>();
```
We can write
```java
TestSubscriber<Integer> ts = TestSubscriber.create();
```
I changed the tests in `OnSubscribeRangeTest` to demo the usage.
=> TestSubscriber - add factory methods

src/main/java/rx/internal/operators/OperatorSwitch.java, src/test/java/rx/internal/operators/OperatorSwitchTest.java
`OperatorSwitch` didn't record the total of requests before first inner subscription occurring and had problems with request overflow. 
Includes 4 unit tests that failed on the original code.
=> switchOnNext - ensure initial requests additive and fix request overflow

src/main/java/rx/internal/operators/OnSubscribeRedo.java, src/test/java/rx/internal/operators/OperatorRetryTest.java, src/test/java/rx/internal/operators/OperatorRetryWithPredicateTest.java
This is the continuation of #2930 with a rebased PR.
There are sporadic testing failures with this PR so not ready for merge. I'll note some failures with this one soon.
=> Fix retry() race conditions

src/perf/java/rx/operators/OperatorFlatMapPerf.java
This test was reported broken in https://github.com/ReactiveX/RxJava/pull/2928#issuecomment-113229698
Fixing by adding the use of LatchedObserver.
Previously broken test results:
```
r.o.OperatorFlatMapPerf.flatMapIntPassthruAsync         1  thrpt         5   363615.622   115041.519    ops/s
r.o.OperatorFlatMapPerf.flatMapIntPassthruAsync      1000  thrpt         5      350.204      125.773    ops/s
r.o.OperatorFlatMapPerf.flatMapIntPassthruAsync   1000000  thrpt         5        0.319        0.184    ops/s
```
Fixed results:
```
r.o.OperatorFlatMapPerf.flatMapIntPassthruAsync         1  thrpt         5   102109.681     8709.920    ops/s
r.o.OperatorFlatMapPerf.flatMapIntPassthruAsync      1000  thrpt         5      403.071      130.651    ops/s …
```
=> Fix OperatorFlatMapPerf.flatMapIntPassthruAsync Perf Test

src/main/java/rx/Observable.java
The singleton `EMPTY` returned by `Observable.empty()` can be instantiated lazily because it is not always required.
=> Instantiate EMPTY lazily

src/main/java/rx/Observable.java, src/main/java/rx/internal/operators/OperatorTakeLast.java
This PR includes these changes:
* standardized parameter names for `take`, `takeLast`, `skip`, `limit` to use `count` instead of `num`
* enhanced the javadoc for `takeLast` so it is clear for all overrides that if the observable contains less than `count` items then all will be emitted.
* improved the exception message thrown by `OperatorTakeLast` when `count` <0
Addresses #3027
=> takeLast() javadoc fixes, standardize parameter names (count instead of num)

src/main/java/rx/internal/operators/OperatorDelay.java, src/test/java/rx/internal/operators/OperatorDelayTest.java
Originally, the error through `delay` was emitted directly to the child without serializing in respect of an in-flight `onNext()`. This change schedules the error on the worker with no delay which ensures proper serialization. (The alternative would be to wrap the child into a `SerializedSubscriber`, however, that wouldn't immediately cancel any in-flight onNext schedules.)
=> Delay: error cut ahead was not properly serialized

src/main/java/rx/observers/TestSubscriber.java
* standardize on `Asserts that` and `Returns`
* fix tenses and wordings
=> TestSubscriber javadoc cleanup

src/test/java/rx/observers/SerializedObserverTest.java
Factored out the NPE before the thread creation as it can take several milliseconds and other values can just slip through.
=> Reduce test failure likelihood of testMultiThreadedWithNPEinMiddle

src/main/java/rx/Observable.java, src/main/java/rx/internal/operators/OnSubscribeSingle.java, src/test/java/rx/internal/operators/OnSubscribeSingleTest.java
* closes ReactiveX/RxJava#3038
* this method allows an observable which is guaranteed to return exactly one
item to be converted to a Single
* NOTE: the semantics of this function are very similar to that of single
* i.e. errors are passed through, more than one item results in an
IllegalArgumentException, completion without emission results in a
NoSuchElementException and exactly one item is passed through the onSuccess
method of SingleSubscriber
=> single: add toSingle method to Observable

src/main/java/rx/internal/operators/OnSubscribeDefer.java, src/main/java/rx/internal/operators/OnSubscribeDelaySubscription.java, src/main/java/rx/internal/operators/OnSubscribeDelaySubscriptionWithSelector.java, src/main/java/rx/internal/operators/OnSubscribeUsing.java, src/main/java/rx/internal/operators/OperatorDoOnSubscribe.java, src/main/java/rx/internal/operators/OperatorDoOnUnsubscribe.java, src/main/java/rx/observers/Subscribers.java
Add utility method to `Subscribers` to perform this common use case:
Naming briefly discussed in #3057.
```java
new Subscriber<T>(subscriber) {
@Override
public void onCompleted() {
subscriber.onCompleted();
}
@Override
public void onError(Throwable e) {
subscriber.onError(e);
}
@Override
public void onNext(T t) {
subscriber.onNext(t);
}
};
```
=> add Subscribers.wrap

src/main/java/rx/Subscriber.java
This PR 
* adds missing javadoc to the `Subscriber(Subscriber)` constructor
* improves (hopefully!) the javadoc for the constructor `Subscriber(Subscriber,boolean)`
* adds missing javadoc for `setProducer`
=> add and improve javadoc in Subscriber

src/main/java/rx/internal/operators/OnSubscribeSingle.java, src/test/java/rx/internal/operators/OnSubscribeSingleTest.java
As per my comment in #3049, `Observable.toSingle` should use `unsafeSubscribe` internally.
This PR includes a unit test that failed on previous code.
=> toSingle() should use unsafeSubscribe

src/main/java/rx/exceptions/CompositeException.java, src/test/java/rx/exceptions/CompositeExceptionTest.java
`CompositeException` won't crash if it received null by some means. A `null` collection or `null` collection item is replaced by a `NullPointerException` instance.
See also: #3046.
=> CompositeException extra NPE protection

src/main/java/rx/Observable.java, src/main/java/rx/internal/operators/OperatorReplay.java, src/test/java/rx/internal/operators/OperatorReplayTest.java
I've added backpressure support to the replay() operator(s).
Related issue: #1487
=> Operator replay() now supports backpressure

src/main/java/rx/internal/operators/OperatorElementAt.java
Based on #3014 
The operator can request up to Long.MAX_VALUE because it will only ever return a single value. If there are fewer elements, the onCompleted() will be triggered anyway. If there are more elements, the unsubscribe() will stop the sequence at the index.
=> ElementAt request management enhanced

src/main/java/rx/Observable.java, src/main/java/rx/internal/operators/OperatorWindowWithObservableFactory.java, src/main/java/rx/internal/operators/OperatorWindowWithStartEndObservable.java, src/test/java/rx/internal/operators/OperatorWindowWithObservableTest.java, src/test/java/rx/internal/operators/OperatorWindowWithStartEndObservableTest.java
Fixed unsubscription propagation of two Window variants (boundary, start-end).
In addition, there was a discrepancy reported on [StackOverflow](http://stackoverflow.com/questions/30963993/rxjava-window-buffer-overload-questions-incompatibility-with-rx-net) regarding the factory-boundary version. In Rx.NET, the factory is called whenever the previous boundary observable has produced a value. I.e., instead of a series of `onNexts` from the same `Observable`, it uses a series of `Observable`s with a single `onNext` emission as a boundary indicator.
=> Window with Observable: fixed unsubscription and behavior

src/main/java/rx/Observable.java, src/main/java/rx/internal/operators/OnSubscribeAutoConnect.java, src/main/java/rx/observables/ConnectableObservable.java, src/test/java/rx/observables/ConnectableObservableTest.java
There is a need for auto-connection capability for an arbitrary ConnectableObservable similar to how it is possible now to use cache() as an auto-connected unbounded replay.
The new `autoConnect()` method let's specify the number of `Subscriber`s required for the real connection to happen and also offers the ability to receive the connection `Subscription`.
I've also updated the parameter name of `cache(int)` to reflect it is a capacity hint and not a bound.
=> ConnectableObservable autoConnect operator

src/main/java/rx/internal/operators/OperatorMerge.java, src/test/java/rx/BackpressureTests.java
Requested amount could reach zero between the first check and entering the synchronized block where it has to be re-read in order to verify the scalar emission can really happen at that point; the new `testMergeAsyncThenObserveOnLoop` test failed with `MissingBackpressureException` after ~20 rounds on my i7 4770K.
This might or might not relate to the canary failure; if combined with retry(), it could have failed over and over, but I'm not sure where the worker retention might have happened.
=> Fix request != 0 checking in the scalar paths of merge()

src/test/java/rx/schedulers/ExecutorSchedulerTest.java
This test fails for me occasionally on my slow laptop when full test suite run because work is scheduled for only 1ms in the future. I've decreased the probability of this one failing by changing the schedule to 50ms in the future.
=> improve ExecutorSchedulerTest.testOnBackpressureDrop

src/test/java/rx/BackpressureTests.java, src/test/java/rx/internal/operators/OperatorMergeMaxConcurrentTest.java
These tests were giving me regular failures on my slow laptop:
* `OperatorMergeMaxConcurrentTest.testSimpleOneLessAsync`
* `BackpressureTests.testOnBackpressureDrop`
They both loop repeatedly looking for failure or lockup. If the machine running the tests isn't fast enough then the tests timeout before reaching the desired number of loops. This PR adds a break to the tests when the loop has run for 9 seconds (timeout is 10 seconds).
=> break tests as approach timeout so that don't fail on slow machines

src/main/java/rx/Observable.java, src/test/java/rx/ObservableTests.java
`Observable.forEach` javadoc suffered from a bit of copy-and-paste and neglected to mention the possible throw of `OnErrorNotImplementedException`.
Also added a couple of unit tests.
=> fix forEach javadoc

src/main/java/rx/internal/operators/OperatorTake.java, src/test/java/rx/internal/operators/OperatorTakeTest.java
Fixes the case uncovered by #3095.
=> Fix take swallowing exception if thrown by exactly the nth onNext call to it.

src/main/java/rx/internal/operators/BlockingOperatorToIterator.java, src/main/java/rx/observables/BlockingObservable.java, src/test/java/rx/internal/operators/BlockingOperatorNextTest.java, src/test/java/rx/observables/BlockingObservableTest.java
I'm using Observable for backport of Java 8's java.util.stream (i.e. [no more loops](http://www.deadcoderising.com/java-8-no-more-loops/)) for Android project.
```java
List<Foo> list2 = Observable.from(list)
.map(...)
.filter(...)
.toList().toBlocking().single()
```
But it sometimes emits InterruptedException at BlockingObservable.
https://github.com/ReactiveX/RxJava/issues/1804#issuecomment-61396523
As the BlocingObservable is placed in map() of another observable with `subscribeOn(Schedulers.io())`, and it is unsubscribed from main thread, perhaps Future.cancel(true) is called on unsubscribing. (#1914)
This PR allows BlockingObsevable not to be interrupted when source observable emits synchronously, by checking current latch or queue state before awaiting for them.
=> No InterruptedException with synchronous BlockingObservable

src/main/java/rx/internal/schedulers/NewThreadWorker.java, src/main/java/rx/internal/util/PlatformDependent.java, src/test/java/rx/internal/schedulers/NewThreadWorkerTest.java
Resolves #3119.
This PR adds methods for detecting Android API Version and disables `NewThreadWorker.tryEnableCancelPolicy()` on Android API < 21 which has significant performance cost on Android.
PR also improves performance of `NewThreadWorker.tryEnableCancelPolicy()` via caching Reflection.
=> Improve performance of NewThreadWorker, disable search for setRemoveOnCancelPolicy() on Android API < 21

src/main/java/rx/Observable.java, src/main/java/rx/internal/operators/OperatorRetryWithPredicate.java, src/test/java/rx/internal/operators/OperatorRetryWithPredicateTest.java
Apparently, we forgot about this operator. The backpressure handling is a trivial case with `ProducerArbiter`. I've also fixed some apparent code indentation error.
Originally reported in #3128 with a test case which I didn't include due to its lengthy nature; however, I did run the test manually and both passed after the fix.
=> Fix retry with predicate ignoring backpressure.

src/main/java/rx/internal/operators/OperatorMaterialize.java, src/test/java/rx/internal/operators/OperatorMaterializeTest.java
As mentioned in #3098 the existing version of  `materialize` could deliver one more event than requested being the termination event (completion or error).
This PR ensures that a termination event is buffered till requested.
=> materialize() - add backpressure support

src/test/java/rx/schedulers/CachedThreadSchedulerTest.java, src/test/java/rx/schedulers/ComputationSchedulerTests.java, src/test/java/rx/schedulers/ExecutorSchedulerTest.java
The former Executor-based check instantiated the wrong worker. In addition, I've refactored the common parts, added check for periodic task retention (after the first round) and added the checks to computation scheduler test as well.
=> Improved Scheduler.Worker memory leak detection

src/main/java/rx/Notification.java, src/main/java/rx/Single.java
P.S. 
@benjchristensen @akarnokd sorry for large amount of simple pull requests, I'm doing full code review of RxJava sources http://artemzin.com/blog/rxjava-code-review-part-1/ and I'll create PRs and issues during this review.
I'll try to group changes by themes so it will be easy to review them. Looks like this adventure is going to be part of #3145!
=> Remove unnecessary static modifier

src/main/java/rx/internal/util/SynchronizedQueue.java, src/test/java/rx/internal/util/SynchronizedQueueTest.java
Courtesy of findBugs, `SynchronizedQueue.equals()` is improperly implemented. I used Eclipse to generate a new `equals()` method based on the `list` field.
The existing code would even have failed to return true when testing queue equality with itself.
I don't think this is causing problems anywhere but this PR will ensure that it doesn't cause a problem in the future.
=> Fix SynchronizedQueue.equals

src/main/java/rx/observers/SerializedObserver.java, src/main/java/rx/observers/TestObserver.java, src/main/java/rx/observers/TestSubscriber.java, src/test/java/rx/observers/ObserversTest.java, src/test/java/rx/observers/SafeObserverTest.java, src/test/java/rx/observers/SafeSubscriberTest.java, src/test/java/rx/observers/SerializedObserverTest.java, src/test/java/rx/observers/SubscribersTest.java, src/test/java/rx/observers/TestObserverTest.java, src/test/java/rx/observers/TestSubscriberTest.java
This includes a rewrite of `SerializedObserver` to have a more cleaner exception semantics.
The `TestSubscriberTest` can be improved further but I've run out of time for today.
=> Observers package test coverage and fixes.

src/main/java/rx/internal/operators/OperatorSwitch.java, src/test/java/rx/internal/operators/OperatorSwitchIfEmptyTest.java, src/test/java/rx/internal/operators/OperatorSwitchTest.java
As per #3073 a race condition in `OperatorSwitch` means that requests can be lost. This PR uses `ProducerArbiter` to ensure all unfulfilled requests are carried through to the next `Observable`.
I also changed `InnerSubscriber` to be a static class as opposed to an inner class just to decouple it from surrounding state.
=> switchOnNext() - fix lost requests race condition 

src/main/java/rx/internal/operators/OnSubscribeFromIterable.java, src/perf/java/rx/operators/FromIterablePerf.java
Some restructuring reduces the overhead of operators:
- extending `AtomicLong` gives access to atomic intrinsics for the request accounting
- loading the final fields into local variables prevents them from being reloaded from cache due to the atomics around them
- request() is hot but generally too large due to the fastpath/slowpath fit and JIT may not want to pick it up early. By refactoring the two paths into two separate methods, it becomes inline friendly for the either of the paths.
Benchmark results on my i7 4770K, Windows 7 x64, Java 8u51:
The benchmark from #3118 gives this result:
=> FromIterable overhead reduction.

src/main/java/rx/internal/operators/OnSubscribeRange.java, src/perf/java/rx/operators/OperatorRangePerf.java, src/test/java/rx/internal/operators/OnSubscribeRangeTest.java
Applied some refactorings and local variable usage to reduce the overhead.
Few observations:
- Having too many local variables may cause register spill, even on x64 which makes some `size` benchmark faster while other slower.
- The observeOn benchmarks are quite hectic because of receiving thread migration caused by the round-robin worker assignment. It affects the benchmarks with 1 or 1000 elements in the stream.
- Note that the previous `OperatorRangePerf` `size = 1` measured the speed of `just` due to the optimization of `range()`. The updated perf now instantiates the `OnSubscribeRange`.
- Note that the `observeOn` benchmark with `size = 1` run the `just()` as well.
Benchmark comparison (i7 4770K, Windows 7 x64, Java 8u51)
=> Range overhead reduction.

src/main/java/rx/exceptions/OnCompletedFailedException.java, src/main/java/rx/exceptions/UnsubscribeFailedException.java, src/main/java/rx/internal/util/RxJavaPluginUtils.java, src/main/java/rx/observers/SafeSubscriber.java, src/test/java/rx/observers/SafeObserverTest.java, src/test/java/rx/observers/SafeSubscriberTest.java
Discussed in #2464, when an observable emits `onCompleted` but `unsubscribe` in `SafeSubscriber` throws then the error should be reported to the `RxJavaPlugin` error handler and if that fails a stack trace is written to `System.err`.
=> SafeSubscriber - report onCompleted unsubscribe error to RxJavaPlugin 

src/main/java/rx/internal/operators/BackpressureUtils.java, src/test/java/rx/internal/operators/BackpressureUtilsTest.java
Common methods to add and multiply longs and cap the result at Long.MAX_VALUE in case of an overflow.
=> BackpressureUtils capped add/multiply methods + tests

src/main/java/rx/internal/operators/OperatorReplay.java, src/test/java/rx/internal/operators/OperatorReplayTest.java
Reported in #3166 
What happened is that if there are multiple subscribers, one with larger requests than the others and it unsubscribed early, the new max request of the others then became smaller than before which yielded a negative difference and thus a negative request.
=> Fixed negative request due to unsubscription of a large requester

src/main/java/rx/internal/operators/OperatorMapNotification.java, src/test/java/rx/internal/operators/OperatorMapNotificationTest.java
Fixed the NPE reported in #3180.
=> MapNotification producer NPE fix

build.gradle, src/main/java/io/reactivex/Observable.java, src/main/java/io/reactivex/Observer.java
- Added compile dependency for reactive-streams.
- Added some basic methods to Observable.
As long as the project defaults to 1.x, the create PR webpage will take a long time to render because it tries to compare a small branch 2.x against the huge 1.x branch with lots of 'deleted' content. A separate project would be much simpler to operate.
=> RS dependency, some basic Observable/Observer methods.

src/main/java/io/reactivex/internal/operators/PublisherAutoConnect.java, src/main/java/io/reactivex/observables/ConnectableObservable.java
`refCount` will come later, although its behavior is sometimes surprising to developers: it disconnects and reconnects in certain use pattern. The alternative is to use `autoConnect(n, connectionConsumer)` which lets the developer explicitly disconnect.
=> ConnectableObservable and autoConnect

src/main/java/io/reactivex/internal/operators/OperatorFilter.java, src/main/java/io/reactivex/internal/operators/OperatorSkip.java, src/main/java/io/reactivex/internal/operators/OperatorSkipLast.java, src/main/java/io/reactivex/internal/operators/OperatorSkipUntil.java, src/main/java/io/reactivex/internal/operators/OperatorSkipWhile.java
In `takeUntil`, the other source may emit an `onError` before the main source sets a subscription. The fix makes sure if other is first, it sets an empty subscription before emitting the error (this is an RS specific thing, doesn't affect 1.x).
=> Operators of skip (untimed), filter; fix to takeUntil

src/main/java/io/reactivex/Observable.java, src/main/java/io/reactivex/internal/operators/OperatorObserveOn.java, src/main/java/io/reactivex/internal/operators/OperatorUnsubscribeOn.java, src/main/java/io/reactivex/internal/operators/PublisherSubscribeOn.java
Few considerations:
- Added an option to specify if `subscribeOn` should also request on the same worker or not. If not, the consumer thread may freely grab the producer and thus reduce the inter-thread communication.
- The scheduling of the subscription in `subscribeOn` now can't be cancelled because in RS, the indication of 'subscription' is to call `onSubscribe` on the proper thread. Since the `Subscriber` can't call cancel until it receives the subscription through `onSubscribe` the time it receives the subscription there is no point in cancelling the operation.
- Added two parametrization option to `observeOn`: the ability to delay the error after all the `onNext` events and the ability to specify the buffer size. Since many get surprised by the 1.x behavior, this should help the …
=> Operators observeOn, subscribeOn and unsubscribeOn

src/main/java/io/reactivex/Observable.java, src/main/java/io/reactivex/internal/subscribers/LambdaSubscriber.java, src/main/java/io/reactivex/internal/subscribers/SubscriptionLambdaSubscriber.java, src/main/java/io/reactivex/schedulers/Schedulers.java
+ forEachWhile that allows stopping the stream from within the onNext callback by returning false.
The lambda subscribe()s return a Disposable so they can be asynchronously cancelled.
=> Lambda-based subscribe and lifecycle tracking methods

src/main/java/io/reactivex/Observable.java, src/main/java/io/reactivex/internal/operators/OperatorOnBackpressureBuffer.java, src/main/java/io/reactivex/internal/operators/OperatorOnBackpressureDrop.java, src/main/java/io/reactivex/internal/operators/OperatorOnBackpressureLatest.java
There won't be `onBackpressureBlock` although it can work with `subscribeOn(scheduler, false)` since that won't schedule the request behind the blocked emission.
Operator `onBackpressureBuffer` has now a `delayError` option; I'd like to give the developer the option on this one. Naturally, the default is false.
=> Operators onBackpressure(Drop|Buffer|Latest)

src/main/java/io/reactivex/Observable.java, src/main/java/io/reactivex/internal/operators/OperatorGroupBy.java, src/main/java/io/reactivex/observables/GroupedObservable.java
This default implementation supports backpressure but doesn't coordinate the group requests with the main requests in any way. 
This means, for example, that given a million element source and a constant true key selector will queue up all million elements until a single subscriber consumes them.
The 1.x version had some coordination and all sorts of group management logic which I don't understand. I'll revisit this operator later.
=> Operator groupBy

src/main/java/io/reactivex/Observable.java, src/main/java/io/reactivex/internal/operators/OperatorWithLatestFrom.java, src/main/java/io/reactivex/internal/operators/PublisherLift.java, src/main/java/io/reactivex/internal/subscriptions/SubscriptionHelper.java
SubscriptionHelper for common validation logic.
The SubscriptionHelper's methods are not yet applied to former operators.
=> Operator WithLatestFrom, PublishLift to help with operator fusing,

src/main/java/io/reactivex/Observable.java, src/main/java/io/reactivex/internal/operators/OperatorDistinct.java, src/main/java/io/reactivex/internal/operators/OperatorReplay.java, src/main/java/io/reactivex/internal/operators/OperatorTimeInterval.java, src/main/java/io/reactivex/internal/subscribers/CancellingSubscriber.java, src/main/java/io/reactivex/schedulers/Timed.java
Instead of having `Timestamped` and `TimeInterval` with the same structure, let's have just a single one: `Timed`.
`distinctUntilChanged` is implemented via special `distinct`.
=> Operator distinct, timeInterval, common Timed container.

src/main/java/io/reactivex/Observable.java, src/main/java/io/reactivex/internal/operators/OperatorDoOnEach.java
The various doOnXXX operator overloads + range(scheduler) + repeat(scheduler).
=> Operations doOnX.

src/main/java/io/reactivex/internal/operators/OperatorFilter.java, src/main/java/io/reactivex/internal/operators/PublisherArraySource.java, src/main/java/io/reactivex/internal/subscribers/ConditionalSubscriber.java
emission/drain loops.
This may help with operators that call request(1) to replenish a dropped value (filter for example).
I've only implemented this with the array-source and with a lot of code duplication. I'll think about how to reduce this duplication via inheritance or with lambdas (which might negate the benefit).
=> ConditionalSubscriber to help fusing filter-like operators into

src/main/java/rx/internal/operators/OperatorScan.java, src/test/java/rx/internal/operators/OperatorScanTest.java
Fixes #3168
If there is no initial value, there is no need to manipulate the request amounts.
If there is an initial value, we must do a full emitter-loop with value queueing because now the downstream request can race with the first onNext or the setting of the upstream producer. The downside is the increased overhead which should be reduced when the spsc unbounded queues get merged.
=> Scan backpressure and first emission fix

src/main/java/rx/Notification.java, src/test/java/rx/NotificationTest.java
The Notification method was missing a check to hasValue and hasThrowable. This allowed for a null value onNext Notification to equal an Object notification. A similar bug for onError Notification events also existed.
=> Fix to Notification equals method.

src/main/java/io/reactivex/Observable.java, src/main/java/io/reactivex/internal/operators/OperatorSkipLastTimed.java, src/main/java/io/reactivex/internal/queue/SpscLinkedArrayQueue.java
The multi-offer helps with the timed skipLast. By offering two at once, the drain won't loop until the second value arrives.
=> Operators first, last, multi-offer for SpscLinkedArrayQueue

src/main/java/io/reactivex/Observable.java, src/main/java/io/reactivex/internal/operators/OperatorTakeWhile.java, src/main/java/io/reactivex/internal/subscribers/ConditionalSubscriber.java
+ a small correction to ConditionalSubscriber: the default onNext removed to avoid bad usage (i.e., not requesting if not accepted).
=> Operator takeWhile

src/main/java/io/reactivex/Observable.java, src/main/java/io/reactivex/internal/operators/OperatorCollect.java, src/main/java/io/reactivex/internal/operators/OperatorDistinct.java, src/main/java/io/reactivex/internal/operators/OperatorGroupBy.java, src/main/java/io/reactivex/internal/operators/OperatorReplay.java, src/main/java/io/reactivex/internal/operators/OperatorSkipUntil.java, src/main/java/io/reactivex/internal/operators/OperatorTakeUntil.java, src/main/java/io/reactivex/internal/operators/OperatorToList.java, src/main/java/io/reactivex/internal/operators/OperatorWithLatestFrom.java, src/main/java/io/reactivex/internal/operators/PublisherAmb.java, src/main/java/io/reactivex/internal/operators/PublisherCombineLatest.java, src/main/java/io/reactivex/internal/operators/PublisherDefer.java, src/main/java/io/reactivex/internal/operators/PublisherEmptySource.java, src/main/java/io/reactivex/internal/operators/PublisherErrorSource.java, src/main/java/io/reactivex/internal/operators/PublisherIterableSource.java, src/main/java/io/reactivex/internal/operators/PublisherScalarSource.java, src/main/java/io/reactivex/internal/operators/PublisherStreamSource.java, src/main/java/io/reactivex/internal/operators/PublisherUsing.java, src/main/java/io/reactivex/internal/operators/PublisherZip.java, src/main/java/io/reactivex/internal/subscriptions/EmptySubscription.java
EmptySubscriber convenience method to reduce boilerplate.
=> Operator using, some internal refactorings.

src/main/java/io/reactivex/subjects/UnicastSubject.java
subscriber only.
Should be the official API replacement of BufferUntilSubscriber.
=> UnicastSubject, onBackpressureBuffer-like behavior for a single

src/main/java/io/reactivex/Observable.java, src/main/java/io/reactivex/Try.java, src/main/java/io/reactivex/internal/disposables/SetCompositeResource.java, src/main/java/io/reactivex/internal/operators/OperatorBufferBoundary.java, src/main/java/io/reactivex/internal/operators/OperatorBufferExactBoundary.java, src/main/java/io/reactivex/internal/operators/OperatorBufferTimed.java, src/main/java/io/reactivex/internal/subscribers/QueueDrainSubscriber.java, src/main/java/io/reactivex/internal/subscriptions/EmptySubscription.java, src/main/java/io/reactivex/internal/util/QueueDrain.java
variants. 
Added `QueueDrain` and `QueueDrainSubscriber` for common queue-drain
operations. Not applied outside the `buffer()`s as of now.
=> Operator buffer with boundary and open-close, fixes to the timed

src/main/java/io/reactivex/Observable.java, src/main/java/io/reactivex/internal/operators/OperatorDebounceTimed.java, src/main/java/io/reactivex/internal/operators/OperatorOnBackpressureBuffer.java, src/main/java/io/reactivex/internal/operators/OperatorReplay.java, src/main/java/io/reactivex/internal/operators/OperatorTimeout.java, src/main/java/io/reactivex/internal/operators/OperatorTimeoutTimed.java, src/main/java/io/reactivex/internal/subscribers/FullArbiterSubscriber.java, src/main/java/io/reactivex/internal/subscriptions/FullArbiter.java
types.
+ FullArbiter and FullArbiterSubscriber to work with total-ordered notifications across sources.
I've also sorted `Observable` members.
=> Operator timeout, onBackpressureBuffer(onOverflow), fixes to parameter

src/main/java/io/reactivex/Observable.java, src/main/java/io/reactivex/Observer.java, src/main/java/io/reactivex/subjects/BehaviorSubject.java
The continuous delivery guarantee and the no-duplication requirement makes it necessary to read/write an index and object values together. I've implemented this with another synchronized block. The alternatives are:
- use an object of (index, value) and atomically set the reference (requires allocation on every value delivered.
- this current nested-synchronized block (no deadlock)
- use a reader-writer lock which works better when concurrent subscribers want to do their first emission at the same time.
=> BehaviorSubject

src/main/java/io/reactivex/Observable.java, src/main/java/io/reactivex/internal/operators/OperatorWindowBoundary.java, src/main/java/io/reactivex/internal/operators/OperatorWindowBoundarySelector.java, src/main/java/io/reactivex/internal/operators/OperatorWindowBoundarySupplier.java
I'm not 100% certain about the state management: when to let the main
source keep running and when to stop. I.e., the in the selector version,
if the other completes, it means no new window will be opened but the
active should keep receiving values until their closer fires. If all
such closers have fired, the main can be stopped.
=> Operator window with boundary (exact, selector, exact + supplier).

src/main/java/io/reactivex/subjects/AsyncSubject.java, src/main/java/io/reactivex/subjects/BehaviorSubject.java, src/main/java/io/reactivex/subjects/PublishSubject.java, src/main/java/io/reactivex/subjects/ReplaySubject.java
Subjects are exposed so they may receive nulls that would mess up the internal state.
=> Subjects onNext and onError null safety

src/main/java/io/reactivex/subscribers/AsyncObserver.java
It is meant to be somewhat a replacement for 1.x `rx.Subscriber`, but it
doesn't support `Subscriber` chaining.
I call it an `Observer` because one only needs to implement `onNext`, `onError`
and `onComplete` as with `rx.Observer`
=> AsyncObserver

src/main/java/io/reactivex/Observable.java, src/main/java/io/reactivex/internal/operators/PublisherGenerate.java
a function and handling backpressure/resource cleanup automatically.
The logic is based on @stealthcode 's SyncSubscriber proposal from 1.x
but using only the lambda-form.
=> Operator generate: create an observable that generates values by calling

src/main/java/rx/observables/SyncOnSubscribe.java, src/perf/java/rx/jmh/InputWithIncrementingInteger.java, src/perf/java/rx/observables/BlockingObservablePerf.java, src/perf/java/rx/observables/MultiInput.java, src/perf/java/rx/observables/SingleInput.java, src/perf/java/rx/observables/SyncOnSubscribePerf.java, src/test/java/rx/observables/SyncOnSubscribeTest.java
This is useful for creating an observable that reads from a data source in a synchronous manner. This is a rewrite of the `AbstractOnSubscribe` experimental class based on the ideas in #3003.
=> Implementing the SyncOnSubscribe

src/main/java/io/reactivex/internal/operators/PublisherGenerate.java, src/main/java/io/reactivex/subjects/UnicastSubject.java
The cancellation notification will come in handy with window (and in
groupby). It helps with the case when the main source has been cancelled
but the individual windows/groups are still being consumed. If those get
cancelled by their single Subscribers, this notification will reach the
source and once all windows/groups get cancelled, the main source can be
cancelled.
Fix to generator production accounting.
=> UnicastSubject javadoc, support for onCancelled notification.

src/main/java/io/reactivex/Observable.java, src/test/java/io/reactivex/ConcatTests.java
I've also added convenience overloads to concat 2-9 sources because `concat(Publisher...)` causes overload resolution conflict with `concat(Publisher<Publisher>)`.
=> Simplest concat test from 1.x

src/test/java/io/reactivex/ErrorHandlingTests.java, src/test/java/io/reactivex/EventStream.java
I've changed them to use `safeSubscribe` because plain RS subscribers
are not expected to throw.
=> ErrorHandlingTests and EventStream

src/test/java/io/reactivex/SubscriberTest.java
They seem to try testing the request mechanism on thin implementations and are somewhat of no use.
=> SubscriberTests port from 1.x

src/main/java/io/reactivex/Observable.java, src/main/java/io/reactivex/internal/operators/OperatorAll.java, src/main/java/io/reactivex/internal/operators/OperatorAny.java, src/test/java/io/reactivex/ObservableTests.java, src/test/java/io/reactivex/internal/operators/OperatorAllTest.java, src/test/java/io/reactivex/internal/operators/OperatorAnyTest.java, src/test/java/io/reactivex/internal/operators/OperatorAsObservableTest.java
Bugfix: since they would emit a value on an empty source, they have to hold it until an actual request comes in.
=> 2.x: test for operators all, any, asObservable, fixes to all and any

src/main/java/rx/Observable.java, src/main/java/rx/internal/operators/OnSubscribeFromCallable.java, src/test/java/rx/internal/operators/OnSubscribeFromCallableTest.java
Yep, this is a new operator.
Motivation? `Observable.defer()` requires function that returns `Observable<T>` when usually we don't want to create `Observable<T>` manually, we just want to defer execution of some function.
Like this:
```java
Observable
.fromCallable(() -> someFunc())
.subscribeOn(...)
...
```
Instead of this:
```java
Observable
.defer(() -> Observable.just(someFunc()))
.subscribeOn(...)
...
```
And more important case with deferring code that throws checked exceptions:
```java
Observable
.fromCallable(() -> {
Value value = ...;
// some code
return value;
})
.subscribeOn(...)
...
```
Instead of this:
```java
Observable
.defer(() -> {
try {
Value value = ...;
// some code that throws checked exceptions
return Observable.just(value);
} catch (Exception e) {
return …
```
=> Add Observable.fromCallable() as a companion for Observable.defer()

src/main/java/io/reactivex/Observable.java, src/main/java/io/reactivex/internal/operators/OperatorBufferBoundarySupplier.java, src/main/java/io/reactivex/internal/operators/PublisherFutureSource.java, src/main/java/io/reactivex/internal/subscriptions/AsyncSubscription.java, src/test/java/io/reactivex/internal/operators/BackpressureHelperTest.java, src/test/java/io/reactivex/internal/operators/BlockingOperatorLatestTest.java, src/test/java/io/reactivex/internal/operators/BlockingOperatorMostRecentTest.java, src/test/java/io/reactivex/internal/operators/BlockingOperatorToIteratorTest.java, src/test/java/io/reactivex/internal/operators/OnSubscribeDeferTest.java, src/test/java/io/reactivex/internal/operators/OperatorAnyTest.java, src/test/java/io/reactivex/internal/operators/OperatorBufferTest.java, src/test/java/io/reactivex/internal/subscriptions/AsyncSubscriptionTest.java
+ added AsyncSubscription that allows setting the actual subscription
later and can hold a resource. It has less overhead than
SubscriptionArbiter due to single use.
=> 2.x: added missing buffer overload (with boundary selector)

src/main/java/io/reactivex/internal/operators/OperatorConcatMap.java, src/main/java/io/reactivex/internal/subscriptions/SubscriptionArbiter.java, src/test/java/io/reactivex/internal/operators/OperatorCastTest.java, src/test/java/io/reactivex/internal/operators/OperatorConcatTest.java
The concat reuses the same inner subscriber to save on its allocation
cost which works only if the inner source conforms with the spec and
doesn't emit any event after an onComplete(). There is a test that
explicitly calls onComplete() twice to test the resilience of concat.
The current workaround makes this test pass but any async non-conforming
source may still bug out the operator. 
This is a tradeoff between safety and performance. If we'd expect such
non-conforming behavior, the current optimization has to be turned into
a regular individually allocated inner subscribers.
=> 2.x: operators cast and concat tests

src/main/java/io/reactivex/internal/operators/OperatorDebounce.java, src/main/java/io/reactivex/internal/operators/OperatorDebounceTimed.java, src/test/java/io/reactivex/internal/operators/OperatorDebounceTest.java, src/test/java/io/reactivex/internal/operators/OperatorDefaultIfEmptyTest.java
When debounce is completed, the last value encountered is emitted immediately.
=> 2.x: Operator debounce and defaultIfEmpty, fix to debounce behavior

src/main/java/io/reactivex/Observable.java, src/main/java/io/reactivex/internal/operators/OperatorDistinct.java, src/main/java/io/reactivex/internal/operators/OperatorDoOnEach.java, src/test/java/io/reactivex/internal/operators/OperatorDistinctTest.java, src/test/java/io/reactivex/internal/operators/OperatorDistinctUntilChangedTest.java, src/test/java/io/reactivex/internal/operators/OperatorDoOnEachTest.java
Note: several tests have been ignored due to non-conformance with RS
Added missing distinct and distinctUntilChanged overloads, fixed doOnEach not cancelling upstream if the callback crashes on the onNext path.
=> 2.x: operator test distinct, distinctUntilChanged and doOnEach

src/main/java/io/reactivex/Observable.java, src/main/java/io/reactivex/internal/operators/OperatorMapNotification.java, src/main/java/io/reactivex/internal/operators/OperatorOnBackpressureBuffer.java, src/main/java/io/reactivex/internal/subscribers/SubscriptionLambdaSubscriber.java, src/test/java/io/reactivex/TestHelper.java, src/test/java/io/reactivex/internal/operators/OperatorConcatTest.java, src/test/java/io/reactivex/internal/operators/OperatorDebounceTest.java, src/test/java/io/reactivex/internal/operators/OperatorDelayTest.java, src/test/java/io/reactivex/internal/operators/OperatorDematerializeTest.java, src/test/java/io/reactivex/internal/operators/OperatorDistinctTest.java, src/test/java/io/reactivex/internal/operators/OperatorDistinctUntilChangedTest.java, src/test/java/io/reactivex/internal/operators/OperatorDoOnEachTest.java, src/test/java/io/reactivex/internal/operators/OperatorDoOnRequestTest.java, src/test/java/io/reactivex/internal/operators/OperatorDoOnSubscribeTest.java, src/test/java/io/reactivex/internal/operators/OperatorDoOnUnsubscribeTest.java, src/test/java/io/reactivex/internal/operators/OperatorFlatMapTest.java, src/test/java/io/reactivex/internal/operators/OperatorMergeDelayErrorTest.java, src/test/java/io/reactivex/internal/operators/OperatorMergeMaxConcurrentTest.java, src/test/java/io/reactivex/internal/operators/OperatorMergeTest.java
+ added operator flatMap of notifications, fixed a bug in onBackpressureBuffer
Note also the few ignored tests because they either want to test against a null value or try to throw from RS methods.
=> 2.x: operator test flatMap, merge, mergeDelayError

src/main/java/io/reactivex/Observable.java, src/main/java/io/reactivex/internal/operators/OperatorGroupBy.java, src/main/java/io/reactivex/internal/subscriptions/BooleanSubscription.java, src/main/java/io/reactivex/observables/GroupedObservable.java, src/test/java/io/reactivex/internal/operators/OperatorGroupByTest.java
for GroupedObservable
+ added BooleanSubscription to detect cancellation without caring about
requests.
I'm still not 100% convinced the groupBy request coordination works
properly (i.e., no stall due lack of requests from one of the groups).
=> 2.x: operator test for groupBy; fix to groupBy and type argument swap

src/main/java/io/reactivex/internal/operators/OperatorObserveOn.java, src/main/java/io/reactivex/internal/operators/PublisherCombineLatest.java, src/main/java/io/reactivex/internal/operators/PublisherIntervalSource.java, src/main/java/io/reactivex/observables/BlockingObservable.java, src/main/java/io/reactivex/subjects/PublishSubject.java, src/test/java/io/reactivex/internal/operators/OperatorObserveOnTest.java
+ fix to observeOn to not request if cancelled in onNext delivery
+ fix combineLatest error emission if the other sources are late or
never emit
+ fix interval and PublishSubject to send MissingBackpressureException
=> 2.x: operator test observeOn

src/main/java/io/reactivex/internal/operators/OperatorOnErrorNext.java, src/main/java/io/reactivex/internal/operators/OperatorOnErrorReturn.java, src/main/java/io/reactivex/internal/subscriptions/EmptySubscription.java, src/test/java/io/reactivex/internal/operators/OperatorOnErrorResumeNextViaFunctionTest.java, src/test/java/io/reactivex/internal/operators/OperatorOnErrorResumeNextViaObservableTest.java, src/test/java/io/reactivex/internal/operators/OperatorOnErrorReturnTest.java, src/test/java/io/reactivex/internal/operators/OperatorOnExceptionResumeNextViaObservableTest.java
I had to ignore tests that throw exceptions from a Publisher.subscribe or an Operator.apply due to their non-conformant behavior.
=> 2.x: operator test onError and onException, relevant bugfixes

src/main/java/io/reactivex/Observable.java, src/main/java/io/reactivex/internal/disposables/SetCompositeResource.java, src/main/java/io/reactivex/internal/operators/OperatorMap.java, src/main/java/io/reactivex/internal/operators/OperatorPublish.java, src/main/java/io/reactivex/internal/operators/PublisherRedo.java, src/main/java/io/reactivex/internal/operators/PublisherRepeat.java, src/main/java/io/reactivex/internal/operators/PublisherRetryPredicate.java, src/main/java/io/reactivex/internal/operators/PublisherSubscribeOn.java, src/main/java/io/reactivex/internal/schedulers/IOScheduler.java, src/main/java/io/reactivex/internal/subscriptions/SubscriptionArbiter.java, src/test/java/io/reactivex/internal/operators/OperatorMergeMaxConcurrentTest.java, src/test/java/io/reactivex/internal/operators/OperatorMergeTest.java, src/test/java/io/reactivex/internal/operators/OperatorPublishTest.java, src/test/java/io/reactivex/internal/operators/OperatorReduceTest.java, src/test/java/io/reactivex/internal/operators/OperatorRepeatTest.java
+ added toSingle and toNbpObservable to Observable
+ fixed bugs in many operators and in the IO scheduler's release logic
=> 2.x: operator tests: publish, reduce, repeat + fixes

src/main/java/io/reactivex/Observable.java, src/main/java/io/reactivex/Try.java, src/main/java/io/reactivex/internal/operators/OperatorMap.java, src/main/java/io/reactivex/internal/operators/PublisherLift.java, src/main/java/io/reactivex/internal/operators/PublisherRedo.java, src/main/java/io/reactivex/internal/operators/PublisherRetryBiPredicate.java, src/test/java/io/reactivex/internal/operators/OperatorRetryTest.java, src/test/java/io/reactivex/internal/operators/OperatorRetryWithPredicateTest.java
+ retry with bipredicate
+ fixed map not checking the returned value for null
+ since RS doesn't allow throwing other than NPE, temporarily subscribe
and lift will throw NPE with the actual error as cause so we don't miss
an operator bug due to swallowed exceptions.
=> 2.x: operator test: retry, retryWhen

src/main/java/io/reactivex/Observable.java, src/main/java/io/reactivex/internal/operators/OperatorSkipLastTimed.java, src/test/java/io/reactivex/internal/operators/OperatorSampleTest.java, src/test/java/io/reactivex/internal/operators/OperatorScanTest.java, src/test/java/io/reactivex/internal/operators/OperatorSequenceEqualTest.java, src/test/java/io/reactivex/internal/operators/OperatorSerializeTest.java, src/test/java/io/reactivex/internal/operators/OperatorSingleTest.java, src/test/java/io/reactivex/internal/operators/OperatorSkipLastTest.java, src/test/java/io/reactivex/internal/operators/OperatorSkipLastTimedTest.java, src/test/java/io/reactivex/internal/operators/OperatorSkipTest.java, src/test/java/io/reactivex/internal/operators/OperatorSkipTimedTest.java, src/test/java/io/reactivex/internal/operators/OperatorSkipUntilTest.java, src/test/java/io/reactivex/internal/operators/OperatorSkipWhileTest.java
Note that since we know have time unit in schedulers, one must be
careful with the time unit of the timed skip operators. The timestamps
will be calculated via this unit and may not return the expected values. 
For example, a skipLast of 1 second will not skip the value 0.5 seconds
before completion because its timestamp is rounded down to the start of
the second. But if one uses 1000 milliseconds, the value will be
skipped.
=> 2.x: operator test: skip variants and bugfix

src/main/java/io/reactivex/Observable.java, src/test/java/io/reactivex/internal/operators/OperatorSkipTimedTest.java, src/test/java/io/reactivex/internal/operators/OperatorSkipUntilTest.java, src/test/java/io/reactivex/internal/operators/OperatorSkipWhileTest.java, src/test/java/io/reactivex/internal/operators/OperatorTimestampTest.java, src/test/java/io/reactivex/internal/operators/OperatorToMapTest.java, src/test/java/io/reactivex/internal/operators/OperatorToMultimapTest.java, src/test/java/io/reactivex/internal/operators/OperatorToObservableListTest.java, src/test/java/io/reactivex/internal/operators/OperatorToObservableSortedListTest.java
+ signature fix to toMultimap and removed deprecated markers.
=> 2.x: operator tests: timestamp, toMap, toMultiMap, toList, toSortedList

src/main/java/io/reactivex/Observable.java, src/main/java/io/reactivex/internal/operators/OperatorObserveOn.java, src/main/java/io/reactivex/internal/operators/OperatorUnsubscribeOn.java, src/main/java/io/reactivex/internal/operators/OperatorWithLatestFrom.java, src/main/java/io/reactivex/internal/operators/PublisherIterableSource.java, src/main/java/io/reactivex/internal/operators/PublisherSubscribeOn.java, src/main/java/io/reactivex/internal/operators/PublisherZip.java, src/main/java/io/reactivex/internal/operators/PublisherZipIterable.java, src/main/java/io/reactivex/internal/schedulers/ScheduledRunnable.java, src/main/java/io/reactivex/subscribers/TestSubscriber.java, src/test/java/io/reactivex/internal/operators/OperatorReplayTest.java, src/test/java/io/reactivex/internal/operators/OperatorToObservableListTest.java, src/test/java/io/reactivex/internal/operators/OperatorUnsubscribeOnTest.java, src/test/java/io/reactivex/internal/operators/OperatorWithLatestFromTest.java, src/test/java/io/reactivex/internal/operators/OperatorZipCompletionTest.java, src/test/java/io/reactivex/internal/operators/OperatorZipIterableTest.java
+ fixed cancellation behavior of observeOn, subscribeOn and
unsubscribeOn (when and what to call cancel on)
+ fixed infinite loop in ScheduledRunnable
+ fixed zip not quitting eagerly if one of the sources was shorter
+ added specific ZipIterable because zip-iterable tests expect it to be
not prefetching any of the sources (the plain zip does prefetch)
+ made the fromIterable more resilient to Iterable/Iterator crashes and
added null-value checks
=> 2.x: operator tests unsubscribeOn, withLatestFrom, zip (partial)

src/main/java/io/reactivex/Observable.java, src/main/java/io/reactivex/internal/operators/OperatorConcatMap.java, src/main/java/io/reactivex/internal/operators/OperatorWindow.java, src/main/java/io/reactivex/internal/operators/OperatorWindowBoundary.java, src/main/java/io/reactivex/internal/operators/OperatorWindowBoundarySupplier.java, src/main/java/io/reactivex/internal/operators/OperatorWindowTimed.java, src/main/java/io/reactivex/internal/subscribers/DisposableSubscriber.java, src/test/java/io/reactivex/internal/operators/OperatorWindowWithObservableTest.java, src/test/java/io/reactivex/internal/operators/OperatorWindowWithSizeTest.java, src/test/java/io/reactivex/internal/operators/OperatorWindowWithStartEndObservableTest.java, src/test/java/io/reactivex/internal/operators/OperatorWindowWithTimeTest.java
I had to adjust some test slightly due to the a new behavior: if one
cancels a source which is windowed, as long as the windows are active,
the source has to stay active. However, there are more subtle
possibilities that need new tests.
=> 2.x: operator test: window variants

src/main/java/io/reactivex/exceptions/CompositeException.java, src/main/java/io/reactivex/exceptions/OnCompleteFailedException.java, src/main/java/io/reactivex/exceptions/OnErrorFailedException.java, src/main/java/io/reactivex/exceptions/OnErrorNotImplementedException.java, src/main/java/io/reactivex/exceptions/UnsubscribeFailedException.java, src/main/java/io/reactivex/internal/operators/OperatorDoOnEach.java, src/main/java/io/reactivex/internal/subscribers/CancelledSubscriber.java, src/main/java/io/reactivex/subscribers/Observers.java, src/main/java/io/reactivex/subscribers/SafeSubscriber.java, src/main/java/io/reactivex/subscribers/SerializedSubscriber.java, src/main/java/io/reactivex/subscribers/Subscribers.java, src/main/java/io/reactivex/subscribers/TestSubscriber.java, src/test/java/io/reactivex/subscribers/ObserversTest.java, src/test/java/io/reactivex/subscribers/SafeObserverTest.java, src/test/java/io/reactivex/subscribers/SafeSubscriberWithPluginTest.java, src/test/java/io/reactivex/subscribers/SerializedObserverTest.java, src/test/java/io/reactivex/subscribers/SubscribersTest.java, src/test/java/io/reactivex/subscribers/TestObserverTest.java, src/test/java/io/reactivex/subscribers/TestSubscriberTest.java
I had to ignore many tests because they either test with null or throw
an exception from a Subscriber method which are not allowed with RS.
+ added Observers and Subscribers to create Observers/Subscribers with convenience.
=> 2.x: subscribers/observers tests

src/main/java/io/reactivex/Observable.java, src/main/java/io/reactivex/annotations/BackpressureKind.java, src/main/java/io/reactivex/annotations/BackpressureSupport.java, src/main/java/io/reactivex/annotations/Beta.java, src/main/java/io/reactivex/annotations/Experimental.java, src/main/java/io/reactivex/annotations/SchedulerKind.java, src/main/java/io/reactivex/annotations/SchedulerSupport.java, src/main/java/io/reactivex/disposables/RefCountDisposable.java, src/main/java/io/reactivex/internal/disposables/SetCompositeResource.java, src/main/java/io/reactivex/internal/util/OpenHashSet.java, src/test/java/io/reactivex/disposables/CompositeDisposableTest.java, src/test/java/io/reactivex/disposables/DisposablesTest.java, src/test/java/io/reactivex/disposables/MultipleAssignmentDisposableTest.java, src/test/java/io/reactivex/disposables/RefCountDisposableTest.java, src/test/java/io/reactivex/disposables/SerialDisposableTests.java
+ sorted `Observable` and added `@BackpressureSupport` and
`SchedulerSupport` annotations.
+ created `@Beta` and `@Experimental` annotations, nothing is marked
with them because I intent everything to be standard at this point.
=> 2.x: disposable unit tests + fix to RefCountDisposable behavior

src/test/java/rx/subjects/AsyncSubjectTest.java, src/test/java/rx/subjects/BehaviorSubjectTest.java, src/test/java/rx/subjects/PublishSubjectTest.java, src/test/java/rx/subjects/ReplaySubjectTest.java
... and remove the unused Mockito imports
=> test/subjects: Use statically imported never() methods

src/main/java/rx/observables/AsyncOnSubscribe.java, src/test/java/rx/observables/AsyncOnSubscribeTest.java
This includes the first functioning unit tests. This still has a few iterations to go but opening PR for review.
=> Implemented the AsyncOnSubscribe

src/perf/java/io/reactivex/InputWithIncrementingInteger.java, src/perf/java/io/reactivex/LatchedObserver.java, src/perf/java/io/reactivex/OperatorFlatMapPerf.java, src/perf/java/io/reactivex/OperatorMergePerf.java
Ported the two perf tests to evaluate 2.x throughput.
My primary suspect for the extra overhead are the atomics of queue-drain. The 1.x uses a synchronized-based emitter-loop which is elided by the JIT compiler but atomics can't be elided. As I mentioned before, synchronized works better for light-to-none asynchronous use whereas atomics work better for asynchronous use.
Also quote from #3157
> Exceptions that do not require a :+1: would be:
>
>javadoc changes
>unit test additions or refactoring
>**perf test additions, fixes or refactoring**
>grammatical and presentation fixes to README, CONTRIBUTING, and other such metadata files
=> 2.x: perf checks for flatMap and merge

DESIGN.md
How to create and destroy streams.
The wording of this can become much better once agreement occurs in https://github.com/ReactiveX/RxJava/pull/3348/files
The intent of this is:
1) Specify how to create streams (Observable/Flowable) of the various flavors, and account for flow control.
2) Evolve towards what the creation/generation APIs are
3) Specify that it is not the responsibility of the final Subscriber to call unsubscribe/cancel upstream
=> 2.x Design: Creation/Destruction

src/perf/java/io/reactivex/InputWithIncrementingInteger.java, src/perf/java/io/reactivex/LatchedObserver.java, src/perf/java/io/reactivex/OperatorFlatMapPerf.java, src/perf/java/io/reactivex/OperatorMergePerf.java, src/perf/java/io/reactivex/RangePerf.java
Benchmarks synchronous, asynchronous (where the emission can hop onto the receiver thread) and strictly-pipelined (the emitter and receiver are on different threads). Results on i7 4790, Windows 7 x64, Java 1.8u60:
```
Benchmark                (times)   Mode  Cnt         Score        Error  Units
RangePerf.rangeAsync           1  thrpt    5    135410,552 ?  20521,908  ops/s
RangePerf.rangeAsync        1000  thrpt    5     25634,730 ?    284,526  ops/s
RangePerf.rangeAsync     1000000  thrpt    5        59,073 ?      1,154  ops/s
RangePerf.rangePipeline        1  thrpt    5     98895,846 ?  11398,363  ops/s
RangePerf.rangePipeline     1000  thrpt    5     16233,903 ?    741,712  ops/s
RangePerf.rangePipeline  1000000  thrpt    5        10,621 ?      2,606  ops/s
RangePerf.rangeSync …
```
=> 2.x: range perf + added missing header.

src/perf/java/io/reactivex/OperatorFlatMapPerf.java, src/perf/java/io/reactivex/OperatorMergePerf.java, src/perf/java/io/reactivex/RangePerf.java
I've noticed that the `times = 1` async range sometimes produces double the throughput without any change to the underlying structure and I've figured out it is because how my operation system wakes up the await in the benchmark. I switched the tests to spin-loop and now I get a consistent and higher value than before:
There are a few light-greens and a few light-reds which I attribute to other fluctuating factors on my computer.
In addition, I've experimented with two optimizations: one for observing a scalar value on a different thread and one where the `OperatorObserveOn` is turned into a `PublisherObserveOn` to save on the allocation of a `PublisherLift`. The scalar optimization ended up being slower by 15% for some reason I don't understand and the `PublishObserveOn` had no impact on …
=> 2.x: perf change wait to spin-loop for short async benchmarks

DESIGN.md
Clarification of `Subject` that affects implementation. 
Related to discussion in https://github.com/ReactiveX/RxJava/pull/3345.
=> 2.x Design: Subject

DESIGN.md
Proposed separation of `Observable` and `Flowable` along with description of each and their characteristics.
=> 2.x Design: Flowable/Observable

src/main/java/rx/internal/operators/OnSubscribeRedo.java, src/main/java/rx/internal/operators/OperatorReplay.java, src/main/java/rx/schedulers/TestScheduler.java
Believe I'm removing some unnecessary unboxing calls, but please correct me if I'm wrong.
=> Lint fixes for unnecessary unboxing

src/main/java/io/reactivex/internal/operators/OperatorTake.java, src/test/java/io/reactivex/internal/operators/OperatorTakeTest.java, src/test/java/io/reactivex/internal/operators/nbp/NbpOperatorTakeTest.java
Discovered by @mgp in #3346 and using his supplied fix. I've already
applied it to NbpObservable's take this Monday so all that's left was
the unit test.
=> 2.x: fix take() reentrancy problem.

src/main/java/rx/observables/AsyncOnSubscribe.java, src/test/java/rx/observables/AsyncOnSubscribeTest.java
There were several problems with the operator:
- The first 2 requests were always `Long.MAX_VALUE` no matter what the child requested.
- There was a race-condition and memory leak when tracking the generated `Observable`s.
- Both the individual generated `Observable`s and the main concatenation could overflow the internal buffers and had to be defensively-buffered.
- If a request was responded with a generated `Observable` that delivered less than this requested amount, the child ended up hanging.
- The concatenation didn't know about the number of values it should deliver in aggregate and might have delivered more or less, causing `MissingBackpressureException` or hangs.
- Exception thrown from the `generateState` is now delivered to the child immediately.
As I see, the usage is as …
=> Fix to a bunch of bugs and issues with AsyncOnSubscribe

src/main/java/rx/internal/operators/OperatorTake.java, src/test/java/rx/internal/operators/OperatorTakeTest.java
Fixes the bug reported in  #3346. (I've done this for 1.x as well since the original poster disappeared).
=> Fix for take() reentrancy bug.

src/main/java/io/reactivex/internal/queue/SpscLinkedArrayQueue.java
Discovered while debugging #3381. Confirmed with JCTools in https://github.com/JCTools/JCTools/pull/80
=> 2.x: fix SpscLinkedArrayQueue leaves 1 slot null just before growing

src/perf/java/io/reactivex/RxVsStreamPerf.java
This benchmark compares the overhead of backpressured range, non-backpressured range, streamed range and parallel-streamed range. Run on i7 4770K, Windows 7 x64, Java 1.8u60.
=> 2.x: perf comparing Observable, NbpObservable, Stream and ParallelStream

src/main/java/rx/subjects/AsyncSubject.java, src/main/java/rx/subjects/PublishSubject.java, src/main/java/rx/subjects/ReplaySubject.java, src/main/java/rx/subjects/SerializedSubject.java, src/main/java/rx/subjects/Subject.java
Squashed commits:
[c6e43fc] 1.0.15. Beta/Deprecation of Subject state peeking methods.
This should give users one release to prepare for the class structure
changes.
=> pull back the Experimental/Beta of the changes until 1.1.x (+1 squashed commit)

src/main/java/rx/Observable.java
This is one of the many 1.1.0 promotion related pull requests. There is a split decision on the operator `Observable.doOnRequest(Action1)`. A majority of core committers have voted to promote this operator from `@Beta` to public. There is currently a minority is support for removing the convenience method on `Observable` or demoting it to `@Experimental`. Instead users would lift the underlying operator `obs.lift(new OperatorDoOnRequest<T>(onRequest))`. In this pull request I have taken the more conservative approach and expect that comments will guide our decisions. 
- the `doOnRequest` use case is to debug back-pressure use cases and as such should not pollute the public operator namespace. 
- the existence of this operator may mislead and confuse users. it could be misinterpreted and …
=> 1.1.0 - Changed Observable.doOnRequest(Action1) to @Experimental from @Beta

src/main/java/rx/Observable.java, src/main/java/rx/internal/operators/OperatorDoOnEach.java, src/test/java/rx/internal/operators/OperatorDoOnEachTest.java
This came up in a [Stackoverflow](http://stackoverflow.com/questions/32889008/do-operators-instead-of-a-whole-subscriber) answer. If the `doOnError`'s callback or the `doOnEach`'s `onError` method throws, any non-fatal exception replaced the original error which got lost. This PR will wrap them both into a `CompositeException`.
2.x note: since Java 8 supports `addSuppressed` all callbacks in this situation either attach to the original exception or the original exception is attached to the callback's exception.
=> DoOnEach: report both original exception and callback exception.

src/main/java/rx/internal/operators/CachedObservable.java
Fewer methods — happier Android Developers :)
=> Remove unused private method from CachedObservable and make "state" final

src/main/java/rx/internal/operators/BlockingOperatorToFuture.java
Not very important since `onError` should be called once, but anyway it's `AtomicReference` and we need to store the value returned from `get()` locally.
P.S. I don't use `Future`s, just found this piece of code.
=> Safer error handling in BlockingOperatorToFuture

src/main/java/rx/internal/operators/OperatorGroupBy.java
Addresses #3067 - Removes a redundant `onStart` implementation in `OperatorGroupBy`.
=> Remove redundant onStart implementation in OperatorGroupBy

src/main/java/rx/Observable.java, src/main/java/rx/internal/operators/OperatorEagerConcatMap.java, src/main/java/rx/internal/util/atomic/SpscLinkedArrayQueue.java, src/test/java/rx/internal/operators/OperatorEagerConcatMapTest.java
=> Eager ConcatMap

src/main/java/rx/internal/operators/BlockingOperatorToIterator.java, src/test/java/rx/internal/operators/BlockingOperatorToIteratorTest.java
The iterator created by `BlockingOperator#getIterator()` doesn't exert backpressure, which causes code like this to never terminate/run out of memory
```java
Observable.from(new Iterable<Integer>() {
@Override
public Iterator<Integer> iterator() {
return new Iterator<Integer>() {
@Override
public boolean hasNext() {
return true;
}
@Override
public Integer next() {
return 1;
}
};
}
}).toBlocking().getIterator().next();
```
This PR adds the appropriate `request` calls so that this works. I had to combine the implementations of `Subscriber` and `Iterator` into a single class to get access to `request()`.
=> Make BlockingOperatorToIterator exert backpressure.

src/main/java/rx/observables/BlockingObservable.java, src/test/java/rx/observables/BlockingObservableTest.java
Mirroring some `Observable.subscribe` methods on `BlockingObservable`.
Related discussion: #3063.
=> Blocking subscribe methods for convenience

src/main/java/rx/Single.java, src/test/java/rx/SingleTest.java
Second part of #3154.
@akarnokd I'd like to reuse `Observable.fromCallable()` but didn't find apropriate way to do it: `Observable.fromCallable().toSingle()` is not best option, if you have some thoughts on this — please share them.
=> Add Single.fromCallable()

src/main/java/rx/Single.java, src/test/java/rx/SingleTest.java
=> Add Single.doOnSuccess()

src/main/java/rx/Observable.java, src/main/java/rx/Single.java, src/main/java/rx/internal/operators/OperatorDelay.java, src/test/java/rx/SingleTest.java
Adds the `delay(long delay, TimeUnit unit, Scheduler
scheduler)` and 'delay(long delay, TimeUnit unit)` operators to
`rx.Single`.
Includes (in a separate commit) a refactor of `OperatorDelay`. As far as I can tell, the `source` field isn't used at all - by removing it, I was able to reuse `OperatorDelay` in `rx.Single` to implement the delay operator pretty easily.
=> Single delay

src/main/java/rx/subscriptions/CompositeSubscription.java
Current state of `CompositeSubscription`'s javadoc — totally misleading :smile: 
Every time we need to store some subscriptions in it then clear them and leave `CompositeSubscription` in an operable state we have to read its sources because its actual behavior is not consistent with the javadoc.
`CompositeSubscription.clear()` leaves `CompositeSubscription` in operable state, when on the other hand `CompositeSubscription.unsubscribe()` sets `isUnsubscribed = true` and `CompositeSubscription` is not able to manage new subscriptions.
=> Clarify contracts of CompositeSubscription in its javadoc

src/main/java/rx/exceptions/MissingBackpressureException.java, src/main/java/rx/exceptions/OnCompletedFailedException.java, src/main/java/rx/exceptions/OnErrorFailedException.java, src/main/java/rx/exceptions/OnErrorNotImplementedException.java, src/main/java/rx/exceptions/OnErrorThrowable.java, src/main/java/rx/exceptions/UnsubscribeFailedException.java, src/test/java/rx/exceptions/ExceptionsNullTest.java
There seems to be a tendency to send `null` values through `onError` which eventually causes repeated failures. This PR converts these `null` values into `NullPointerException`s so the error origin is can be discovered and prevents the XXXExceptions from throwing NPEs in their constructors as well.
I've also added some missing javadoc.
=> Better null tolerance in rx.exceptions.*Exception classes.

src/main/java/rx/Observable.java, src/main/java/rx/exceptions/Exceptions.java, src/test/java/rx/exceptions/ExceptionsTest.java
https://github.com/ReactiveX/RxJava/issues/2998
=> OnErrorFailedException fix

src/perf/java/rx/operators/FlatMapRangePerf.java
The current baseline on i7 4770K, Windows 7 x64, Java 8u66:
```
Benchmark           (times)   Mode   Samples        Score  Score error    Units
rangeFlatMapJust          1  thrpt         5 24242025,899  2299703,654    ops/s
rangeFlatMapJust         10  thrpt         5  2536987,139   153629,364    ops/s
rangeFlatMapJust       1000  thrpt         5    54154,325     4014,598    ops/s
rangeFlatMapJust    1000000  thrpt         5       48,638        7,591    ops/s
rangeFlatMapRange         1  thrpt         5  9331777,291   531241,251    ops/s
rangeFlatMapRange        10  thrpt         5   388606,708    22875,097    ops/s
rangeFlatMapRange      1000  thrpt         5     4164,424      266,850    ops/s
rangeFlatMapRange   1000000  thrpt         5        4,354        0,575    ops/s
```
=> 1.x: benchmark range + flatMap throughput.

src/perf/java/rx/SubscribingPerf.java
This PR adds a perf test that measures what it takes to subscribe to a
non-backpressured and backpressured source and what is the effect of the
mini-arbitration inside Subscriber.
This should enable investigations into why generally 1.x subscriptions have more overhead than 2.x.
Benchmark (i7 4770K, Windows 7 x64, Java 8u66):
Direct overrides `setProducer` and requests directly. Started requests in the `onStart` method and Usual requests in the constructor.
=> 1.x: perf benchmark for the cost of subscribing

src/perf/java/rx/SubscribingPerf.java
Note: this doesn't change any main class, just a perf class.
- Two of the tests used the wrong subscriber type.
- The benchmark layout allowed stack allocation instead of heap allocation and thus showing less overhead than expected. By letting consuming the `Subscriber`s via blackhole, this JIT optimization is negated as it should be.
- Added a benchmark which should help verify the overhead of checking `isUnsubscribed` within range in #3479 because I suspect that will get worse there.
Benchmark values: (i7 **4790**, Windows 7 x64, Java 8u66):
=> 1.x: update and bugfix to SubscribingPerf

CHANGES.md
Can get two more :+1: from the committers.
=> Begin the steps to release 1.0.15

src/main/java/rx/internal/operators/OperatorScan.java, src/test/java/rx/internal/operators/OperatorScanTest.java
I forgot a NotificationLite conversion in the constructor. Note that
there were no tests verifying null behavior at all.
=> 1.x: fix scan() not accepting a null initial value

src/main/java/rx/Observable.java, src/main/java/rx/Single.java, src/test/java/rx/exceptions/ExceptionsTest.java
Reviewed all usages of `OnErrorNotImplementedException` and fixed issues similar to #3455.
=> 1.x: Fix other places that may swallow OnErrorFailedException

src/perf/java/rx/ScalarJustPerf.java
This add a perf class that benchmarks just() and optimizations it allows. I'll use this as a baseline to compare the upcoming backpressure-aware version against.
Benchmark results of throughput (ops/s) (i7 4790, Windows 7 x64, Java 8u66):
=> 1.x: benchmark just() and its optimizations.

src/main/java/rx/internal/operators/BlockingOperatorNext.java, src/main/java/rx/internal/operators/OnSubscribeRedo.java, src/main/java/rx/internal/operators/OperatorBufferWithSize.java, src/main/java/rx/internal/operators/OperatorConcat.java, src/main/java/rx/internal/operators/OperatorWindowWithSize.java, src/main/java/rx/internal/operators/OperatorWithLatestFrom.java, src/main/java/rx/internal/schedulers/EventLoopsScheduler.java, src/main/java/rx/internal/schedulers/GenericScheduledExecutorService.java, src/main/java/rx/internal/util/SubscriptionRandomList.java, src/main/java/rx/observables/AbstractOnSubscribe.java, src/main/java/rx/observables/AsyncOnSubscribe.java, src/main/java/rx/subjects/ReplaySubject.java, src/main/java/rx/subscriptions/RefCountSubscription.java, src/test/java/rx/CovarianceTest.java, src/test/java/rx/internal/operators/OnSubscribeCombineLatestTest.java, src/test/java/rx/internal/operators/OnSubscribeUsingTest.java, src/test/java/rx/internal/operators/OperatorConcatTest.java, src/test/java/rx/internal/operators/OperatorGroupByTest.java, src/test/java/rx/internal/operators/OperatorMapTest.java, src/test/java/rx/internal/operators/OperatorMergeTest.java, src/test/java/rx/internal/operators/OperatorPublishTest.java, src/test/java/rx/internal/operators/OperatorSerializeTest.java, src/test/java/rx/internal/operators/OperatorTakeUntilPredicateTest.java, src/test/java/rx/internal/operators/OperatorZipTest.java, src/test/java/rx/internal/util/IndexedRingBufferTest.java, src/test/java/rx/observers/SerializedObserverTest.java
Nothing that could change logic or application flow, just minor refactors to be consistent with good practices and clean code.
To sum up changes:
- Simplified some conditions
- Changed small l to L in long number, as l tends to look like 1 and might confuse
- Removed "return" statements where those are not necessary (last instruction in function)
- Inlined returns where there were no need for creating new variable (easier to read)
- Deleted unnecessary colons
=> Some code clean ups.

src/main/java/rx/observers/SafeSubscriber.java
The documentation was wrong in two points: unsubscription doesn't call` onCompleted` and unsubscription doesn't directly prevent delivery of `onXXX` events since the implementation doesn't even check isUnsubscribed: (it is the responsibility of the upstream to do that).
Related issue: #3059.
=> 1.x: fix SafeSubscriber documentation regarding unsubscribe

src/main/java/rx/internal/operators/OperatorEagerConcatMap.java, src/main/java/rx/internal/util/atomic/AtomicReferenceArrayQueue.java, src/main/java/rx/internal/util/atomic/SpscAtomicArrayQueue.java
I forgot to add the choice because 2.x `SpscArrayQueue` doesn't use Unsafe. I copied the `SpscAtomicArrayQueue` from #3169 and I hope it won't conflict. This is the drawback of long trail of unmerged fixes and enhancements...
Reported in #3508 .
=> 1.x: eager concatMap to choose safe or unsafe queue based on platform.

src/main/java/rx/internal/operators/OperatorMerge.java, src/main/java/rx/internal/util/atomic/AtomicReferenceArrayQueue.java, src/main/java/rx/internal/util/atomic/SpscAtomicArrayQueue.java, src/main/java/rx/internal/util/atomic/SpscExactAtomicArrayQueue.java, src/main/java/rx/internal/util/atomic/SpscUnboundedAtomicArrayQueue.java, src/perf/java/rx/operators/FlatMapPerf.java, src/test/java/rx/internal/operators/OperatorMergeTest.java, src/test/java/rx/internal/util/JCToolsQueueTests.java
Resolves #3156 
Note that since the default merge operation is unbounded, this change could lead to an excessive memory usage when flatMapping fast sources. Note that the pre 1.0.13 version did this albeit on a slighty slower path.
The change also affects the scalar optimization as well. Pre 1.0.13 implicitly limited the concurrency level to RxRingBuffer.SIZE when scalars were received. This version now fills the queue up to the concurrency level.
For 2.0, I suggest having a bounded behavior by default and require the developer to specify Integer.MAX_VALUE to go for the unbounded behavior so he/she knows about the consequences.
=> Merge can now operate in horizontally unbounded mode.

src/main/java/rx/Single.java, src/main/java/rx/internal/util/BlockingUtils.java, src/main/java/rx/observables/BlockingObservable.java, src/main/java/rx/singles/BlockingSingle.java, src/test/java/rx/SingleTest.java, src/test/java/rx/internal/util/BlockingUtilsTest.java, src/test/java/rx/singles/BlockingSingleTest.java
Adds BlockingSingle (issue #3252), the blocking version of rx.Single.
BlockingSingle has the following methods:
- `from(Single)` -- factory method for creating a `BlockingSingle` from a
`Single`
- `value()` -- returns the value emitted from the Single
- `toFuture()` -- returns a `java.util.concurrent.Future`
Couldn't actually think of any other useful operations to perform on `BlockingSingle` - in comparison to `BlockingObservable`, there's not much to this class (at the moment).
=> 1.x: Implements BlockingSingle

src/test/java/rx/observables/SyncOnSubscribeTest.java
The test failed on Travis and locally if my machine was under heavy load without interacting with the mock. This change gives more time in the inner await and reports the exception instead of itself throwing.
=> 1.x: SyncOnSubscribeTest.testConcurrentRequests give more time.

src/main/java/rx/plugins/RxJavaPlugins.java, src/test/java/rx/plugins/RxJavaPluginsTest.java
This adds a new pattern and lookup method that let's the developer specify the custom plugins with shorter system property keys. Android is quite restrictive and allows only 31 characters.
The new pattern splits the target simple class name and its implementation into two separate system properties:
```
rxjava.plugin.1.class=SimpleClassName
rxjava.plugin.1.impl=path.to.impl.Class
```
The index tag (`1`) can be any string of your chosing:
```
rxjava.plugin.mykey.class=SimpleClassName
rxjava.plugin.mykey.impl=path.to.impl.Class
```
but make sure they are paired, otherwise nothing will happen.
If there are multiple `class` entries with the same `SimpleClassName` one of them will be chosen (depending on the walk order in `java.util.Properties`).
Related issue #2835.
=> 1.x: add shorter RxJavaPlugin class lookup approach.

src/main/java/rx/internal/operators/OperatorFinally.java, src/test/java/rx/internal/operators/OperatorFinallyTest.java
Part of #3435.
Personally, I'd also add same test to `Observable.finallyDo()` and `Single.finallyDo()` because there are no guarantees that in future they will use exact same operator as implementation and this contract is more a contract of `Observable.finallyDo()` and `Single.finallyDo()`.
=> 1.x: Add action != null check in OperatorFinally

src/main/java/rx/internal/operators/OperatorZipIterable.java, src/test/java/rx/internal/operators/OperatorZipIterableTest.java
`delay` delays the `onCompleted` event and `unsubscribe` is called when `onCompleted` finishes. So if we put a `o.zipWith(Iterable, func)` before `delay`, such as `o.zipWith(Iterable, func).delay(...)`, `o` may keep emitting items even if `zipWith` emits an `onCompleted` event. This PR just fixed `OperatorZipIterable` to handle this case.
Fixes https://github.com/ReactiveX/RxScala/issues/180
=> 1.x: Avoid to call next when Iterator is drained

src/test/java/rx/internal/util/BlockingUtilsTest.java
For some strange reason, the interrupted flag is sometimes still set when the next JUnit test method runs and `await` will throw immediately.
=> 1.x: BlockingUtils test: clear interrupted flag before/after

src/main/java/rx/internal/operators/OperatorWindowWithObservable.java, src/main/java/rx/internal/operators/OperatorWindowWithObservableFactory.java, src/main/java/rx/internal/operators/OperatorWindowWithSize.java, src/main/java/rx/internal/operators/OperatorWindowWithStartEndObservable.java, src/main/java/rx/internal/operators/OperatorWindowWithTime.java, src/main/java/rx/internal/operators/UnicastSubject.java, src/main/java/rx/internal/util/atomic/SpscUnboundedAtomicArrayQueue.java, src/main/java/rx/internal/util/unsafe/QueueProgressIndicators.java, src/main/java/rx/internal/util/unsafe/SpscUnboundedArrayQueue.java, src/test/java/rx/internal/operators/BufferUntilSubscriberTest.java, src/test/java/rx/internal/operators/OperatorConcatTest.java, src/test/java/rx/internal/operators/OperatorWindowWithObservableTest.java
=> Window operators now support backpressure in the inner observable.

src/test/java/rx/observables/SyncOnSubscribeTest.java
The test checks if onUnSubscribe is called but that happens after
onCompleted is sent and as such, may run concurrently with the main
thread where the mock is verified. The change switches to CountDownLatch
to properly await the call to onUnsubscribe.
=> 1.x: Fix SyncOnSubscribeTest.testConcurrentRequests non-determinism

src/main/java/rx/internal/operators/OperatorScan.java, src/main/java/rx/internal/producers/ProducerObserverArbiter.java, src/test/java/rx/internal/operators/OperatorScanTest.java, src/test/java/rx/internal/producers/ProducersTest.java
It turns out serializing `request()` calls with regular `onXXX()` calls can be problematic because a `request()` may trigger an emission of events which then end up being queued (since `emitting == true`). If the request is large and the queue otherwise unbounded, this will likely cause OOME.
In case of `scan`, the fix was to make the missing request accounting and arrival of the `Producer` independent of the event's emitter loop; there is no need for them to be serialized in respect to each other.
In case of the `ProducerObserverArbiter` where the request accounting and producer swapping has to be serialized with the value emission, the solution is to call `request()` outside the emitter-loop.
There shouldn't be any issue with 2.x `scan()` because in 2.x, scan receives the `Subscription` …
=> 1.x: make scan's delayed Producer independent of event serialization

src/main/java/rx/internal/operators/OperatorGroupBy.java, src/test/java/rx/internal/operators/OperatorGroupByTest.java, src/test/java/rx/internal/operators/OperatorRetryTest.java
This is a backport of the 2.x GroupBy operator which solves #3425.
One unit test in OperatorRetryTest had to be altered a bit. I believe
the original code relied on a GroupBy behavior which caused the bug in
#3425.
=> GroupBy backpressure fix

src/main/java/rx/Completable.java, src/main/java/rx/internal/operators/CompletableOnSubscribeConcat.java, src/main/java/rx/internal/operators/CompletableOnSubscribeConcatArray.java, src/main/java/rx/internal/operators/CompletableOnSubscribeConcatIterable.java, src/main/java/rx/internal/operators/CompletableOnSubscribeMerge.java, src/main/java/rx/internal/operators/CompletableOnSubscribeMergeArray.java, src/main/java/rx/internal/operators/CompletableOnSubscribeMergeDelayErrorArray.java, src/main/java/rx/internal/operators/CompletableOnSubscribeMergeDelayErrorIterable.java, src/main/java/rx/internal/operators/CompletableOnSubscribeMergeIterable.java, src/main/java/rx/internal/operators/CompletableOnSubscribeTimeout.java, src/test/java/rx/CompletableTest.java
=> 1.x: Completable class to support valueless event composition + tests

src/main/java/rx/Observable.java, src/main/java/rx/internal/operators/OperatorBufferWithSingleObservable.java, src/main/java/rx/internal/operators/OperatorBufferWithSize.java, src/main/java/rx/internal/operators/OperatorBufferWithStartEndObservable.java, src/main/java/rx/internal/operators/OperatorBufferWithTime.java
=> Corrected buffer operator onError behaviour documentation

src/main/java/rx/internal/operators/OperatorToMap.java, src/main/java/rx/internal/operators/OperatorToMultimap.java, src/test/java/rx/internal/operators/OperatorToMapTest.java, src/test/java/rx/internal/operators/OperatorToMultimapTest.java
This PR adds the usual try-catch around callback invocations in `toMap`
and `toMultimap`.
Related #3555.
=> 1.x: fix toMap and toMultimap not handling exceptions of the callbacks

src/main/java/rx/Single.java, src/test/java/rx/SingleTest.java
As promised, adding more operators to `Single`. This one is very useful for releasing resources if task can be cancelled externally via `subscription.unsubscribe()` and subscriber may not receive the result.
=> Add Single.doOnUnsubscribe()

src/main/java/rx/Observable.java, src/main/java/rx/internal/operators/OnSubscribeDelaySubscriptionOther.java, src/test/java/rx/internal/operators/OnSubscribeDelaySubscriptionOtherTest.java
Requested in #3445.
This is an efficient implementation as it avoids allocating the lifter object, doesn't require a function wrapper and doesn't use producer arbitration.
(Bonus points to those who can recognize the similarities with #3446).
=> 1.x: DelaySubscription with a plain other Observable.

src/main/java/rx/Single.java, src/test/java/rx/SingleTest.java
@akarnokd I've found a problem with `null` action, I'll create separate issue about this soon.
=> Add Single.finallyDo()

src/main/java/rx/Observable.java, src/main/java/rx/internal/operators/OperatorDoAfterTerminate.java, src/test/java/rx/internal/operators/OperatorDoAfterTerminateTest.java, src/test/java/rx/internal/operators/OperatorObserveOnTest.java
=> Deprecate Observable.finallyDo() and add Observable.doAfterTerminate() instead

src/main/java/rx/Completable.java, src/test/java/rx/CompletableTest.java
Renames as part of #3434 for the recently added Completable.
=> Renamed Completable#finallyDo to #doAfterTerminate

src/main/java/rx/Single.java
There was a cross dependency between two PRs yielding a broken
compilation in main.
=> 1.x: fix renamed operator in Single.

src/test/java/rx/subjects/BehaviorSubjectTest.java
Advantage is that we verify that there's no interaction at all so also something that we might not expect is not going to happen.
=> Replace never() calls in BehaviorSubjectTest with verifyNoMoreInteractions

src/main/java/rx/Observable.java, src/test/java/rx/ObservableTests.java
~~The parameter is a capacity hint, but more frequently confused with a
buffer size like replay(int) than it is correctly understood. It also
offers no guarantees, only the weak hope of optimization.~~
The parameter is a capacity hint, but more frequently confused with a buffer size like replay(int) than it is correctly understood. It also offers no guarantees, only the weak hope of optimization.
This change renames the method, deprecating the old name. It also adds javadoc calling out that the parameter is not a bound and referencing replay(int).autoConnect() as a way to achieve that behavior.
=> 1.x: Rename cache(int) to cacheWithInitialCapacity(int)

src/main/java/rx/internal/operators/OperatorReplay.java, src/test/java/rx/internal/operators/OperatorReplayTest.java
Fixes the bug reported in #3452.
The fix involves 3 changes:
- First, each node in the bounded buffer receives an incrementing index whenever they are created. The root node starts with 0, the first value's index will be 1 and so on.
- In the replay logic, the very first time the current node is captured, the node's index is added to the totalRequested amount of the subscriber. Since this is always one less than the max requested that far, there is no point in calling `manageRequests()` at this point.
- Third, the pinning of the current node has to happen before the child requests, otherwise the difference would manifest before the compensation and some elements may get missed.
In addition, there was a missing `r--` in the emission loop and thus the operator could have overflown its child …
=> 1.x: fix: bounded replay() not requesting enough for latecommers

src/main/java/rx/Scheduler.java, src/test/java/rx/SchedulerWorkerTest.java
There is a problem, reported in #3461 and #2943, in which if the system clock drifts, the periodic calculation inside Scheduler.Worker gets off and either taking a longer time for the next invocation of the task or doing "catching-up" with all the lost invocations.
The solution checks the wall clock difference between the last run and the current run and if it went back or forward significantly, it rebases the timer period and schedules the next execution relative to now.
If the clock goes back, the original code scheduled the next invocation way into the future. This PR will schedule it after the period.
If the clock goes forward, the original code scheduled executions for all the missed time between the last run and the new time immediately, yielding a bunch of 0 delays. This PR will …
=> 1.x: compensation for significant clock drifts in schedulePeriodically

src/main/java/rx/Observable.java, src/main/java/rx/internal/operators/OnSubscribeFromArray.java, src/perf/java/rx/operators/FromComparison.java, src/test/java/rx/internal/operators/OnSubscribeFromArrayTest.java
This specialized OnSubscribe performs ~33% better on longer streams.
Benchmark comparison (i7 4770K, Windows 7 x64, Java 8u66):
The `slowpath` requests the available amount + 1 to trigger a slow path, `slowpath2` requests in batches of 128 and replenishes only after all were received.
=> 1.x: add a source OnSubscribe which works from an array directly

src/main/java/rx/internal/schedulers/GenericScheduledExecutorService.java
The static `GenericScheduledExecutorService.None` should be initialized before creating any GenericScheduledExecutorService instance. Although the previous codes happen to work, it's sill worth to fix it.
=> Fix the initialization order in GenericScheduledExecutorService

src/main/java/rx/Completable.java, src/test/java/rx/CompletableTest.java
I expect some discussion around the method name.
=> Implemented Completable#andThen(Observable)

src/main/java/rx/Observable.java
It subscribes to the upstream `Observable` on the emitting thread of the other `Observable` obtained from the `Func0`.
=> delaySubscription(Func0) does not use a scheduler

src/main/java/io/reactivex/observables/BlockingObservable.java, src/main/java/io/reactivex/observables/nbp/NbpBlockingObservable.java
get() throws NSE when absent and orElse(T) returns the provided value when absent.
=> 2.x: Remove duplication of Optional API behavior.

src/test/java/rx/subjects/PublishSubjectTest.java
This PR complete the never assert in PublishSubjectTest.
=> 1.x: add never test for  PublishSubjectTest

src/main/java/rx/Observable.java
As discussed in #3411, some clarification of the behaviour of `groupBy` looks necessary re its behaviour when the `GroupedObservable` terminates early (for example has `.first()` applied to it). See also  #3581.
I also took the liberty of recommending `ignoreElements` instead of `take(0)` for the section in the javadoc that recommends how to ignore emissions because the `take(0)` approach would have more overhead (every emission from source would prompt the emission of a new `GroupedObservable`) than the `ignoreElements` approach.
Once this is accepted I'll look to submit a PR with `groupByOnce` (mentioned in #3411).
=> clarify behaviour of groupBy in javadoc

src/main/java/rx/Completable.java, src/test/java/rx/CompletableTest.java
This PR fixes the cases when the Completable factory throws an exception
or returns null and the resource is not disposed before reporting error
to the subscriber.
=> 1.x: fix Completable.using not disposing the resource if the factory crashes during the subscription phase.

src/main/java/rx/internal/operators/OperatorEagerConcatMap.java, src/test/java/rx/internal/operators/OperatorEagerConcatMapTest.java
The operator was not allowing `null`s in the inner Observables.
Related: #3629.
=> 1.x: ConcatMapEager allow nulls from inner Observables.

src/main/java/rx/Single.java, src/main/java/rx/internal/operators/OnSubscribeFromCallable.java, src/main/java/rx/internal/operators/OperatorScan.java, src/main/java/rx/internal/operators/OperatorToMap.java, src/main/java/rx/internal/operators/OperatorToMultimap.java, src/main/java/rx/internal/operators/UnicastSubject.java, src/main/java/rx/observers/SafeSubscriber.java, src/main/java/rx/observers/SerializedObserver.java
This PR simplifies error handling by making use of existing `Exceptions.throwOrError` overloads.
A number of classes are touched by this one PR but I'm assuming review will be easy enough that merge can happen soon.
=> use Exceptions.throwOrError to simplify error handling

src/perf/java/rx/operators/RedoPerf.java
This PR adds a perf test to measure the redo-based operators: repeat, repeatWhen, retry, retryWhen.
Results (Intel Celeron 1005M, Windows 7 x64, Java 8u72):
```
Benchmark                     (params)        Score  Score error
r.o.RedoPerf.baseline              1,1  9507538,496   384265,883
r.o.RedoPerf.baseline           1,1000   127236,123     6322,513
r.o.RedoPerf.baseline        1,1000000      131,491        7,443
r.o.RedoPerf.baseline           1000,1   126830,429     8161,593
r.o.RedoPerf.baseline        1000,1000      130,795        8,571
r.o.RedoPerf.baseline        1000000,1      130,097        0,936
r.o.RedoPerf.repeatCounted         1,1   473245,445    16574,938
r.o.RedoPerf.repeatCounted      1,1000     2039,161       64,254
r.o.RedoPerf.repeatCounted   1,1000000        2,304 …
```
=> 1.x: redo performance checker

src/main/java/rx/Single.java, src/test/java/rx/SingleTest.java
=> 1.x: No more need to convert Singles to Observables for Single.zip()

src/main/java/rx/internal/operators/OperatorOnBackpressureDrop.java, src/test/java/rx/internal/operators/OperatorOnBackpressureDropTest.java
`onDrop.call()`  was not wrapped in an appropriate try catch to prevent the error from being reported from an upstream operator.
This PR includes a unit test that failed on the original code.
=> fix error handling in onBackpressureDrop

src/main/java/rx/internal/operators/OperatorSkipWhile.java, src/test/java/rx/internal/operators/OperatorSkipWhileTest.java
A non-fatal exception thrown by `predicate.call()` in `OperatorSkipWhile` could result in the error being reported by an upstream operator. This PR ensures that the error is reported by the operator in which it occurs.
I've added a unit test for this scenario that failed with the original code, and a couple of other tests.
There are a few more of these floating around that I'll submit PRs for as well.
=> handle predicate exceptions properly in skipWhile

src/main/java/rx/internal/operators/OperatorDistinctUntilChanged.java, src/test/java/rx/internal/operators/OperatorDistinctUntilChangedTest.java
As per #3637, `keySelector.call()` was not wrapped in an appropriate try catch to prevent the error from being reported from an upstream operator.
This PR includes a unit test that failed on the original code.
=> fix error handling in OperatorDistinctUntilChanged

src/main/java/rx/internal/operators/OperatorOnBackpressureBuffer.java, src/test/java/rx/internal/operators/OperatorOnBackpressureBufferTest.java
`onOverflow.call()`  was not wrapped in an appropriate try catch to prevent the error from being reported from an upstream operator.
This PR includes a unit test that failed on the original code.
=> fix error handling in onBackpressureBuffer

build.gradle, src/perf/java/rx/operators/ZipPerf.java
Performance measurement of `zip` and upgrade to JMH 1.11.3.
Results (Intel Celeron 1005M, Windows 7 x64, Java 8u72):
Overall throughput values:
Comparing fully sync and fully async dual sources:
Comparing when either the first or the second is an async source:
So the order of sources matter, having the async first allows it to start early and not after the synchronous source completes its prefetch run.
=> 1.x: zip performance measure

src/perf/java/rx/SingleSourcePerf.java
Benchmark `Single`'s behavior with `flatMap`, `subscribeOn` and `observeOn`.
Results: (i7 4790, Windows 7 x64, Java 8u72)
```
Benchmark                   Score       Error  Units
direct                9054864,731  189403,130  ops/s
flatmap               2761060,187   40953,148  ops/s
flatmapConst          2763238,776   34372,376  ops/s
observeOn              300489,044   27461,361  ops/s
observeOnExec          333838,535    9098,275  ops/s
observeOnFJ            402261,384    9467,060  ops/s
observeOnSchExec       342714,377    8624,188  ops/s
subscribeOn            311487,902    8986,858  ops/s
subscribeOnExec        257315,361   29967,833  ops/s
subscribeOnFJ          383189,863   12596,397  ops/s
subscribeOnSchExec     290880,185   45773,862  ops/s
```
Here is a side-by-side comparison …
=> 1.x: Single performance measurements

src/main/java/rx/observables/SyncOnSubscribe.java, src/test/java/rx/observables/SyncOnSubscribeTest.java
Discovered in a [stackoverflow](http://stackoverflow.com/questions/35001387/how-to-handle-error-in-generatestate-in-synconsubscribe-rxjava) question.
=> 1.x: fix SyncOnSubscribe not signalling onError if the generator crashes

src/main/java/rx/internal/operators/OnSubscribeAmb.java, src/test/java/rx/internal/operators/OnSubscribeAmbTest.java
The OnSubscribeAmb shared the choice variable among all of its subscribers which prevented reusing the same Observable.
=> 1.x: fix Amb sharing the choice among all subscribers

src/main/java/rx/Observable.java, src/main/java/rx/Single.java, src/main/java/rx/internal/operators/OperatorSubscribeOn.java, src/main/java/rx/internal/operators/OperatorTimeoutBase.java, src/main/java/rx/internal/util/ScalarSynchronousObservable.java, src/test/java/rx/internal/operators/OperatorReplayTest.java, src/test/java/rx/internal/operators/OperatorUnsubscribeOnTest.java, src/test/java/rx/internal/util/ScalarSynchronousObservableTest.java
Updated `just()` to fully support backpressure.
This is a repost of #3496 due to merge and rebase problems.
=> 1.x: just() now supports backpressure (+ related fixes/changes)

src/main/java/rx/Observable.java, src/main/java/rx/Single.java, src/main/java/rx/exceptions/CompositeException.java, src/main/java/rx/internal/operators/OnSubscribeAmb.java, src/main/java/rx/internal/util/IndexedRingBuffer.java, src/main/java/rx/internal/util/ScalarSynchronousObservable.java, src/main/java/rx/internal/util/atomic/SpscLinkedArrayQueue.java, src/main/java/rx/internal/util/atomic/SpscUnboundedAtomicArrayQueue.java, src/main/java/rx/internal/util/unsafe/SpscUnboundedArrayQueue.java, src/main/java/rx/internal/util/unsafe/UnsafeAccess.java, src/main/java/rx/observables/GroupedObservable.java, src/main/java/rx/observers/Observers.java, src/main/java/rx/observers/Subscribers.java, src/main/java/rx/subjects/ReplaySubject.java
=> 1.x: Remove redundant "final" modifiers

src/main/java/rx/internal/operators/OperatorSampleWithObservable.java, src/test/java/rx/internal/operators/OperatorSampleTest.java
Reported on the rxjava discussion group.
Sample has to disconnect itself from the Producer chain and request Long.MAX_VALUE instead of whatever the downstream requests.
=> 1.x: fix sample(Observable) not requesting Long.MAX_VALUE

src/main/java/rx/internal/operators/OperatorSampleWithObservable.java, src/test/java/rx/internal/operators/OperatorSampleTest.java
This PR fixes 2 bugs with `sample`
- Termination of the main or sampler subscriber unsubscribed the child subscriber which is not allowed.
- The sampler wrapped the child subscriber and thus it allowed setting a producer on the child (thus sampling based on request with some sources).
In addition, #3657 wants to emit the very last item on completion to which I marked the required changes in comments (to be uncommented in a separate PR if needed).
=> 1.x: fix unsubscription and producer issues in sample(other)

src/main/java/rx/internal/operators/OperatorDoOnRequest.java, src/test/java/rx/internal/operators/OperatorDoOnRequestTest.java
When the operator is assembled and it sets the producer on the child, if the child doesn't request until the assembly is complete, `doOnRequest` requested the default Long.MAX_VALUE.
=> 1.x: fix doOnRequest premature requesting.

src/main/java/rx/Single.java, src/main/java/rx/internal/operators/SingleOperatorOnErrorResumeNextViaSingle.java, src/test/java/rx/SingleTest.java
Part of #3652, will submit a PR for `onErrorResumeNext(Func1<Throwable, Single>)` later.
=> 1.x: Add Single.onErrorResumeNext(Single)

src/main/java/rx/Single.java, src/main/java/rx/internal/util/ScalarSynchronousSingle.java, src/test/java/rx/SingleTest.java, src/test/java/rx/internal/util/ScalarSynchronousSingleTest.java
This PR add similar optimization as ScalarSynchronousObservable to Single.just method.
=> 1.x: Optimizate single just

src/main/java/rx/observers/Subscribers.java
fix for https://github.com/ReactiveX/RxJava/issues/3664
=> Update javadoc for Subscribers.empty()

src/main/java/rx/Observable.java, src/main/java/rx/internal/operators/OnSubscribeCombineLatest.java, src/test/java/rx/internal/operators/OnSubscribeCombineLatestTest.java
This PR is a backport of the 2.x `combineLatest` with `null` support and let's the programmer combine more than 128 sources at once. Note that 2.x supports manual sizing of the prefetch buffer and allows delaying the exceptions to the last moment; I kept these in case such features are required by 1.x some day.
The original had this 128 limit due to using a single and non-parametric RxRingBuffer to store values from sources. In addition, the original algorithm divided downstream requests among the sources with some strange logic in order to keep them running and not overflow the buffer.
This PR uses an unbounded-linked SPSC queue which can now hold as many elements as there are sources times the default ring buffer size (this is not preallocated and grows/shrinks as necessary).
The …
=> 1.x: CombineLatest now supports any number of sources

src/main/java/rx/internal/operators/BackpressureUtils.java, src/main/java/rx/internal/operators/OperatorConcat.java, src/perf/java/rx/operators/ConcatPerf.java
This PR reduces the request tracking overhead of `concat` by tracking the produced item count in a plain field and subtracting it from the arbiter and requested values only before the inner source completes. So instead of N decrementAndGet call, we have 1 addAndGet(-N) per source. 
I've added a perf class to measure the difference.
(Intel Celeron 1005M @ 2GHz, Windows 7 x64, Java 8u66)
The throughput increased considerably, although I would have expected more, especially in the 1M case where the subscription overhead doesn't matter.
I'll do further investigation on it and post a follow-up PR if this gets merged in the meantime.
=> 1.x: concat reduce overhead when streaming a source

src/main/java/rx/internal/operators/OperatorTake.java, src/test/java/rx/internal/operators/OperatorTakeTest.java
Originally, only 0 was checked which resulted in `onCompleted()` but negative values weren't. When the downstream requested, c became -1 and was requested from the source. `range` ignores negative requests but other sources may throw IAE in that case.
With the fix, the operator will throw IAE in assembly time.
=> 1.x: fix take(-1) not completing

CONTRIBUTING.md
Since it has become standard to have everything about how to contribute on CONTRIBUTING.md file, I think   it would be really helpful and good to have link to How-to-Contribute wiki page.
=> Add How to Contribute wiki link

src/test/java/io/reactivex/schedulers/SchedulerLifecycleTest.java
I forgot that RxCached threads can get evicted during the test. The new logic makes sure no new threads appeared.
=> 2.x: fix SchedulerLifecycle.testStartIdempotence vs cached threads dying

src/main/java/rx/exceptions/CompositeException.java, src/test/java/rx/exceptions/CompositeExceptionTest.java
=> 1.x: Fix NPE in CompositeException when nested throws on initCause

src/main/java/rx/internal/operators/OperatorMerge.java, src/main/java/rx/internal/operators/OperatorSkip.java, src/test/java/rx/internal/operators/OperatorMergeTest.java, src/test/java/rx/internal/operators/OperatorSkipTest.java
As per #3675, we should also check the `count` argument of `skip`. Also added the missing check for `merge`'s `maxConcurrent`.
=> 1.x: negative argument check for skip's count and merge's maxConcurrent

src/main/java/rx/Observable.java, src/test/java/rx/internal/operators/OperatorMergeDelayErrorTest.java
=> 1.x: Added MergeDelay operators for Iterable of Observables

src/main/java/rx/internal/operators/OperatorZip.java
Reported in #3687.
By the way, I see several other small problems with zip: it is implemented as an `Operator` and even though one can know the number of sources upfront, this indirection hides the fact. In addition, it uses SpMc queue but could just use Spsc because there is only one drain thread at a time.
=> 1.x: Fix zip() - observer array becoming visible too early and causing NPE

src/main/java/rx/Observable.java, src/main/java/rx/Single.java, src/main/java/rx/internal/operators/OperatorObserveOn.java, src/main/java/rx/internal/util/atomic/SpscAtomicArrayQueue.java, src/main/java/rx/internal/util/unsafe/SpscArrayQueue.java, src/test/java/rx/internal/operators/OperatorObserveOnTest.java
This PR fixes the "messing around" reported in #3002 and adds an overload to `observeOn` that allows delaying errors without the need for wrapping (see #3542 and maybe there are other reports).
In addition, this PR adds a proper override of the `isEmpty` method to simply compare the two indexes for emptiness directly instead of `size() == 0` to avoid looping, multi-reading and casting.
Benchmark comparison (i7 4790, Windows 7 x64, Java 8u66):
Note that the benchmark is generally quite noisy, yielding hectic results (i.e., firing up a thread with newThread may take quite some random microseconds). For example, `observeOnImmediate` shouldn't be affected by any of the changes yet the run-to-run variance is +/- 10%. I'm fine with the results of the benchmark.
=> 1.x: fix observeOn resource handling, add delayError capability

src/main/java/rx/internal/operators/OnSubscribePublishMulticast.java, src/main/java/rx/internal/operators/OperatorPublish.java, src/test/java/rx/internal/operators/OperatorPublishFunctionTest.java
Solves the problems #3673 and #3674 by introducing a new subject-like dispatcher class `OnSubscribePublishMulticast` that does support backpressure, pauses when there are no subscribers and signals the terminal event for late subscribers; all ideal for the multicasting `publish(Func1)` overload.
=> 1.x: change publish(Func1) to use a dedicated subject-like dispatcher

src/main/java/rx/internal/util/ScalarSynchronousObservable.java
Schedulers.computation()
When one installs a scheduler hook which makes Schedulers.computation() return a different scheduler, the constant function in ScalarSynchronousObservable crashes if that hasn't been initialized.
=> 1.x: fix ScalarSynchronousObservable expects EventLoopsScheduler from

src/main/java/rx/Completable.java, src/test/java/rx/CompletableTest.java
=> 1.x: Add Completable.doOnCompleted and deprecate Completable.doOnComplete

src/main/java/rx/Completable.java, src/test/java/rx/CompletableTest.java
The empty and lambda-based `Completable.subscribe()` returns a `Subscription` whose `isUnsubscribed` should be consistent with the rest of the reactive objects by returning true if the sequence terminated (not just when one truly cancelled it).
=> 1.x: make Completable.subscribe() report isUnsubscribed consistently

build.gradle, gradle/stylesheet.css
This PR modified the javadoc task to make it generate the same format of http://reactivex.io/RxJava/javadoc/index.html. `gradle/stylesheet.css` is copied from https://github.com/ReactiveX/RxJava/blob/gh-pages/javadoc/stylesheet.css
This supports both Java 7 and Java 8. However, docs generated by Java 8 have a totally different style. Hence we should use Java 7 to generate javadoc and publish it to http://reactivex.io/RxJava/javadoc/index.html.
=> 1.x: Make the javadoc task generate correct docs

README.md
The latest version of rxjava is 978K long.
=> Update information about jar size in README.md

src/main/java/rx/internal/operators/OperatorMapNotification.java, src/test/java/rx/internal/operators/OperatorMapNotificationTest.java
The previous algorithm used a 2 element queue but it was possible the drain loop got captured and the queue wasn't enough, causing `MissingBackpressureException`.
The new algorithm uses the requested field's most significant bit to indicate a completed state. If the terminal events reach it with non-zero request or a post-terminal request finds a zero request amount, the last item is emitted.
In addition, the upstream's producer may arrive after the first request thus the class includes the usual arbitration logic inlined. If the upstream doesn't set a `Producer` but just emits values, the production/backpressure checks are bypassed.
```
rx.internal.operators.OperatorFlatMapTest > testFlatMapTransformsMaxConcurrentNormalLoop FAILED
java.lang.AssertionError: Unexpected onError events: 1
at …
```
=> 1.x: fix mapNotification's last item backpressure handling

src/test/java/rx/internal/operators/OperatorGroupByTest.java
This is passing against 1.1.1 with the back-ported OperatorGroupBy, but would be good to have it in as a regression test.
See also: #3698
=> 1.x: GroupBy Regression Test Case

src/main/java/rx/internal/operators/OnSubscribeRange.java, src/main/java/rx/internal/operators/OperatorMerge.java
Changes to the scalar fast-path was inspired by the Project Reactor's `flatMap` which was in turn inspired by RxJava 2.x's implementation of `flatMap`.
**Naturally, this will conflict with #3169 .**
Benchmark for comparison (i7 4770K, Windows 7 x64, Java 8u66):
Just by applying the scalar re-batching, the operator gained a massive 45% throughput increase, from **48 MOps/s** to **71 MOps/s**.
When the range optimization is also applied, the improvement is even more impressive:  +60% throughput, from **48 MOps/s** to **79 MOps/s**.
The optimization doesn't really affect `rangeFlatMapRange`, it has a larger run-to-run variance due to GC.
I'm experimenting with the 2.x branch as well and by applying these two optimizations, the throughput increasd from **40 MOps/s** to **58 MOps/s**. I'm …
=> 1.x: overhead reduction for merge and flatMap

src/test/java/rx/ObservableTests.java, src/test/java/rx/internal/operators/OnSubscribeCombineLatestTest.java, src/test/java/rx/internal/operators/OnSubscribeRefCountTest.java, src/test/java/rx/internal/operators/OperatorMergeMaxConcurrentTest.java, src/test/java/rx/internal/operators/OperatorReplayTest.java
These changes may help in reducing problems when the tests are run on an Android emulation:
- set an uncaught exception handler because the native error handler crashes the entire test run.
- reduce memory usage by some tests by doing fewer loops or items.
- fix a missing backpressure case as Android starts threads much slower (100ms?).
=> 1.x: Test adjustments to reduce problems when tests run on Android

src/main/java/rx/Single.java, src/test/java/rx/SingleTest.java
As discussed in #3708
This adds `takeUntil(Observable)` and `takeUntil(Single)` support in `Single`. It was mostly just adapting the logic from the existing `OperatorTakeUntil` and adjusting it for accepting a `Single` and sending a `CancelattionException` in the event of a submission from `other` prior to a terminal event in the source `Single`.
Any feedback is appreciated it, this is my first time contributing an implementation to this project. Particularly wondering if it's worth keeping both overloads or if the user should just coerce their `other` to one type or ther other. Also particularly looking for feedback on what information to include in the `CancellationException`.
=> Add takeUntil support in Single

src/main/java/rx/internal/operators/OperatorScan.java, src/test/java/rx/internal/operators/OperatorScanTest.java
Changes in 1.1.1. for the `scan` operator introduced a bug in requesting where when the initial request was for max value the `scan` operator requested one less than that value of upstream (which affects fast-path producers).
I believe this bug only affects 1.1.1 (haven't looked at 2.x).
This PR includes a test that failed on the original code.
=> scan should pass upstream a request of Long.MAX_VALUE

src/main/java/rx/Completable.java, src/test/java/rx/CapturingUncaughtExceptionHandler.java, src/test/java/rx/CompletableTest.java, src/test/java/rx/schedulers/SchedulerTests.java
Instead, deliver them up to the thread's uncaught exception handler.
Fixes reactivex/rxjava#3726
=> Avoid swallowing errors in Completable

src/main/java/rx/Observable.java, src/main/java/rx/observables/AsyncOnSubscribe.java, src/main/java/rx/observables/SyncOnSubscribe.java
This is to facilitate the discovery of methods for creating observables that respect back pressure semantics. Currently the `Observable#create(OnSubscribe)` static method is the easiest method to discover for creating an observable which does not provide clear facilities for managing back pressure.
=> Creating Observable#create overloads for SyncOnSubscribe and AsyncOnSubscribe

src/main/java/rx/Single.java, src/test/java/rx/SingleTest.java
Ref #3740.
I didn't write much unit tests for `doOnSubscribe` because it internally uses `OperatorDoOnSubscribe` which is well covered.
=> Add doOnSubscribe for Single

src/test/java/rx/ObservableTests.java
The tests started regularly failing on travis. This PR increases the waiting time to 2 seconds in total.
=> 1.x: Fix the test Issue1685 not waiting long enough.

src/perf/java/rx/operators/FlatMapAsFilterPerf.java
This PR adds a perf class to measure the overhead of using `empty()` when the `flatMap`/`concatMap` emulates `filter`.
This will establish the comparison baseline for `flatMap`/`concatMap` optimization as requested in #1653.
The baseline [numbers](https://gist.github.com/akarnokd/243a09e28edfc27aeb0d) (i7 4770K, Windows 7 x64, Java 8u72):
Comparing `flatMap` against `concatMap`:
Here, mask indicates the and-mask that makes emitting `empty` less frequent: 0 = always, 1 = every other, 3 = every fourth, 7 = every eighth. This also means that `rangeEmpty` starts emitting more and more values with higher mask value hence the different throughput values.
=> 1.x: measure flatMap/concatMap performance when used as filter

src/main/java/rx/Single.java, src/main/java/rx/internal/operators/SingleOnSubscribeUsing.java, src/test/java/rx/SingleTest.java, src/test/java/rx/internal/operators/SingleOnSubscribeUsingTest.java
This PR adds the factory method `using()` +1 overload to `Single` as requested in #3732.
For convenience, I've also added `Single.subscribe(Observer)`.
=> 1.x: Single.using()

src/main/java/rx/Observable.java
=> 1.x: clarify join/groupJoin no ordering guarantees

src/main/java/rx/Observable.java, src/main/java/rx/internal/operators/OnSubscribeCombineLatest.java, src/test/java/rx/internal/operators/OnSubscribeCombineLatestTest.java
This PR exposes the `delayError` option in `combineLatest` as `combineLatestDelayError`.
(Note that we have convenience overloads with 2-9 sources that could also use an overload, but that just expands the API surface drastically.)
=> 1.x: combineLatestDelayError

src/main/java/rx/Observable.java, src/main/java/rx/internal/operators/OperatorSwitch.java, src/test/java/rx/internal/operators/OperatorSwitchTest.java
This PR adds a delayError version to the `switchOnNext` / `switchMap` operators.
=> 1.x: switchOnNextDelayError and switchMapDelayError

src/main/java/rx/internal/operators/OperatorObserveOn.java, src/test/java/rx/internal/operators/OperatorObserveOnTest.java
This fixes `observeOn` not completing immediately if the downstream requested exactly the remaining amount. The original version required a new request from downstream to trigger the delivery of the terminal event.
This also fixes the rare failure in `testNoMoreRequestsAfterUnsubscribe` because the unsubscription is now checked in-sequence and doesn't trigger the unwanted replenishment request.
=> 1.x: observeOn - fix in-sequence termination/unsubscription

src/main/java/rx/Single.java, src/main/java/rx/plugins/RxJavaPlugins.java, src/main/java/rx/plugins/RxJavaSingleExecutionHook.java, src/main/java/rx/plugins/RxJavaSingleExecutionHookDefault.java, src/test/java/rx/SingleTest.java, src/test/java/rx/plugins/RxJavaPluginsTest.java
=> 1.x: Added Single execution hooks

src/main/java/rx/internal/schedulers/GenericScheduledExecutorService.java, src/main/java/rx/schedulers/ExecutorScheduler.java, src/test/java/rx/internal/schedulers/GenericScheduledExecutorServiceTest.java
This PR relates to the failure of `errorThrownIssue1685`.
The underlying problem was with the `GenericScheduledExecutorService`. By being multi-threaded, tasks scheduled from the same thread one after the other may get reordered because different worker threads inside the pool could pick them up at the same time. In this case, there is no guarantee they keep their FIFO order.
*(I currently have no idea how one can use trampolining for this case; subsequent tasks may have any relative delays in respect to each other.)*
The solution creates N single threaded `ScheduledExecutorService`s and getInstance() hands one of them out. In turn `ExecutorService` takes one in its worker upfront.
However, there is still the problem when the programmer uses a multi-threaded `ScheduledExecutorService` …
=> 1.x: fix ExecutorScheduler and GenericScheduledExecutorService reorder bug

src/main/java/rx/BackpressureOverflow.java, src/main/java/rx/Observable.java, src/main/java/rx/internal/operators/OperatorOnBackpressureBuffer.java, src/test/java/rx/internal/operators/OperatorOnBackpressureBufferTest.java, src/test/java/rx/internal/operators/OperatorOnExceptionResumeNextViaObservableTest.java
Introduce a new interface BackpressureOverflowStrategy that allows implementing different handlers for an overflow situation.  This patch adds three implementations, reachable via OverflowStrategy:
static class OverflowStrategy {
static final BackpressureOverflowStrategy DEFAULT = Error.INSTANCE;
static final Error ERROR = Error.INSTANCE;
static final DropOldest DROP_OLDEST = DropOldest.INSTANCE;
static final DropLatest DROP_LATEST = DropLatest.INSTANCE;
}
The behavior for each is the following:
- ERROR remains the default as the existing implementation.
- DROP_LATEST will drop newly produced items after the buffer fills up.
- DROP_OLDEST will drop the oldest elements in the buffer, making room for
newer ones.
In all cases, a drop will result in a notification to the producer by invoking …
=> 1.x: OnBackpressureBuffer: DROP_LATEST and DROP_OLDEST

src/main/java/rx/Observable.java, src/main/java/rx/internal/operators/BackpressureUtils.java, src/main/java/rx/internal/operators/OperatorBufferWithSize.java, src/main/java/rx/internal/operators/OperatorWindowWithSize.java, src/main/java/rx/internal/operators/UnicastSubject.java, src/main/java/rx/observers/TestSubscriber.java, src/test/java/rx/internal/operators/OperatorBufferTest.java, src/test/java/rx/internal/operators/OperatorWindowWithSizeTest.java
This PR fixes the backpressure behavior of the counted `buffer` and `window` operators and consists of several changes.
The main issue lies when `count > skip` in the operators, yielding overlapping buffers/windows. 
For `buffer`, when the upstream completed, the logic emitted all remaining partial buffers even if there was no request for new buffers, which can result in `MissingBackpressureException` somewhere. The proper handling of the final buffers required a new backpressure management algorithm which is now part of the `BackpressureUtils` class and consists of two new methods: `postCompleteDone` called from onComplete to take over the emission of queued values and `postCompleteRequest` which manages requests before and after the completed state.
For `window`, the new window opened …
=> 1.x: fix counted buffer and window backpressure

CHANGES.md
=> 1.x: Release 1.1.2 CHANGES.md update

src/main/java/rx/internal/operators/OperatorSampleWithObservable.java, src/main/java/rx/internal/operators/OperatorSampleWithTime.java, src/test/java/rx/internal/operators/OperatorSampleTest.java
Changes:
- `OperatorSampleWithTime` emits last stored value if it is set before `onCompleted`
- `OperatorSampleWithObservable` emits last sampled value if source or sample complete.
As discussed in https://github.com/ReactiveX/RxJava/issues/3657.
=> 1.x: Operator sample emits last sampled value before termination.

src/main/java/rx/exceptions/CompositeException.java, src/main/java/rx/exceptions/Exceptions.java, src/test/java/rx/exceptions/CompositeExceptionTest.java
Before this PR messagePrefix was never used :dancer: 
If you guys want I can revert the change on CompositeExceptionTest.java:177. I just thought that way it' be nicer.
About the message is there any reason for having a space after the dot?
=> 1.x: Deprecate CompositeException constructor with message prefix

src/main/java/rx/internal/operators/OperatorGroupBy.java, src/test/java/rx/GroupByTests.java
In 1.1.1, `groupBy` was fixed to properly honor backpressure on the outer `Observable`. The change included a drain loop that emitted `onCompleted()` to the groups only when all `GroupedObservable`s were drained from the main queue. This delayed the group's completion unnecessarily causing the `concat` operator to hang in some source-consumer cases such as #3775.
This PR fixes the behavior by signalling `onCompleted()` to the groups the moment the main completes. 
Note, however, that concatenating groups is eventually prone to hangs due to the groups not completing until the source completes, thus `concat` can't switch to the next source. One should use `flatMap` or `concatMapEager` instead.
=> 1.x: fix GroupBy delaying group completion till all groups were emitted

src/main/java/rx/Single.java
=> 1.x: Expose Single.lift()

src/main/java/rx/Single.java, src/main/java/rx/internal/operators/SingleOperatorZip.java, src/test/java/rx/SingleTest.java
=> 1.x: Prevent Single.zip() of zero Singles

src/main/java/rx/Observable.java, src/main/java/rx/internal/operators/OperatorObserveOn.java, src/test/java/rx/internal/operators/OperatorObserveOnTest.java
The observeOn operator is backed by a small queue of 128 slots that may
overflow quickly on slow producers.  This could only be avoided by
adding a backpressure operator before the observeOn (not only
inconvenient, but also taking a perf. hit as it forces hops between two
queues).
This patch allows modifying the default queue size on the observeOn
operator.
Fixes: #3751
Signed-off-by: Galo Navarro <anglorvaroa@gmail.com>
=> observeOn: allow configurable buffer size

src/main/java/rx/Completable.java, src/main/java/rx/Single.java, src/main/java/rx/internal/operators/SingleOnSubscribeDelaySubscriptionOther.java, src/test/java/rx/CompletableTest.java, src/test/java/rx/internal/operators/SingleOnSubscribeDelaySubscriptionOtherTest.java
https://github.com/ReactiveX/RxJava/issues/3730
=> 1.x: Add Completable.andThen(Single)

src/main/java/rx/observers/TestSubscriber.java
the docs of TestSubscriber.create(Subscriber) and TestSubscriber.create(Observer) got mixed up.
I just swapped them.
=> 1.x: Fix TestSubscriber.create doc

src/main/java/rx/internal/util/unsafe/UnsafeAccess.java
Part of #3459, related to #3815.
=> 1.x: Add system property for disabling usage of Unsafe API

src/main/java/rx/subjects/AsyncSubject.java, src/main/java/rx/subjects/SubjectSubscriptionManager.java, src/test/java/rx/subjects/AsyncSubjectTest.java
`AsyncSubject` can trivially support backpressure when it emits a single item by setting the `SingleProducer` on the child `Subscriber` instead of calling `onNext` immediately.
=> 1.x: AsyncSubject now supports backpressure

src/main/java/rx/internal/operators/OperatorDoAfterTerminate.java, src/test/java/rx/internal/operators/OperatorDoAfterTerminateTest.java
Fixes the bug reported in #3435.
=> 1.x: DoAfterTerminate handle if action throws

src/main/java/rx/Observable.java, src/main/java/rx/Single.java, src/main/java/rx/internal/operators/BlockingOperatorLatest.java, src/main/java/rx/internal/operators/BlockingOperatorMostRecent.java, src/main/java/rx/internal/operators/BlockingOperatorNext.java, src/main/java/rx/internal/operators/BlockingOperatorToFuture.java, src/main/java/rx/internal/operators/BlockingOperatorToIterator.java, src/main/java/rx/internal/operators/CachedObservable.java, src/main/java/rx/internal/operators/CompletableOnSubscribeConcat.java, src/main/java/rx/internal/operators/CompletableOnSubscribeMerge.java, src/main/java/rx/internal/operators/OnSubscribeCombineLatest.java, src/main/java/rx/internal/operators/OperatorMapPair.java, src/main/java/rx/internal/operators/OperatorMulticast.java, src/main/java/rx/internal/operators/OperatorReplay.java, src/main/java/rx/internal/operators/SingleOnSubscribeDelaySubscriptionOther.java, src/main/java/rx/observables/AsyncOnSubscribe.java, src/main/java/rx/observables/BlockingObservable.java, src/main/java/rx/singles/BlockingSingle.java
The type inference of javac in JDK 9 has been changed in an incompatible way, marking many generics-related code invalid.
The most common problems:
- The inference calculates `Observable<? extends T>` but from its perspective, a call to `subscribe()` with a `Subscriber<T>` is ambiguous as it matches `subscribe(Observer<? super T>)` and `subscribe(Subscriber<? super T>)`. Somehow, the more specific class is not considered as a valid choice. Downcasting to `Observable<T>` fixes the error.
- `A<?>[]` no longer accepts `A<Ti>` elements, requires the use of raw types to get around
The tests appear to compile fine.
Note that I couldn't find a working IDE for JDK 9 and had to revert to command line trickery:
```
@echo off
dir /s /B src\main\java\rx\*.java > sources.txt
dir /s /B …
```
=> 1.x: javac 9 compatibility fixes

src/main/java/rx/Observable.java, src/main/java/rx/Single.java
=> 1.x fromCallable() @Experimental -> @Beta

src/main/java/rx/internal/operators/OperatorSwitch.java, src/main/java/rx/internal/util/atomic/SpscLinkedArrayQueue.java, src/test/java/rx/internal/operators/OperatorSwitchTest.java
This PR fixes the producer retention problem and backpressure problem in `switchMap`/`switchOnNext`.
In the original, when an inner source completed, its producer was still referenced after it. If there was no new inner source or the next inner source didn't set a new producer, the operator leaked the previous inner source's internals. The fix involves nulling out the producer field when the inner source completes (and is still the current one).
The original had an additional bug due to a race condition between the request arbitration and switching inner sources. In some cases, the switch didn't properly forward the remaining request amount to the new inner source, causing hangs. In some other cases, both the old and new inner sources were able to emit, causing overflow. The fix involves …
=> 1.x: fix switchMap/switchOnNext producer retention and backpressure

DESIGN.md
This is a first draft of the design document for the 2.x branch.
We are interested in collecting any feedback from the community (implementers but also pure users).
This present document is the collaborative work of @abersnaze, @benjchristensen, @stealthcode, and @stevegury. But we encourage anyone to propose improvements/clarifications via pull-request.
=> 2.x design decisions

src/main/java/rx/schedulers/ExecutorScheduler.java, src/test/java/rx/schedulers/ExecutorSchedulerTest.java
I noticed that when a worker built from `Schedulers.from(Executors.newFixedThread(1))` is unsubscribed the use of a `CompositeSubscription` to track task subscriptions means that the tasks may be unsubscribed in any old order (`CompositeSubscription` holds its subscriptions in a `HashSet`).  This means that if the worker is given task A and task B then the race can prevent A from running but allow B to run! I've included a unit test in this PR that demos it. Fails every time on my machine on the first loop.
This  PR is really for discussion about the problem and possible fixes.
I have included a possible fix which is to track overall subscription using a volatile boolean and check that boolean before running any task. If this was considered the way to go some further simplification would …
=> 1.x: improve ExecutorScheduler worker unsubscription

src/main/java/rx/internal/operators/OnSubscribeConcatMap.java, src/test/java/rx/internal/operators/OperatorConcatTest.java
There were two tiny problems with the rewritten `concatMap` operator, mainly due to copy-paste error:
- When a scalar was concatenated, the `active` field was not set and thus the next prefetched source overwrote it.
- When the scalar was set on the arbiter, its custom producer didn't check for n > 0 zero causing instant emission always. Generally Producer.request(0) is allowed and should be no-op (unlike RS).
- When an empty() was encountered as a last source, the it didn't trigger the check for completion afterwards.
=> 1.x: fix concatMap scalar/empty source behavior

src/main/java/rx/internal/operators/OperatorObserveOn.java, src/test/java/rx/internal/operators/OperatorObserveOnTest.java, src/test/java/rx/observables/AsyncOnSubscribeTest.java
This PR makes sure `observeOn` requests replenishments in a fixed and predictable quantity of 75% of the `bufferSize`, that is, if an emission counter reaches `0.75 * bufferSize`, that amount is requested and the emission counter is reset to zero. This requires saving the emission count between drain runs. If the bufferSize is 1 or 2, the replenishment will trigger after every 1 or 2 items.
Note that there is only one sensitive operator-builder, `AsyncOnSubscribe`, which is mostly affected by the request pattern as it facilitates user code to respond with an Observable sequence of the requested amount.
In addition, since `observeOn` now supports setting the buffer size, it can act as a rebatching operator via the help of `Schedulers.immediate()`.
=> 1.x: observeOn now replenishes with constant rate

src/main/java/rx/internal/operators/OnSubscribeDelaySubscriptionOther.java, src/test/java/rx/internal/operators/OnSubscribeDelaySubscriptionOtherTest.java, src/test/java/rx/internal/operators/OperatorDelayTest.java
The serial subscription in the `delaySubscription(Observable)` operator was not chained properly and thus an unsubscription before any events by the other didn't prevent the subscription to the main source.
Reported in #3844
=> 1.x: fix delaySubscription(Observable) unsubscription before triggered

CHANGES.md
Update to the CHANGES.md file.
(Without the flatMap and replay perf enhancements.)
=> 1.x: Release 1.1.3 CHANGES.md update

src/perf/java/rx/operators/ConcatMapInterablePerf.java
This PR adds a perf class to measure the difference between `concatMap()` and `concatMapIterable()` to support performance work
[Results](https://gist.github.com/akarnokd/86f5507ba4dec6a19fdf5b4bf7d7578f) on my machine (i7 4770K, Windows 7 x64, Java 8u77):
=> 1.x: ConcatMap vs ConcatMapIterable perf

src/main/java/rx/internal/schedulers/CachedThreadScheduler.java, src/main/java/rx/internal/schedulers/NewThreadScheduler.java, src/main/java/rx/plugins/RxJavaSchedulersHook.java, src/main/java/rx/schedulers/Schedulers.java
Unlike other hooks, the `RxJavaSchedulersHook` has no access to the real `Scheduler` instances in order to do wrapping/delegation. With these factory methods, a hook can access what would otherwise be the instance used since there is often no other means of creating these specialized schedulers.
For Android this wrapping/delegation use-case is important for UI testing. We have a means to tell the testing framework when the app is idle and to do that we need to hook into the schedulers to know when they're empty. This is easy to do currently, but you cannot wrap the real instance and instead have to supply alternate implementations which might subtly alter the behavior under test.
These three methods are referenced in #3724, and I think providing the defaults is useful as well as …
=> Provide factories for creating the default scheduler instances.

src/main/java/rx/Single.java, src/test/java/rx/SingleTest.java
=> 1.x: Add Single.toCompletable()

src/main/java/rx/internal/schedulers/CachedThreadScheduler.java, src/main/java/rx/internal/schedulers/EventLoopsScheduler.java, src/test/java/rx/schedulers/AbstractSchedulerConcurrencyTests.java, src/test/java/rx/schedulers/ExecutorSchedulerTest.java
There is an unsubscribe race condition similar to #3842 in `CachedThreadScheduler.EventLoopWorker` and `EventLoopsScheduler.EventLoopWorker`. Image the following execution order:
| Execution Order  | thread 1 | thread 2 |
| ------------- | ------------- | ------------- |
| 1 |  | submit task A |
| 2 |  | submit task B |
| 3 | unsubscribe Worker  |  |
| 4 | unsubscribe task A |   |
| 5 | | task A won't run as it's unsubscribed |
| 6 | | run task B |
| 7 | unsubscribe task B |  |
So task B will run but its previous task A will be skipped.
This PR adds a check before running an action and moves `workerUnderConcurrentUnsubscribeShouldNotAllowLaterTasksToRunDueToUnsubscriptionRace` to `AbstractSchedulerConcurrencyTests` to test all concurrent schedulers.
=> Fix an unsubscribe race in EventLoopWorker

src/main/java/rx/schedulers/ExecutorScheduler.java
As per discussion in #3842, there was an outstanding possibility that unsubscription of a `Worker` would not cancel all tasks waiting in the queue. This PR addresses that possibility. I attempted to provoke the condition in a unit test but didn't manage it. Nethertheless I think this change completes the protection desired in #3842.
I do have mixed feelings about the possible double calling of `queue.clear()` (once in the `run()` method and once in the `unsubscribe()` method. Any preferences?
=> 1.x: improve ExecutorScheduler worker unsubscription some more

src/main/java/rx/internal/operators/OperatorObserveOn.java, src/main/java/rx/internal/schedulers/ExecutorScheduler.java, src/main/java/rx/internal/schedulers/GenericScheduledExecutorService.java, src/main/java/rx/internal/schedulers/ImmediateScheduler.java, src/main/java/rx/internal/schedulers/SleepingAction.java, src/main/java/rx/internal/schedulers/TrampolineScheduler.java, src/main/java/rx/schedulers/ImmediateScheduler.java, src/main/java/rx/schedulers/NewThreadScheduler.java, src/main/java/rx/schedulers/Schedulers.java, src/main/java/rx/schedulers/TrampolineScheduler.java, src/test/java/rx/internal/schedulers/ExecutorSchedulerTest.java, src/test/java/rx/schedulers/ComputationSchedulerTests.java, src/test/java/rx/schedulers/IoSchedulerTest.java, src/test/java/rx/schedulers/SchedulerTests.java
A continuation of some work done in #3856 of removing uninstantiable types from the public API (via deprecation).
=> Deprecate remaining public scheduler types.

src/main/java/rx/internal/operators/OnSubscribeFromIterable.java, src/test/java/rx/internal/operators/OnSubscribeFromIterableTest.java
The `from(Iterable)` ignored non-fatal exceptions thrown by the `Iterable` and `Iterator`.
Apart from wrapping the calls into `try-catch`, the overal emission algorithm has been changed:
- It calls `hasNext` only once for each available value. Since the subscribe() checks for an outright empty `Iterable`, the drain loop runs only if it wasn't empty and does another `hasNext` check immediately to complete immediately if possible.
- It uses what I call a fast-flow algorithm to avoid decrementing the requested amount (this) if there were more requests issued during the emission.
=> 1.x: fix from(Iterable) error handling of Iterable/Iterator

src/main/java/rx/exceptions/Exceptions.java, src/test/java/rx/exceptions/ExceptionsTest.java
Otherwise, if there's an error in onCompleted, the exception is
swallowed and unreported.
Fixes #3885
=> throwIfFatal() now throws OnCompletedFailedException

src/main/java/rx/internal/schedulers/CachedThreadScheduler.java, src/main/java/rx/internal/schedulers/EventLoopsScheduler.java, src/main/java/rx/internal/schedulers/NewThreadScheduler.java, src/main/java/rx/internal/util/RxThreadFactory.java, src/main/java/rx/plugins/RxJavaSchedulersHook.java, src/test/java/rx/internal/operators/OperatorObserveOnTest.java, src/test/java/rx/plugins/RxJavaSchedulersHookTest.java, src/test/java/rx/schedulers/ComputationSchedulerTests.java, src/test/java/rx/schedulers/IoSchedulerTest.java
This allows hooks to create schedulers whose threads have different priorities.
Closes #3724.
=> Expose scheduler factories which accept thread factories.

src/main/java/rx/Observable.java
This change will make sure if the `Subscriber` has unsubscribed, the non-fatal error is sent to the plugin error handler at least. I.e.,
```java
Observable.create(s -> {
s.onError(new RuntimeException());
throw new IllegalArgumentException();
}).subscribe();
```
In addition, if the original code threw `RuntimeException` in case the `subscriber.onError()` threw. I've changed this to `OnErrorFailedException` but not sure the original type was intentional or just left out.
=> Have undeliverable errors on subscribe() sent to plugin error handler.

src/main/java/rx/plugins/RxJavaPlugins.java
Discussions found here: https://github.com/ReactiveX/RxJava/issues/2297
=> Making RxPlugins reset() public

src/test/java/rx/internal/operators/OperatorSwitchTest.java
`OperatorSwitchTest.switchAsyncHeavily` sometimes times out. Could be due to Travis or an actual bug which doesn't deliver the last few elements.
=> 1.x: Give more time to OperatorSwitchTest.switchAsyncHeavily

src/main/java/rx/internal/operators/OperatorMapPair.java, src/test/java/rx/internal/operators/OperatorMapPairTest.java
=> 1.x: OperatorMapPair should unsubscribe on crash eagerly

src/main/java/rx/internal/operators/OperatorCast.java, src/test/java/rx/internal/operators/OperatorCastTest.java
=> 1.x: cast() should unsubscribe on crash eagerly

src/main/java/rx/internal/operators/OperatorFilter.java, src/main/java/rx/internal/operators/OperatorMap.java, src/test/java/rx/internal/operators/OperatorFilterTest.java, src/test/java/rx/internal/operators/OperatorMapTest.java
In current master, when the function in `map` or `filter` crashes, the error is propagated but the upstream is not immediately unsubscribed but expected to happen eventually due to some other operator or `SafeSubscriber`.
The fix, and also the restructuring of the unsubscription chain, makes sure the crash also unsubscribes immediately (unless a fatal one).
Related: [StackOverflow question](http://stackoverflow.com/questions/35343474/why-does-it-need-onbackpressure-here-for-click-events)
=> 1.x: map() and filter() should unsubscribe on crash eagerly

src/main/java/rx/Single.java, src/main/java/rx/internal/operators/SingleDoAfterTerminate.java, src/test/java/rx/internal/operators/SingleDoAfterTerminateTest.java
Resolves #3881.
The bug is caused by the impedance mismatch between `Observable`'s `Subscriber` and `Single`'s `SingleSubscriber`. The original code called `onNext()` which immediately signalled an `onSuccess` but also caused an unsubscription, preventing a delivery of `onCompleted()` in the inner Single.
The fix keeps `onSuccess`/`onError` rails intact  throughout the chain.
=> 1.x: fix multiple chained Single.doAfterTerminate not calling actions

src/main/java/rx/internal/operators/OnSubscribeToObservableFuture.java, src/test/java/rx/internal/operators/OnSubscribeToObservableFutureTest.java
The `from(Future)` operator was not refitted for backpressure.
Reported in: #3892.
=> 1.x: enable backpressure with from(Future).

src/main/java/rx/Completable.java, src/test/java/rx/CompletableTest.java
Fixed https://github.com/ReactiveX/RxJava/issues/3860
=> 1.x: Fix Completable swallows OnErrorNotImplementedException

src/main/java/rx/internal/operators/OperatorMerge.java, src/test/java/rx/internal/operators/OperatorFlatMapTest.java
This PR improves the overhead when one merges/flatMaps `empty()` sequences.
Benchmark results: (i7 4770K, Windows 7 x64, Java 8u72):
For rare `empty()`, the overhead seems to be around the noise level.
=> 1.x: optimize merge/flatMap for empty sources

src/main/java/rx/internal/operators/OperatorSingle.java, src/test/java/rx/internal/operators/OperatorSingleTest.java
Issue #3892 is a goldmine for missing backpressure problems. This PR fixes the case when `singleOrDefault` encounters an empty source and has to emit some default value. Fixed via setting the `SingleProducer` on the child on termination.
=> 1.x: fix singleOrDefault() backpressure if source is empty

src/main/java/rx/Observable.java, src/main/java/rx/internal/operators/OnSubscribeDetach.java, src/test/java/rx/internal/operators/OnSubscribeDetachTest.java
By default, operators have final link to their child Subscriber and they never clear the upstream's Producer. If the end subscriber is referenced, for example in a `CompositeSubscription`, that keeps an entire chain of objects alive and can cause memory leaks (a use case common on Android).
This proposed operator detaches the structures and nulls out references if the sequence terminates or the downstream unsubscribes - at the cost of atomic operations and mandatory volatile read for each onNext(). 
I know this issue has been brought up several times, but instead of adding the overhead to every operator, I propose an operator that can be applied when the developer really needs it (i.e., could be part of the usual compose(subscribeOn/observeOn) setup).
On the implementation side, this …
=> 1.x: proposal: onTerminateDetach - detach upstream/downstream for GC

src/main/java/rx/Observable.java, src/main/java/rx/internal/operators/OnSubscribeFlattenIterable.java, src/main/java/rx/internal/operators/OnSubscribeFromIterable.java, src/test/java/rx/internal/operators/OnSubscribeFlattenIterableTest.java
This PR reduces the overhead of `concatMapIterable`/`flatMapIterable` by not wrapping them into `Observable.from` sources but handling the generated `Iterable`s directly.
Since `Iterable`s are inherently synchronous, there is no difference between the two operators that now use the common underlying operator (i.e., flatMap can't chose a different source because it can't tell if an `Iterable` source is not ready or not; `hasNext()` is for indicating completion, not temporary lack of data).
Benchmark (i7 4790, Window 7 x64, Java 8u77):
`Iterable-M` is the current master, `Plain` is using `concatMap(Observable::from)` as a reference.
The `count=1` cases are bit slower because there is no good way of detecting if an `Iterable` holds only a single element, unlike with `just()`, and have to …
=> 1.x: optimize concatMapIterable/flatMapIterable

CHANGES.md
Release 1.1.4 CHANGES.md update.
:+1: for the release.
=> 1.x: Release 1.1.4 CHANGES.md update

src/main/java/rx/internal/operators/OperatorFilter.java, src/test/java/rx/internal/operators/OperatorFilterTest.java
Forgot that `Subscriber` defaults to requesting `Long.MAX_VALUE` unless suppressed and apparently there was no verification of filter's backpressure behavior; the two existing tests didn't really check for the delivery pattern.
=> 1.x: fix filter() default-requesting and thus going unbounded

src/main/java/rx/Single.java
=> 1.x: Single.retryWhen javadoc clarifications

src/main/java/rx/Observable.java
=> 1.x: DoOnUnsubscribe javadoc clarifications

src/main/java/rx/internal/util/ObjectPool.java
This PR fixed the `ObjectPool` dependency on the `Schedulers.computation()` which can be replaced via plugin hooks causing unexpected and long sleeps (i.e., when `computation()` is replaced by `immediate()`).
See #3923.
I'd also consider removing the `RxRingBuffer` entirely.
=> 1.x: fix RxRingBuffer-pool depending on the computation scheduler

src/main/java/rx/Subscriber.java
Somehow, Subscriber.NOT_SET was object `Long` instead of primitive `long`.
=> 1.x: Subscriber.NOT_SET Long -> long, saves an unboxing per instance

src/main/java/rx/internal/operators/OnSubscribeUsing.java, src/test/java/rx/internal/operators/OnSubscribeUsingTest.java
The operator `using` didn't call the resource cleanup code if the `observableFactory.call()` code crashed. In addition, a non-eager using didn't call the resource cleanup if one subscribed with `unsafeSubscribe` or the subscription to the generated `Observable` crashed.
Related: #3921
=> 1.x: fix using() resource cleanup when factory throws or being non-eager

src/main/java/rx/observers/TestObserver.java, src/main/java/rx/observers/TestSubscriber.java, src/test/java/rx/observers/TestSubscriberTest.java
This PR adds extra information to assertion failure messages on `TestSubscriber` and `TestObserver`, indicating:
- the listener didn't receive any `onCompleted` calls, which is an indication of hung or skipping operation,
- there were errors received, indicating a failure in the event generation process.
Previously, if there was something wrong with the sequence, the order and type of assertions were mostly unhelpful: if `assertValues` was first, the lack of values failure could hide a revealing onError call. If the `assertNoErrors()` was first, the error is visible but no way of knowing how far the sequence got.
Now, it is generally okay to use `assertValues` first, which along the difference, will print the lack of completion and the number of exceptions received, plus, the …
=> 1.x: TestSubscriber extra info on assertion failures

src/main/java/rx/Completable.java, src/main/java/rx/Single.java, src/main/java/rx/internal/operators/CompletableOnSubscribeConcat.java, src/main/java/rx/internal/operators/CompletableOnSubscribeConcatArray.java, src/main/java/rx/internal/operators/CompletableOnSubscribeConcatIterable.java, src/main/java/rx/internal/operators/CompletableOnSubscribeMerge.java, src/main/java/rx/internal/operators/CompletableOnSubscribeMergeArray.java, src/main/java/rx/internal/operators/CompletableOnSubscribeMergeDelayErrorArray.java, src/main/java/rx/internal/operators/CompletableOnSubscribeMergeDelayErrorIterable.java, src/main/java/rx/internal/operators/CompletableOnSubscribeMergeIterable.java, src/main/java/rx/internal/operators/CompletableOnSubscribeTimeout.java, src/main/java/rx/observers/SafeCompletableSubscriber.java, src/main/java/rx/plugins/RxJavaCompletableExecutionHook.java, src/main/java/rx/plugins/RxJavaPlugins.java, src/test/java/rx/CompletableTest.java, src/test/java/rx/SingleTest.java, src/test/java/rx/internal/operators/OnSubscribeCompletableTest.java, src/test/java/rx/plugins/RxJavaPluginsTest.java
Add option to safely subscribe a `CompletableSubscriber` / regular `Subscriber` and handle `onXXX` failures.
See also: #3938
Naming and whether or not the safe wrapping should be the default is open to discussion.
=> 1.x: add Completable.safeSubscribe option + RxJavaPlugins hook support

src/main/java/rx/internal/operators/OperatorWindowWithObservable.java, src/main/java/rx/internal/operators/OperatorWindowWithObservableFactory.java, src/main/java/rx/internal/operators/OperatorWindowWithSize.java, src/main/java/rx/internal/operators/OperatorWindowWithStartEndObservable.java, src/main/java/rx/internal/operators/OperatorWindowWithTime.java, src/main/java/rx/subjects/UnicastSubject.java, src/test/java/rx/internal/operators/OperatorConcatTest.java, src/test/java/rx/subjects/BufferUntilSubscriberTest.java
Plus, the unsubscribe indirection has been inlined, making `State` implement `Subscription` directly (instead of `Action0` + `Subscriptions.create`).
=> 1.x: promote UnicastSubject to be a standard+experimental Subject

src/main/java/rx/internal/operators/OperatorReplay.java, src/main/java/rx/internal/util/OpenHashSet.java, src/test/java/rx/internal/util/OpenHashSetTest.java
Reported in #3469.
This change will make sure whenever a new subscriber arrives, the
request coordination doesn't scan every other subscriber unnecessary.
(They will trigger a manageRequests individually anyway).
Unfortunately, I can't make the subscription registration constant (via a HashSet) because that would slow down the dispatching loop (which is quite expensive to for-each over compared to a plain array).
Note also that this will likely conflict with #3454.
I get the following numbers with the program in #3469.
```
subscribing...
subscribed so far 10000; took 54ms to subscribe last 10000 at rate: 185185 per sec...
subscribed so far 20000; took 110ms to subscribe last 10000 at rate: 90909 per sec...
subscribed so far 30000; took 157ms to subscribe last 10000 at rate: 63694 per …
```
=> 1.x: replay request coordination reduce overhead

src/main/java/rx/subjects/ReplaySubject.java, src/test/java/rx/subjects/ReplaySubjectTest.java
In addition, the behavior of time-limited mode has been changed. Late subscribers will now skip stale data.
Related issue: #3917
=> 1.x: ReplaySubject now supports backpressure

src/main/java/io/reactivex/schedulers/TestScheduler.java, src/test/java/io/reactivex/schedulers/TestSchedulerTest.java
This change is adding a bit of thread safety when some threads are trying to insert some actions while the time is changed in the TestScheduler
=> 2.x: Add support for concurrently inserting actions while advancing time

build.gradle, src/main/java/rx/Observable.java, src/main/java/rx/internal/operators/OperatorGroupBy.java, src/test/java/rx/internal/operators/OperatorGroupByTest.java
I have a long running stream using `groupBy` that over time will accumulate 10s of millions of keys. If I can specify an evicting map to `groupBy` then I'll be able to keep it down to ~10,000 keys. 
This PR supports this use case and could be used with Guava's `CacheBuilder` like this:
```java
Func1<Action1<K>, Map<K, Object>> mapFactory = 
action -> CacheBuilder.newBuilder()
.maximumSize(1000)
.expireAfterAccess(12, TimeUnit.HOUR)
.removalListener(key -> action.call(key))
.<K, Object> build().asMap();
observable
.groupBy(keySelector, elementSelector, mapFactory)
...
```
I'll enhance this PR with more unit tests if this looks a good direction.
=> 1.x: add groupBy overload with evictingMapFactory
