src/main/java/rx/internal/util/SynchronizedQueue.java

SynchronousQueue.clone fix

---

src/main/java/rx/internal/operators/OperatorWindowWithTime.java
src/test/java/rx/internal/operators/OperatorWindowWithTimeTest.java

Fixed off-by-one error and value-drop in the window operator.

---

src/test/java/rx/internal/operators/OperatorRetryTest.java

To discover the actual problem for issue #2560.

Retry backpressure test: split error conditions into separate test lines.

---

.travis.yml
gradle/buildViaTravis.sh
gradle/publishViaTravis.sh

Configuring Travis for build and release. This was tested at https://github.com/ReactiveX/BuildInfrastructure

Gradle & Travis Release Config

---

build.gradle
gradle/buildViaTravis.sh

Syntax error in build.gradle prevents PRs to be verified.

Fixed comment and missing value

---

gradle/buildViaTravis.sh

Master doesn't build because the lack of parameter for gradlew.

Make travis run a proper build.

---

src/main/java/rx/internal/operators/OnSubscribeRedo.java
src/test/java/rx/internal/operators/OperatorRepeatTest.java

Fix for repeat: wrong target of request

---

src/test/java/rx/internal/operators/OperatorRetryTest.java

Should fix the test recent test failures.

Fixed reentrancy issue with the error producer.

---

src/main/java/rx/internal/operators/OperatorPublish.java

Fix termination race condition in OperatorPublish.dispatch

---

src/main/java/rx/internal/util/PaddedAtomicIntegerBase.java
src/test/java/rx/ConcatTests.java
src/test/java/rx/internal/operators/OperatorBufferTest.java
src/test/java/rx/internal/operators/OperatorOnErrorReturnTest.java

Somehow, every second rebase I do I get this tab-space conversion which pollutes my PRs.

Replaced tabs with spaces for good.

---

src/main/java/rx/internal/operators/OnSubscribeAutoConnect.java

Fix autoConnect calling onStart twice.

---

src/main/java/rx/Single.java
src/test/java/rx/SingleTest.java

Adding `Single.toObservable` as companion to `Observable.toSingle`.

Single.toObservable

---

src/main/java/rx/internal/util/atomic/MpscLinkedAtomicQueue.java
src/main/java/rx/internal/util/atomic/SpscLinkedAtomicQueue.java
src/main/java/rx/internal/util/unsafe/MpmcArrayQueue.java
src/main/java/rx/internal/util/unsafe/MpscLinkedQueue.java
src/main/java/rx/internal/util/unsafe/SpmcArrayQueue.java
src/main/java/rx/internal/util/unsafe/SpscArrayQueue.java
src/main/java/rx/internal/util/unsafe/SpscLinkedQueue.java
src/test/java/rx/internal/util/JCToolsQueueTests.java

Increased test coverage of JCTools' queues and unsafe activities. Fixed inconsistencies in the queues.

Unit tests and cleanup of JCTools' queues.

---

src/test/java/rx/functions/ActionsTest.java
src/test/java/rx/functions/FunctionsTest.java

Since these are public API methods, their expected behavior needs to be verified.

Test coverage of rx.functions utility methods.

---

src/main/java/rx/functions/Actions.java

Remove redundant type parameter in EmptyAction

---

src/main/java/io/reactivex/internal/queue/BaseArrayQueue.java
src/main/java/io/reactivex/internal/queue/BaseLinkedQueue.java
src/main/java/io/reactivex/internal/queue/LinkedQueueNode.java
src/main/java/io/reactivex/internal/queue/MpscLinkedQueue.java
src/main/java/io/reactivex/internal/queue/SpscArrayQueue.java
src/main/java/io/reactivex/internal/queue/SpscExactArrayQueue.java
src/main/java/io/reactivex/internal/queue/SpscLinkedArrayQueue.java
src/main/java/io/reactivex/internal/util/Pow2.java

Spsc:
- power-of-2 array
- exact capacity array
- linked array
Mpsc:
- linked

Some safe queue implementations

---

src/main/java/io/reactivex/Observable.java
src/main/java/io/reactivex/internal/util/AppendOnlyLinkedArrayList.java
src/main/java/io/reactivex/internal/util/BackpressureHelper.java
src/main/java/io/reactivex/internal/util/NotificationLite.java
src/main/java/io/reactivex/internal/util/QueueDrainHelper.java
src/main/java/io/reactivex/internal/util/TerminalAtomicsHelper.java
src/main/java/io/reactivex/subjects/AsyncSubject.java
src/main/java/io/reactivex/subjects/PublishSubject.java
src/main/java/io/reactivex/subjects/SerializedSubject.java
src/main/java/io/reactivex/subjects/Subject.java

We can use `Publisher` directly and no need for `OnSubscribe`. `Operator` is still quite a convenience.

PublishSubject, AsyncSubject and a few helper classes

---

src/main/java/io/reactivex/disposables/Disposable.java
src/main/java/io/reactivex/internal/disposables/ArrayCompositeResource.java
src/main/java/io/reactivex/internal/disposables/ListCompositeResource.java
src/main/java/io/reactivex/internal/disposables/MultipleAssignmentResource.java
src/main/java/io/reactivex/internal/disposables/SerialResource.java
src/main/java/io/reactivex/internal/disposables/SetCompositeResource.java
src/main/java/io/reactivex/internal/util/AppendOnlyLinkedArrayList.java
src/main/java/io/reactivex/internal/util/NotificationLite.java
src/main/java/io/reactivex/internal/util/OpenHashSet.java
src/main/java/io/reactivex/internal/util/TerminalAtomicsHelper.java

Mostly internal addition plus the public `Disposable` interface.
Naming of packages and classes can be changed at any time if one wishes...

Disposable interface and a bunch of general resource containers.

---

src/main/java/io/reactivex/Scheduler.java
src/main/java/io/reactivex/internal/disposables/ArrayCompositeResource.java
src/main/java/io/reactivex/internal/disposables/CompositeResource.java
src/main/java/io/reactivex/internal/disposables/EmptyDisposable.java
src/main/java/io/reactivex/internal/disposables/ListCompositeResource.java
src/main/java/io/reactivex/internal/disposables/SetCompositeResource.java
src/main/java/io/reactivex/internal/schedulers/ExecutorScheduler.java
src/main/java/io/reactivex/internal/schedulers/RxThreadFactory.java
src/main/java/io/reactivex/internal/schedulers/ScheduledRunnable.java
src/main/java/io/reactivex/internal/schedulers/SchedulerLifecycle.java
src/main/java/io/reactivex/internal/schedulers/SingleScheduler.java
src/main/java/io/reactivex/schedulers/Schedulers.java
src/main/java/io/reactivex/schedulers/TestScheduler.java

incomplete.
This PR has a few TODO questions that require decisions.

Schedulers (a few) + API, slight modifications to other classes,

---

src/main/java/io/reactivex/Observable.java
src/main/java/io/reactivex/internal/operators/PublisherArraySource.java
src/main/java/io/reactivex/internal/operators/PublisherCompletableFutureSource.java
src/main/java/io/reactivex/internal/operators/PublisherDefer.java
src/main/java/io/reactivex/internal/operators/PublisherEmptySource.java
src/main/java/io/reactivex/internal/operators/PublisherErrorSource.java
src/main/java/io/reactivex/internal/operators/PublisherIterableSource.java
src/main/java/io/reactivex/internal/operators/PublisherRangeSource.java
src/main/java/io/reactivex/internal/operators/PublisherScalarAsyncSource.java
src/main/java/io/reactivex/internal/operators/PublisherScalarSource.java
src/main/java/io/reactivex/internal/operators/PublisherStreamSource.java
src/main/java/io/reactivex/internal/subscriptions/EmptySubscription.java
src/main/java/io/reactivex/internal/subscriptions/ScalarAsyncSubscription.java
src/main/java/io/reactivex/internal/subscriptions/ScalarSubscription.java

Added a bunch of basic event sources and helper Subscription

---

src/main/java/io/reactivex/Observable.java
src/main/java/io/reactivex/plugins/RxJavaPlugins.java
src/main/java/io/reactivex/subjects/AsyncSubject.java
src/main/java/io/reactivex/subjects/PublishSubject.java
src/main/java/io/reactivex/subjects/SerializedSubject.java
src/main/java/io/reactivex/subscribers/SafeSubscriber.java
src/main/java/io/reactivex/subscribers/SerializedSubscriber.java

- SafeSubscriber
- SerializedSubscriber
- RxJavaPlugins (partial)

Basic Subscribers and plugin class

---

src/main/java/io/reactivex/Observable.java
src/main/java/io/reactivex/internal/operators/OperatorFlatMap.java
src/main/java/io/reactivex/internal/operators/OperatorMap.java

With all `flatMap`, `merge` and `mergeDelayError` overloads.

Operators map and flatMap

---

src/main/java/io/reactivex/Observable.java
src/main/java/io/reactivex/Observer.java
src/main/java/io/reactivex/internal/operators/OperatorIgnoreElements.java
src/main/java/io/reactivex/internal/operators/OperatorTake.java
src/main/java/io/reactivex/internal/operators/OperatorTakeLast.java
src/main/java/io/reactivex/internal/operators/OperatorTakeLastOne.java
src/main/java/io/reactivex/internal/operators/OperatorTakeUntil.java
src/main/java/io/reactivex/internal/operators/OperatorTakeUntilPredicate.java
src/main/java/io/reactivex/internal/operators/PublisherArraySource.java
src/main/java/io/reactivex/internal/operators/PublisherIterableSource.java
src/main/java/io/reactivex/internal/operators/PublisherRangeSource.java
src/main/java/io/reactivex/internal/operators/PublisherStreamSource.java
src/main/java/io/reactivex/internal/schedulers/ScheduledRunnable.java
src/main/java/io/reactivex/internal/subscriptions/EmptySubscription.java
src/main/java/io/reactivex/internal/subscriptions/ScalarAsyncSubscription.java
src/main/java/io/reactivex/internal/subscriptions/ScalarSubscription.java

Operators of take (untimed), plugin error reporting fix for other

---

src/main/java/io/reactivex/Observable.java
src/main/java/io/reactivex/internal/operators/OperatorSkipUntil.java

Forgot to add them in the previous PR.

The skips and filter operators added to Observable

---

src/main/java/io/reactivex/Observable.java
src/main/java/io/reactivex/internal/operators/CancelledSubscriber.java
src/main/java/io/reactivex/internal/operators/OperatorToList.java

`toSortedList` is implemented with `toList().map()`.

Operator toList and toSortedList

---

src/main/java/io/reactivex/Observable.java
src/main/java/io/reactivex/internal/disposables/SerialResource.java
src/main/java/io/reactivex/internal/operators/CachedObservable.java
src/main/java/io/reactivex/internal/operators/OperatorPublish.java
src/main/java/io/reactivex/internal/operators/OperatorReplay.java
src/main/java/io/reactivex/internal/operators/SubscriberResourceWrapper.java
src/main/java/io/reactivex/internal/util/LinkedArrayList.java
src/main/java/io/reactivex/schedulers/Timestamped.java

I'm not 100% certain about the the timing of the onSubscribe() calls inside the operators; I'll have a second run over them once the tests are also added.

Operators publish, replay and cache.

---

src/main/java/io/reactivex/Observable.java
src/main/java/io/reactivex/internal/operators/OperatorAll.java
src/main/java/io/reactivex/internal/operators/OperatorAny.java
src/main/java/io/reactivex/internal/operators/OperatorCount.java
src/main/java/io/reactivex/internal/operators/OperatorElementAt.java
src/main/java/io/reactivex/internal/operators/OperatorSingle.java

Operators all, any, count, elementAt, single

---

src/main/java/io/reactivex/Scheduler.java
src/main/java/io/reactivex/internal/schedulers/ComputationScheduler.java
src/main/java/io/reactivex/internal/schedulers/ExecutorScheduler.java
src/main/java/io/reactivex/internal/schedulers/IOScheduler.java
src/main/java/io/reactivex/internal/schedulers/NewThreadScheduler.java
src/main/java/io/reactivex/internal/schedulers/NewThreadWorker.java
src/main/java/io/reactivex/internal/schedulers/ScheduledRunnable.java
src/main/java/io/reactivex/internal/schedulers/SingleScheduler.java
src/main/java/io/reactivex/internal/schedulers/TrampolineScheduler.java
src/main/java/io/reactivex/plugins/RxJavaPlugins.java
src/main/java/io/reactivex/schedulers/Schedulers.java
src/main/java/io/reactivex/schedulers/TestScheduler.java

+ updated RxJavaPlugins and added decorator calls to the Schedulers.

All standard schedulers ported and cleaned up.

---

src/main/java/io/reactivex/Observable.java
src/main/java/io/reactivex/internal/operators/ConcatMap.java
src/main/java/io/reactivex/internal/subscriptions/SubscriptionArbiter.java

This includes
- concatMap
- concat
- startWith
- endWith
- concatWith
- mergeWith (via merge)

Operator concatMap and related convenience methods

---

src/main/java/io/reactivex/internal/subscribers/EmptySubscriber.java
src/main/java/io/reactivex/subscribers/TestSubscriber.java

TestSubscriber implemented

---

src/main/java/io/reactivex/Observable.java
src/main/java/io/reactivex/internal/operators/PublisherRepeat.java
src/main/java/io/reactivex/internal/operators/PublisherRepeatUntil.java
src/main/java/io/reactivex/internal/operators/PublisherRetryPredicate.java
src/main/java/io/reactivex/internal/subscriptions/SubscriptionArbiter.java

I'll post the `retryWhen` and `repeatWhen` separately.

Some Repeat + Retry methods, fix to SubscriptionArbiter.

---

src/main/java/io/reactivex/Observable.java
src/main/java/io/reactivex/internal/operators/PublisherIntervalOnceSource.java
src/main/java/io/reactivex/internal/operators/PublisherIntervalRangeSource.java
src/main/java/io/reactivex/internal/operators/PublisherIntervalSource.java

`intervalRange` helps when one needs a fixed amount of timed values and wants to avoid map+take overhead.

Operators interval and intervalRange

---

src/main/java/io/reactivex/Observable.java
src/main/java/io/reactivex/functions/Function3.java
src/main/java/io/reactivex/functions/Function4.java
src/main/java/io/reactivex/functions/Function5.java
src/main/java/io/reactivex/functions/Function6.java
src/main/java/io/reactivex/functions/Function7.java
src/main/java/io/reactivex/functions/Function8.java
src/main/java/io/reactivex/functions/Function9.java
src/main/java/io/reactivex/internal/operators/PublisherZip.java

FunctionX extends Function<Object[], R> and the default method for it unpacks the array.

Operator zip plus Function3..Function9.

---

src/main/java/io/reactivex/internal/operators/OperatorFlatMap.java
src/main/java/io/reactivex/subscribers/TestSubscriber.java

Strenghtening flatMap against misbehaving sources, TestSubscriber +

---

src/main/java/io/reactivex/Observable.java
src/main/java/io/reactivex/Try.java
src/main/java/io/reactivex/internal/operators/PublisherZip.java
src/main/java/io/reactivex/internal/queue/BaseArrayQueue.java

Also corrected the naming of one-shot timer and fixed-period interval

Fixes to classes, convenience operators mostly.

---

src/main/java/io/reactivex/Observable.java
src/main/java/io/reactivex/internal/operators/OperatorCollect.java

I know `toList` can be also implemented this way but its frequent use makes it eligible for a custom operator.

Operator collect, toMap and toMultimap based on it.

---

src/main/java/io/reactivex/Observable.java

javac is unable to select the right overload for some reason

collect: javac is unable to select the right overload for some reason

---

src/main/java/io/reactivex/Observable.java
src/main/java/io/reactivex/internal/operators/OperatorSamplePublisher.java
src/main/java/io/reactivex/internal/operators/OperatorSampleTimed.java

I'd like to state that I try to use `Publisher` as much as possible: this adds the benefit that RxJava can use someone else's publisher without the explicit need to wrap it into an `Observable` all the time.

Operator sample with time or with another publisher

---

src/main/java/io/reactivex/Observable.java
src/main/java/io/reactivex/internal/operators/OperatorSkipLastTimed.java
src/main/java/io/reactivex/internal/operators/OperatorTakeLastTimed.java

+ bufferSize +delayError options, as usual by now

Operator takeLast time + size, skipLast time

---

src/main/java/io/reactivex/Observable.java
src/main/java/io/reactivex/internal/operators/PublisherAmb.java

Very similar to zip in terms of structure.

Operator amb, ambWith

---

src/main/java/io/reactivex/Observable.java
src/main/java/io/reactivex/internal/operators/OperatorOnErrorNext.java
src/main/java/io/reactivex/internal/operators/OperatorOnErrorReturn.java
src/main/java/io/reactivex/internal/subscriptions/SubscriptionArbiter.java

Operators onErrorReturn, onErrorResumeNext, onExceptionResumeNext

---

src/main/java/io/reactivex/Notification.java
src/main/java/io/reactivex/Observable.java
src/main/java/io/reactivex/internal/operators/OperatorOnErrorNext.java
src/main/java/io/reactivex/internal/operators/PublisherRedo.java
src/main/java/io/reactivex/internal/subscribers/ToNotificationSubscriber.java

+ a fix to OperatorOnErrorNext

Operator retryWhen, repeatWhen; Notification

---

src/main/java/io/reactivex/Observable.java
src/main/java/io/reactivex/internal/operators/PublisherSequenceEqual.java

Inlined (no zipping and wrapping like in 1.x)

Operator sequenceEqual

---

src/main/java/io/reactivex/Observable.java
src/main/java/io/reactivex/internal/operators/PublisherCombineLatest.java

+ Some minor internal refactorings in `Observable`.

Operator combineLatest

---

src/main/java/io/reactivex/Notification.java
src/main/java/io/reactivex/Observable.java
src/main/java/io/reactivex/internal/operators/OperatorDematerialize.java
src/main/java/io/reactivex/internal/operators/OperatorMaterialize.java
src/main/java/io/reactivex/internal/operators/PublisherRedo.java
src/main/java/io/reactivex/internal/subscribers/ToNotificationSubscriber.java

`Optional.ofNullable` returns an empty instance, not a null-containing one.

Operator materialize, dematerialize, minor notification fix.

---

src/main/java/io/reactivex/Observable.java
src/main/java/io/reactivex/internal/operators/OperatorDelay.java

The `delaySubscription` is implemented via composition.

Operators delay, delaySubscription, share.

---

src/main/java/io/reactivex/Observable.java
src/main/java/io/reactivex/internal/operators/BlockingOperatorLatest.java
src/main/java/io/reactivex/internal/operators/BlockingOperatorMostRecent.java
src/main/java/io/reactivex/internal/operators/BlockingOperatorNext.java
src/main/java/io/reactivex/internal/subscribers/BlockingSubscriber.java
src/main/java/io/reactivex/internal/subscribers/DisposableSubscriber.java
src/main/java/io/reactivex/internal/util/Exceptions.java
src/main/java/io/reactivex/observables/BlockingObservable.java

subscribe, stream, forEach, iterator
Now it extends both Publisher and Iterable directly.

BlockingObservable, next, latest, mostRecent, first, last, single,

---

src/main/java/io/reactivex/Observable.java
src/main/java/io/reactivex/internal/operators/PublisherRefCount.java
src/main/java/io/reactivex/observables/ConnectableObservable.java

Operator refCount

---

src/main/java/io/reactivex/Observable.java
src/main/java/io/reactivex/internal/operators/OperatorBuffer.java
src/main/java/io/reactivex/internal/operators/OperatorBufferTimed.java

The boundary version will come next.

Operators buffer: size, time, size + time

---

src/main/java/io/reactivex/Observable.java
src/main/java/io/reactivex/internal/operators/OperatorWindow.java
src/main/java/io/reactivex/subjects/UnicastSubject.java

Luckily, there is no need to count the emission per subject but just use
arithmetic.

Window with count, count + skip.

---

src/main/java/io/reactivex/Observable.java
src/main/java/io/reactivex/internal/operators/OperatorBufferBoundary.java
src/main/java/io/reactivex/internal/operators/OperatorBufferTimed.java
src/main/java/io/reactivex/internal/operators/OperatorWindowTimed.java
src/main/java/io/reactivex/internal/subscribers/QueueDrainSubscriber.java

The timed buffer and window operators are quite complicated in terms of
concurrency. I'm not sure if all corner cases are covered.

Operator window timespan, timespan + count, timespan + timeskip

---

src/main/java/io/reactivex/Observable.java
src/main/java/io/reactivex/internal/operators/OperatorDebounce.java
src/main/java/io/reactivex/internal/operators/OperatorDebounceTimed.java

(Taking a break from `window()` operators.)

Operator debounce (time, selector), throttleWithTimeout (alias)

---

src/main/java/io/reactivex/Observable.java
src/main/java/io/reactivex/internal/operators/OperatorScan.java
src/main/java/io/reactivex/internal/operators/OperatorScanSeed.java
src/main/java/io/reactivex/internal/subscribers/QueueDrainSubscriber.java
src/main/java/io/reactivex/subscribers/TestSubscriber.java

TestSubscriber now does asynchronous requests and cancellation.

Operator scan, reduce. Fixes to TestSubscriber async behavior.

---

src/main/java/io/reactivex/Observable.java
src/main/java/io/reactivex/internal/operators/OperatorDebounce.java
src/main/java/io/reactivex/internal/operators/OperatorThrottleFirstTimed.java

I've implemented the wrong debounce logic in #3254 .

Fixed debounce behavior, added throttleFirst, throttleLast alias

---

src/main/java/io/reactivex/subjects/ReplaySubject.java

Has full backpressure support (replays as many elements as requested).

ReplaySubject

---

src/main/java/io/reactivex/subjects/BehaviorSubject.java
src/main/java/io/reactivex/subjects/ReplaySubject.java

ReplaySubject: time and size bound trimming was incorrectly deleting the terminal notification
BehaviorSubject: double emission of the same value. The following loop fails (prints `Bad pattern received: [2, 2]`) with 1.x:
```java
for (int i = 0; i < 1_000_000; i++) {
if (i % 1000 == 0) {
System.out.println("--> " + i);
}
BehaviorSubject<Object> bs = BehaviorSubject.create(1);
List<Object> list = new ArrayList<>();
CyclicBarrier cb = new CyclicBarrier(2);
CountDownLatch cdl = new CountDownLatch(1);
ForkJoinPool.commonPool().submit(() -> {
cb.await();
bs.onNext(2);
cdl.countDown();
return null;
});
cb.await();
bs.subscribe(v -> list.add(v));
cdl.await();
if (Arrays.asList(2).equals(list)) {
continue;
}
if (Arrays.asList(1, 2).equals(list)) {
continue;
}
System.out.println("Bad pattern …
```

Fixes to ReplaySubject and BehaviorSubject.

---

src/main/java/io/reactivex/plugins/RxJavaPlugins.java

By using null checks and direct returns we can avoid a dynamic dispatch
on a volatile variable which always more expensive.
I've also added the `lockdown()` method to prevent any further changing
of the plugin handlers. There is a `unlock` package-private method to
allow testing the plugin in the locked state and then return to the
unlocked state as other tests may want to install custom plugins.

RxJavaPlugins performance enabling fix & lockdown.

---

src/main/java/io/reactivex/disposables/BooleanDisposable.java
src/main/java/io/reactivex/disposables/CompositeDisposable.java
src/main/java/io/reactivex/disposables/Disposables.java
src/main/java/io/reactivex/disposables/MultipleAssignmentDisposable.java
src/main/java/io/reactivex/disposables/RefCountDisposable.java
src/main/java/io/reactivex/disposables/SerialDisposable.java
src/main/java/io/reactivex/internal/disposables/MultipleAssignmentResource.java
src/main/java/io/reactivex/internal/disposables/SerialResource.java
src/main/java/io/reactivex/internal/disposables/SetCompositeResource.java

+ `Disposables` utility class with wrapper methods named `from`.

Standard disposables, changes to resource containers to support them.

---

build.gradle
src/main/java/io/reactivex/exceptions/MissingBackpressureException.java
src/main/java/io/reactivex/internal/operators/OperatorDoOnEach.java
src/main/java/io/reactivex/internal/operators/OperatorFlatMap.java
src/main/java/io/reactivex/internal/operators/OperatorObserveOn.java
src/main/java/io/reactivex/internal/operators/PublisherLift.java
src/main/java/io/reactivex/internal/operators/PublisherSubscribeOn.java
src/main/java/io/reactivex/internal/schedulers/ScheduledRunnable.java
src/main/java/io/reactivex/internal/util/Exceptions.java
src/main/java/io/reactivex/internal/util/Pow2.java
src/main/java/io/reactivex/internal/util/QueueDrain.java
src/main/java/io/reactivex/subscribers/AsyncObserver.java
src/main/java/io/reactivex/subscribers/TestSubscriber.java
src/test/java/io/reactivex/BackpressureTests.java

Fixed mistakes in the operators.

First unit test and fixes to operators.

---

src/main/java/io/reactivex/internal/subscribers/EmptySubscriber.java
src/main/java/io/reactivex/subscribers/TestSubscriber.java
src/test/java/io/reactivex/BackpressureTests.java

Either the test is non-deterministic or I still have a bug.

Fix attempt to the firehose test.

---

src/main/java/io/reactivex/Observable.java
src/main/java/io/reactivex/internal/operators/OperatorGroupBy.java
src/test/java/io/reactivex/CombineLatestTests.java
src/test/java/io/reactivex/CovarianceTest.java

Forgot to deliver the value inside the GroupedUnicast drain loop.

Simplest combineLatest tests and fix to groupBy.

---

src/main/java/io/reactivex/Notification.java
src/test/java/io/reactivex/GroupByTests.java
src/test/java/io/reactivex/MergeTests.java
src/test/java/io/reactivex/NotificationTest.java

We need to talk about `Notification`s.

Simplest tests of groupBy, merge and Notification

---

src/main/java/io/reactivex/internal/operators/OperatorScanSeed.java
src/main/java/io/reactivex/internal/operators/OperatorSingle.java
src/main/java/io/reactivex/internal/operators/OperatorTakeLastOne.java
src/main/java/io/reactivex/internal/subscribers/QueueDrainSubscriber.java
src/main/java/io/reactivex/subscribers/TestSubscriber.java
src/test/java/io/reactivex/ObservableConversionTest.java
src/test/java/io/reactivex/ObservableDoOnTest.java

Forgot to call request, refactored some validation code.

ConversionTest and DoOnTest

---

src/main/java/io/reactivex/Observable.java
src/main/java/io/reactivex/internal/operators/OperatorDematerialize.java
src/main/java/io/reactivex/internal/operators/OperatorFilter.java
src/main/java/io/reactivex/internal/operators/OperatorMaterialize.java
src/main/java/io/reactivex/internal/operators/OperatorScan.java
src/main/java/io/reactivex/internal/operators/OperatorScanSeed.java
src/main/java/io/reactivex/internal/operators/OperatorTake.java
src/main/java/io/reactivex/internal/operators/PublisherAmb.java
src/main/java/io/reactivex/internal/operators/PublisherArraySource.java
src/main/java/io/reactivex/observables/BlockingObservable.java
src/main/java/io/reactivex/observables/ConnectableObservable.java
src/main/java/io/reactivex/subjects/ReplaySubject.java
src/main/java/io/reactivex/subscribers/TestSubscriber.java
src/test/java/io/reactivex/MergeTests.java
src/test/java/io/reactivex/ObservableConversionTest.java
src/test/java/io/reactivex/ObservableTests.java

ObservableTests and bugfixes.

---

src/main/java/io/reactivex/Observable.java
src/test/java/io/reactivex/ObservableTests.java
src/test/java/io/reactivex/ObservableWindowTests.java
src/test/java/io/reactivex/ReduceTests.java
src/test/java/io/reactivex/ScanTests.java
src/test/java/io/reactivex/StartWithTests.java
src/test/java/io/reactivex/TestHelper.java

I've refectored the mockSubscriber method out into a helper enum since it will be required almost everywhere.

Simpler tests for window reduce, scan, starWith.

---

src/main/java/io/reactivex/Observable.java
src/main/java/io/reactivex/internal/operators/OperatorDebounceTimed.java
src/test/java/io/reactivex/ThrottleLastTests.java
src/test/java/io/reactivex/ThrottleWithTimeoutTests.java
src/test/java/io/reactivex/ZipTests.java

Tests expect certain operator parameter orders so I'd expect a few changes in Observable in this regard.
Fixed timing bug with `throttleWithTimeout` but I'm not 100% certain it works as expected beyond this single test.

Simpler tests of throttleLast, throttleWithTimeout, zip

---

src/main/java/io/reactivex/internal/operators/CachedObservable.java
src/main/java/io/reactivex/internal/operators/OperatorSkipUntil.java
src/main/java/io/reactivex/internal/operators/OperatorTakeUntil.java
src/test/java/io/reactivex/internal/operators/BufferUntilSubscriberTest.java
src/test/java/io/reactivex/internal/operators/CachedObservableTest.java
src/test/java/io/reactivex/internal/operators/NotificationLiteTest.java
src/test/java/io/reactivex/internal/operators/OnSubscribeAmbTest.java

+ bugfix to cache, skipUntil and takeUnit

Test some UnicastSubject, cache, NotificationLite, amb

---

src/main/java/io/reactivex/internal/operators/PublisherFutureSource.java
src/main/java/io/reactivex/internal/operators/PublisherUsing.java
src/main/java/io/reactivex/observables/BlockingObservable.java
src/test/java/io/reactivex/internal/operators/OnSubscribeToObservableFutureTest.java
src/test/java/io/reactivex/internal/operators/OnSubscribeUsingTest.java

expectations
Some tests are now skipped due to being invalid in RS.

2.x: test for toFuture and using, changes according to the test

---

src/main/java/io/reactivex/BackpressureStrategy.java
src/main/java/io/reactivex/NbpObservable.java
src/main/java/io/reactivex/Single.java
src/main/java/io/reactivex/internal/operators/nbp/NbpOperatorFlatMap.java
src/main/java/io/reactivex/internal/operators/nbp/NbpOperatorMap.java
src/main/java/io/reactivex/internal/operators/single/SingleOperatorFlatMap.java
src/main/java/io/reactivex/internal/operators/single/SingleOperatorMap.java
src/main/java/io/reactivex/internal/util/AppendOnlyLinkedArrayList.java
src/test/java/io/reactivex/NbpObservableTest.java

`Single` is a deferred single-value emitting Observable.
`NbpObservable` is the non-backpressure Observable, named this way until
the main Observable gets all its tests ported so a refactor can deal
with all of them.
I've implemented the most basic construction and operator methods on
them.

2.x: classes Single and NbpObservable

---

src/main/java/io/reactivex/Observable.java
src/main/java/io/reactivex/internal/operators/OperatorElementAt.java
src/test/java/io/reactivex/internal/operators/OperatorElementAtTest.java
src/test/java/io/reactivex/internal/operators/OperatorFilterTest.java
src/test/java/io/reactivex/internal/operators/OperatorFinallyTest.java
src/test/java/io/reactivex/internal/operators/OperatorFirstTest.java

+ fixed exceptions throw by elementAt

2.x: operator test elementAt, filter, finally, first

---

src/main/java/io/reactivex/internal/operators/OperatorReplay.java
src/main/java/io/reactivex/internal/operators/SubscriberResourceWrapper.java
src/test/java/io/reactivex/internal/operators/OperatorPublishTest.java
src/test/java/io/reactivex/internal/operators/OperatorReduceTest.java
src/test/java/io/reactivex/internal/operators/OperatorRepeatTest.java
src/test/java/io/reactivex/internal/operators/OperatorReplayTest.java

Note that testIssue_2191_SchedulerUnsubscribe had to change the call
count to pass. I don't understand this test and the over-mocking (but
recognize the style).

2.x: operator test for replay

---

src/main/java/io/reactivex/Observable.java
src/main/java/io/reactivex/internal/operators/OperatorTakeLast.java
src/main/java/io/reactivex/internal/operators/OperatorTakeLastTimed.java
src/test/java/io/reactivex/internal/operators/OperatorMergeTest.java
src/test/java/io/reactivex/internal/operators/OperatorTakeLastOneTest.java
src/test/java/io/reactivex/internal/operators/OperatorTakeLastTest.java
src/test/java/io/reactivex/internal/operators/OperatorTakeLastTimedTest.java
src/test/java/io/reactivex/internal/operators/OperatorTakeTest.java
src/test/java/io/reactivex/internal/operators/OperatorTakeTimedTest.java
src/test/java/io/reactivex/internal/operators/OperatorTakeUntilPredicateTest.java
src/test/java/io/reactivex/internal/operators/OperatorTakeUntilTest.java
src/test/java/io/reactivex/internal/operators/OperatorTakeWhileTest.java

+ fixed a deadlock possibility in one of the merge tests

2.x: operator tests: take family + fixes

---

src/main/java/io/reactivex/internal/schedulers/NewThreadWorker.java
src/main/java/io/reactivex/subjects/AsyncSubject.java
src/main/java/io/reactivex/subjects/BehaviorSubject.java
src/main/java/io/reactivex/subjects/ReplaySubject.java
src/test/java/io/reactivex/internal/operators/OperatorConcatTest.java
src/test/java/io/reactivex/internal/operators/OperatorZipTest.java
src/test/java/io/reactivex/subjects/AsyncSubjectTest.java
src/test/java/io/reactivex/subjects/BehaviorSubjectTest.java
src/test/java/io/reactivex/subjects/PublishSubjectTest.java
src/test/java/io/reactivex/subjects/ReplaySubjectBoundedConcurrencyTest.java
src/test/java/io/reactivex/subjects/ReplaySubjectConcurrencyTest.java
src/test/java/io/reactivex/subjects/ReplaySubjectTest.java
src/test/java/io/reactivex/subjects/SerializedSubjectTest.java
src/test/java/io/reactivex/subscribers/SafeSubscriberTest.java

+ Fixed the `testNestedAsyncConcat` test.
+ Fixed memory leak in `NewThreadWorker`.

2.x: subject tests and bugfixes

---

src/main/java/io/reactivex/NbpObservable.java
src/main/java/io/reactivex/Single.java
src/main/java/io/reactivex/internal/operators/single/SingleOperatorFlatMap.java
src/main/java/io/reactivex/internal/operators/single/SingleOperatorMap.java
src/perf/java/io/reactivex/LatchedSingleObserver.java
src/test/java/io/reactivex/SingleTest.java

I've added the methods from the 1.x Single plus a couple more based on Observable operators that makes sense to me in respect to Single. No plus unit tests and no javadoc.

2.x: Single class more operators + test from 1.x

---

src/main/java/rx/Observable.java

sigificent -> significant
alreay -> already

Fix typo in a comment inside Observable.subscribe

---

src/main/java/rx/internal/operators/BufferUntilSubscriber.java

Compiler, VM, JIT and IDE will be happier :)

Fix synchronization on non-final field in BufferUntilSubscriber

---

src/main/java/rx/internal/schedulers/EventLoopsScheduler.java
src/main/java/rx/internal/schedulers/GenericScheduledExecutorService.java
src/main/java/rx/internal/schedulers/NewThreadWorker.java
src/main/java/rx/internal/schedulers/SchedulerLifecycle.java
src/main/java/rx/internal/util/ObjectPool.java
src/main/java/rx/internal/util/RxRingBuffer.java
src/main/java/rx/schedulers/CachedThreadScheduler.java
src/main/java/rx/schedulers/ExecutorScheduler.java
src/main/java/rx/schedulers/Schedulers.java
src/test/java/rx/internal/schedulers/SchedulerLifecycleTest.java
src/test/java/rx/schedulers/SchedulerLifecycleTest.java

Scheduler shutdown capability

---

src/main/java/rx/internal/operators/OperatorZip.java
src/test/java/rx/internal/operators/OperatorZipTest.java

1.x: fix for zip(Obs<Obs<T>>) backpressure problem

---

src/main/java/rx/Observable.java

fix subscribe() javadoc 

---

src/main/java/rx/internal/operators/OperatorZipIterable.java

1.x: Don't swallow fatal errors in OperatorZipIterable

---

src/main/java/io/reactivex/internal/operators/PublisherCombineLatest.java
src/main/java/io/reactivex/internal/operators/nbp/NbpOnSubscribeCombineLatest.java

A terminal condition is now clearing the latest array which should help release its contents earlier in case a reference is kept to the class.

2.x: CombineLatest removed leftover debug field + better cleanup

---

README.md

1.x: adding source links for @Beta and @Experimental

---

src/main/java/rx/observers/Subscribers.java

1.x: fix Subscribers.create(onNext) javadoc

---

src/main/java/rx/internal/operators/OperatorPublish.java

Fix various misspellings in OperatorPublish

---

src/main/java/rx/exceptions/Exceptions.java

1.x: javadoc for rx.exceptions.Exceptions

---

src/main/java/rx/Producer.java

1.x: javadoc for Producer

---

src/main/java/rx/Completable.java
src/main/java/rx/internal/operators/CompletableOnSubscribeMerge.java
src/test/java/rx/CompletableTest.java

The upgraded gradle switched my IDE to use a JDK 6 library I have installed all along and these popped up immediately.

1.x: Fix Completable using JDK 7 suppressed exceptions feature

---

README.md

1.x: #3618 adding source links for @Beta and @Experimental

---

src/test/java/rx/ObservableTests.java

I hope this fixes the test once and for all.

1.x: fix attempt 2 for testErrorThrownIssue1685

---

src/test/java/rx/observers/SerializedObserverTest.java

This PR fixes the `SerializedObserverTest.testNotificationDelay` test to use reentrancy to verify the buffer in `SerializedObserver` is properly drained. For now, it loops 10,000 times to see if the CI brings up the issue again. Takes 400ms on my machine but I'll probably reduce it to 1,000 times.
(The previous version was a bit convoluted with all those countdowns that didn't properly lock out the other thread).
Reported in issue #1389

1.x: fix SerializedObserverTest.testNotificationDelay

---

src/test/java/rx/internal/operators/OperatorObserveOnTest.java

The test had some non-deterministic machinery to trigger the failure.

1.x: Fix ObserveOnTest. testQueueFullEmitsErrorWithVaryingBufferSize

---

src/main/java/rx/plugins/RxJavaPlugins.java

1.x: make defensive copy of the properties in RxJavaPlugins

---

src/main/java/rx/Observable.java
src/main/java/rx/internal/operators/OperatorEagerConcatMap.java
src/test/java/rx/internal/operators/OperatorEagerConcatMapTest.java

1.x: Add maxConcurrent parameter to concatMapEager

---

src/main/java/rx/internal/operators/OperatorOnBackpressureBuffer.java

remove unused field baseCapacity from onBackpressureBuffer

---

src/main/java/rx/observers/TestObserver.java
src/test/java/rx/observers/TestObserverTest.java
src/test/java/rx/observers/TestSubscriberTest.java

Otherwise you have to manually print/debug values if test failed.

1.x: TestSubscriber/TestObserver print values if number of items doesn't match

---

src/main/java/rx/internal/operators/OnSubscribeFromCallable.java
src/main/java/rx/internal/operators/OperatorTakeLastOne.java
src/main/java/rx/internal/operators/SingleOnSubscribeUsing.java
src/main/java/rx/internal/operators/SingleOperatorOnErrorResumeNext.java
src/main/java/rx/internal/operators/SingleOperatorZip.java
src/main/java/rx/internal/schedulers/SchedulerLifecycle.java
src/perf/java/rx/operators/OperatorTakeLastOnePerf.java
src/test/java/rx/CapturingUncaughtExceptionHandler.java
src/test/java/rx/NotificationTest.java
src/test/java/rx/ObservableConversionTest.java
src/test/java/rx/internal/operators/OnSubscribeConcatDelayErrorTest.java
src/test/java/rx/internal/operators/OnSubscribeFromCallableTest.java
src/test/java/rx/internal/operators/OperatorDoOnRequestTest.java
src/test/java/rx/internal/operators/OperatorIgnoreElementsTest.java
src/test/java/rx/internal/operators/OperatorTakeLastOneTest.java
src/test/java/rx/internal/operators/SingleOnSubscribeDelaySubscriptionOtherTest.java
src/test/java/rx/internal/schedulers/GenericScheduledExecutorServiceTest.java
src/test/java/rx/internal/schedulers/NewThreadWorkerTest.java
src/test/java/rx/internal/util/JCToolsQueueTests.java
src/test/java/rx/internal/util/SynchronizedQueueTest.java
src/test/java/rx/observables/AsyncOnSubscribeTest.java
src/test/java/rx/schedulers/SchedulerLifecycleTest.java
src/test/java/rx/schedulers/SchedulerTests.java

This PR simply adds missing license header to main and test files.

1.x: Add missing license headers

---

src/main/java/rx/internal/util/ScalarSynchronousObservable.java

Handling the case of 0 requests with the same code style as SingleDelayedProducer and SingleProducer.

Small code style consistency fix for WeakSingleProducer

---

CHANGES.md

Release 1.1.5 CHANGES.md update

---

src/main/java/rx/Single.java
src/test/java/rx/SingleTest.java

1.x: fix Single.flatMap not composing subscription through

---

DESIGN.md

I went through all the pending comments that weren't addressed.

Clean-up of the 2.x Design.md document
